### ISSUE TITLE
Need AWS Athena support in moto!!

### ISSUE THREAD

**Issue by kirang0725** [getmoto/moto#1524]
I am working on python lambda functions that will shoot a sql query to Athena as part of my process. The development part is done, i need to test my code, where i use moto for testing my lambda functions locally. 70% of my lambda function is sql code, is there a chance i get to moto support aws athena? Thanks.

**Comment by spulec** [comment]
As a general rule, new endpoints get added when people that need them have some extra time to add them to Moto.

Right now I don't have a particular use for this so I can't promise anything for timing.

If someone does have time, pull requests are much appreciated (even small one just to get a service started). If you have some example code you want to work, preferably with some example data, that can also speed up the process.

**Comment by farridav** [comment]
+1 For Athena support.

We are using Athena within more and more of our projects, and the ability to maintain full test coverage would be awesome. 

Thanks for your contributions thus far, and keep up the good work !

**Comment by fatlumv** [comment]
+1

My team have increased our use of Athena massively recently but have struggled when it comes to testing our solutions locally.

Adding Athena support to moto would be a great addition to an already powerful library.

**Comment by OmerJog** [comment]
+1 from me too

**Comment by iamlmn** [comment]
+1

**Comment by robinicole** [comment]
+1

**Comment by bblommers** [comment]
Moto already has these methods:
```
create_work_group
list_work_groups
```

What other methods would people like to see?

(Just trying to get a feel for what's most used, in case I want to have a crack at it..)

**Comment by jasonrhaas** [comment]
This is a comprehensive list:  https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html

But the most important ones are:

- `get_query_execution()`
- `get_query_results()`
- `start_query_execution()`
- `stop_query_execution()`

**Comment by dreamorosi** [comment]
@bblommers I see that `start_query_execution()`, `stop_query_execution()` and `get_query_execution()` have been implemented and merged in #2996 (thanks for implementing them) but for now the query stays in the `QUEUED` status indefinitely unless explicitly stopped, after which it passes to `CANCELLED`.
Me and my team would be interested in having a way of testing also around other states (`RUNNING`, `SUCCEEDED`, and `FAILED`) and we would be available to dedicate some time to do a PR but we are not sure of what would be an acceptable way of extending the [AthenaBackend](https://github.com/spulec/moto/blob/master/moto/athena/models.py#L73) without making a blocking action (thinking of a `time.sleep()`) or having to actually implement an actual query execution.

I have checked how similar cases are handled in moto for [DynamoDB Tables](https://github.com/spulec/moto/blob/73813460b66119dd2491f286a01bf07e0b18d193/moto/dynamodb2/models/__init__.py#L445) or [EC2 Instances](https://github.com/spulec/moto/blob/73813460b66119dd2491f286a01bf07e0b18d193/moto/ec2/models.py#L457) and in both cases the transition is skipped altogether in favor of the end state.

**Comment by bblommers** [comment]
Hi @dreamorosi, are you using the decorators? Most people fiddle with the state directly in their tests, if they have a specific use case. See this comment from spulec: https://github.com/spulec/moto/issues/380#issuecomment-123932483

**Comment by dreamorosi** [comment]
Hi @bblommers, thanks for the reply! I will try the option suggested in that issue but from a first look it seems it could fit our needs. I'll comment here in case it doesn't and we can discuss further.

**Comment by orenmazor** [comment]
throwing another vote for "SUCCEEDED" being the final state. most of my test suite relies on this case, and the tests that check other states can do manual intervention, as in #380

**Comment by nmerket** [comment]
Is there any way to put a small amount of test data in our mocked athena instance for querying or am I misunderstanding the scope of this?

**Comment by dreamorosi** [comment]
@nmerket that's not possible and goes beyond the scope of this project.

Almost all services are mocked in a way that basically instantiates and holds mock values at runtime.

The project leans more towards mocking AWS APIs so that you can run your tests against a local instance rather than the live environment. With that said, moto really shines at helping you test how your application interacts and deals with these APIs, data correctness should be handled separately.

**Comment by amoeedm** [comment]
Feel free to contribute on #4854, which aims to add:
`create_data_catalog`
`get_data_catalog`
`list_data_catalogs`

**Comment by bblommers** [comment]
We have since added an API that allows you to specify query execution results. Every call to `get_query_results` will then returns whatever data you have specified. 

See the `get_query_results`-documentation  here: http://docs.getmoto.org/en/latest/docs/services/athena.html

This feature is available as of moto >= 4.1.4

**Comment by bblommers** [comment]
As far as I can tell, all requested methods are now part of Moto. Queries are not actually executed, but the workaround above allows you to mock the exact response that you're expecting.

I'm going to close this - if there are any other issues or new features that you'd like to see, please open a new issue.
