### ISSUE TITLE
Strategy for triaging issues

### ISSUE THREAD

**Issue by spulec** [getmoto/moto#1659]
[Lodash](https://github.com/lodash/lodash) has an interesting strategy for handling their github issues: [here](https://twitter.com/samselikoff/status/991395669016436736)

In short:

- Feature requests are closed issues with `feature` label and `votes needed` label, and a 👍 emoji reaction
- Bugs are open issues tagged with `bug` label

For a project like Moto where there are an endless number of feature requests (every time AWS adds a service/endpoint), this feels very appealing. It would be great for us to be able to separate out the triage work. Establishing an easy way to give prioritization feedback would also be very helpful.

Any downsides? cc @JackDanger @terrycain

**Comment by JackDanger** [comment]
This sounds really good. I don't know if there's an easy way to automate this but it's a great policy and I'd be happy to help triage things like this.

**Comment by spulec** [comment]
I don't know if there is a way to automate it, but I'm optimistic it will be much easier to stay on top of things and keep them in order.

I think it will also require us to have a better definition of bugs. I'm leaning toward bugs being regressions only (or other egregious mistakes on our part).

**Comment by terrycain** [comment]
Thats really cool. But yes we'd need to properly define bugs, and might need to rename feature requests every now and again so they're easily spotted/searchable. And also be super clear in the readme about how to go about pleading for features.

**Comment by spulec** [comment]
It has been a year and I'm liking this more and more. We get so many feature requests that it seems impossible to maintain a project like this without a better strategy.

I'm going to work on a PR with an explanation of a philosophy in the README + CONTRIBUTING. I'll tag this issue once I create that. If everyone agrees on that, then we can work on some scripts to cleanup existing issues.

**Comment by terrycain** [comment]
Sounds good to me

**Comment by spulec** [comment]
Draft opened here: https://github.com/spulec/moto/pull/2314

Feedback appreciated!

**Comment by bblommers** [comment]
Since this discussion, we've gotten much better at dealing with incoming feature requests. Issues are now properly tagged, and the total list is much smaller. So I feel like this is no longer necessary, and the drawback of having 'invisible' issues, and having to educate users on why, outweighs the positive effects in my mind. 

I'll close this - but feel free to correct/discuss if you disagree!
