### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by sean-abbott** [getmoto/moto#2159]
Hello!  My company has an Open Source Fund that allows us to donate money to projects as long as they have a reasonable way to give to a foundation. 

I'd like to submit this project for donations, but it doesn't look like you have an org that we could submit to?

https://www.autoremarketing.com/technology/cargurus-gives-back-engineers-launch-open-source-fund

**Comment by spulec** [comment]
Thanks Sean; that is much appreciated. We don't have a solution to this today, but I would be open to suggestions from anyone.

Moto is very much a community project though so I would want a solution that can distribute funds to everyone that helps keep this project running. I don't know if that exists.

**Comment by dargueta** [comment]
Might be helpful? https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

**Comment by bblommers** [comment]
There's also [https://gitfund.io/tav/gitfund](GitFund), which seems to answer that question, How to distribute funds across all contributors.

Still in beta, but it looks like a serious contender to tackle the OS funding issue.

**Comment by bblommers** [comment]
We are now open for donations! There is a sponsor-button above every page, allowing you to donate either via Github Sponsors or directly to OpenCollective.

On OpenCollective you can also see our current financials: https://opencollective.com/moto

Thank you in advance for any donations - they will greatly help to ensure the stability and progress of Moto.

I'll close this, but do let us know if you have any questions around this.
