### ISSUE TITLE
Error handling for SNS mobile push does not match AWS

### ISSUE THREAD

**Issue by taion** [getmoto/moto#2333]
Currently, the Moto SNS mock raises an error with code `DuplicateEndpoint` when attempting to create a second platform endpoint using the same token.

This is not actually the behavior on AWS. On AWS, when attempting to do this, when not setting `CustomUserData`, the operation actually returns the existing endpoint.

AWS will raise an exception when `CustomUserData` is set, but the exception raised is of code `InvalidParameter`. Additionally, the exception thrown will have a reason of a specific format: `Endpoint <ARN> already exists with the same Token, but different attributes.` The docs explicitly recommend parsing this reason to get the existing ARN.

References:
- Documentation of current behavior: https://docs.aws.amazon.com/sns/latest/dg/mobile-platform-endpoint.html#mobile-platform-endpoint-sdk-examples
- Documented error types (notably excluding `DuplicateEndpoint`): https://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformEndpoint.html

**Comment by taion** [comment]
Also, if the ARN does not exist, it appears that we actually get an `InvalidParameter` error from AWS with message: `Invalid parameter: TargetArn Reason: No endpoint found for the target arn specified`, rather than the `NotFound` that Moto gives.

**Comment by spulec** [comment]
Thanks for opening. I'm setting this as a feature request.

**Comment by tzusman** [comment]
From [SNS CreatePlatformEndpoint](https://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformEndpoint.html) docs, `The CreatePlatformEndpoint action is idempotent, so if the requester already owns an endpoint with the same device token and attributes, that endpoint's ARN is returned without creating a new endpoint`.

I believe [this line](https://github.com/spulec/moto/blob/master/moto/sns/models.py#L371) should simply be replaced with `return endpoint` to make it consistent with the AWS docs.

**Comment by taion** [comment]
That's not quite correct. If `CustomUserData` is set, then AWS will reject the request.

**Comment by tzusman** [comment]
@taion It seems maybe the SNS push notification flow isn't well covered as the next error I run into is `NotFound: Topic does not exist` even though the ARN is the same as when I run `list-endpoints-by-platform-application` with the aws cli.  This same code successfully sends push notifications to devices when pointed to an AWS region.

This is the go code that results in the `Topic does not exist` error, I'm guessing it's because I'm sending a `TargetArn` and not a `TopicArn`, although that's how to send a push notification:
```
input := &sns.PublishInput{
	Message:          aws.String(string(m)),
	MessageStructure: aws.String("json"),
	TargetArn:        aws.String(endpointArn),
}
```

**Comment by aonamrata** [comment]
Is there an ETA on when this will be available?

**Comment by bblommers** [comment]
Hi @aonamrata, the majority of our features/bugs are fixed by the community, i.e. by people who need it the most. So we don't have an ETA/timeline for this - it all depends on whether someone wants to take the time to propose a PR with a fix.

**Comment by aonamrata** [comment]
> 
> 
> Hi @aonamrata, the majority of our features/bugs are fixed by the community, i.e. by people who need it the most. So we don't have an ETA/timeline for this - it all depends on whether someone wants to take the time to propose a PR with a fix.

Ok, i just saw a pull request and thought someone was already working on it. But if not i can get something 😸

**Comment by bblommers** [comment]
Took a while, but all these error scenarios should now all work correctly as of moto >= 4.2.7.dev29
