### ISSUE TITLE
NotImplementedError: allocate_hosts

### ISSUE THREAD

**Issue by ConnorWescott-TR** [getmoto/moto#2423]
`NotImplementedError: The allocate_hosts action has not been implemented`

Method used to generate issue:

```
def setup_mock_dedicated_host(zone):
    response = ec2client.allocate_hosts(
        AvailabilityZone=zone,
        InstanceType='t3a.nano',
        Quantity=1
    )
    return response
```
I am using Moto version 1.3.13.

Creating this issue as a feature request to implement this functionality.

**Comment by spulec** [comment]
Thanks for opening. Tagging this as a feature request.
