### ISSUE TITLE
Add support for EventBridge partner methods

### ISSUE THREAD

**Issue by dmulter** [getmoto/moto#2572]
Thanks so much for the great work on initial support in #2322. Specifically I am looking for support for the following partner methods.

* `create_partner_event_source()`
* `delete_partner_event_source()`
* `put_partner_events()`

**Comment by spulec** [comment]
Thanks for opening; setting this as a feature request.

**Comment by sdouek** [comment]
please , I am looking for this feature too.
Do you have a plan for this implement ? Thanks!

**Comment by kurtqq** [comment]
would be great to have this!
