### ISSUE TITLE
Full Step Functions Execution Support

### ISSUE THREAD

**Issue by prestomation** [getmoto/moto#3544]
I didn't see this in the issues, so my apologies if it's already filed. 

This is a feature request for full Step Function execution support, such that test code could call sfn.StartExecution and get a production-like execution of a state machine, including retries, error handling, concurrency, choice evaluation, etc, and actually runs application code.
Something like StepFunctionsLocal from AWS, which is in java: https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local.html

I appreciate that implementing all of step functions is a daunting task! I will describe a subset that I think would be useful to a large set of developers. 

My ideal implementation would support State Language and lambda task integration. 

I suppose of course it could it integrate with moto.lambda to run lambda functions, but I think some kind of configuration interface/escape hatch enabling test writers to implement their own implementation of any task type would keep it flexible enough for users to do some minimal work to keep up with new step functions features. 

In my case, I would hook the lambda tasks directly to my own worker code and skip the lambda worker model that moto has, as I don't use this

**Comment by bblommers** [comment]
Hi @prestomation, that is daunting indeed! Are you using the decorators, or server mode?

Considering the StepFunctionsLocal already exists, the easiest implementation might be to just start that Docker-image from within Moto. Appropriate calls can than simply be forwarded, and we get all the functionality without having to figure out all the logic ourselves. 

The big downside is that calling Lambda's would only be possible in Server Mode.

Not sure how we would be able to intercept any Lambda-calls, and execute a provided workder code instead, with that solution.

**Comment by Leooo** [comment]
Hello, we are refactoring our CI from a lambda / s3 / cloudwatch / cfn based architecture to a step-function based one, and not being able to port moto mocks atm is certainly a blocker on our side. 

I understand why this would be a very big work to port. Does anyone have an idea of which designs could allow moto to consume the [StepFunctionsLocal](https://hub.docker.com/r/amazon/aws-stepfunctions-local) docker image? 

If this is not the way moto works (at least when not in server mode), then could the only solution be to mock all step functions logic into moto ? Which would be a big work of course, but wondering if we could try to help in that case maybe.

Any other possibilities? Thanks

**Comment by bblommers** [comment]
Using the server mode is definitely the easiest way, as (as far as I can tell) that does not need any work on Moto's side.

When using decorators:
One option would be to run a server, and pass in the models/backends (created by the decorator) that the server will update.
The starting point would be similar to ServerMode, but the way it deals with incoming requests would be very different.

The workflow would then be:
User calls start_execution
Moto starts a server
Moto starts the StepFunctionsLocal as a Docker image, passing in the server endpoint for Lambda/SQS/etc endpoints

Pros:
1. No recreating any of the step functions logic (ASL parsing)

Cons:
1. As it's an asyncronous process, there is no logical entrypoint where Moto can kill the server. If the unit test fails, the user would have to kill this server manually
2. AWS Lambdas will be executed inside a Docker container (as usual). That means there's no way of mocking any HTTP requests.
3. Very complex from a software architecture point of view, and difficult to debug (decorator calls Docker calls server calls Docker (for AWS Lambda))

It would also blur the lines between the Docker implementatino and our own. Would we even need to keep any of our current SFN implementation, or do we just redirect to the StepFunctionsLocal image?

As I was thinking this through I got quite excited with the potential functionality it would give us, but now that I'm listed the cons, I'm not so sure about it anymore.

@spulec Quick ping in case you have any thougths on this

**Comment by bblommers** [comment]
> could the only solution be to mock all step functions logic into moto ?

If somebody is willing to do the work for this, yeah - that might be more feasible. It's easier to debug, easier to implement it gradually.
It will have the same limitation that there would be no way of mocking HTTP requests, though.

**Comment by Leooo** [comment]
I managed to run a quite complex state machine from one test using moto_server and the docker image for step function local. Happy to write down more details later but the outlines are (as @bblommers advised):

1) run `moto_server` (on http://127.0.0.1:5000/)

2) run the SAM local step function docker image: 
```
docker run -p 8083:8083 --env-file aws-stepfunctions-local-credentials.txt amazon/aws-stepfunctions-local:1.7.3
```
with the following config file (aws-stepfunctions-local-credentials.txt):
```
AWS_DEFAULT_REGION=eu-west-1
LAMBDA_ENDPOINT=http://host.docker.internal:5000/
```

3) declaring the tests with (excerpts only):
```python
import boto3
for service_name in ['s3', 'cloudformation', 'ec2', 's3', 'iam']:
    boto3.resource(
        service_name=service_name,
        region_name=LAMBDA_REGION,
        endpoint_url='http://127.0.0.1:5000/'
    )

#still using @mock_ssm

stack = {} # actually a Class
stack.s3Client = boto3.client(
  's3',
  LAMBDA_REGION,
  endpoint_url='http://localhost:5000'
)
stack.ec2Client = boto3.client(
  'ec2',
  endpoint_url='http://localhost:5000'
)
stack.clientCf = boto3.client(
  'cloudformation', 
  region_name=LAMBDA_REGION,
  endpoint_url='http://localhost:5000'
)
stack.clientIam = boto3.client(
  'iam',
  endpoint_url='http://localhost:5000'
)

stack.lambdaClient = boto3.client('lambda',
    endpoint_url='http://localhost:5000',
    region_name=LAMBDA_REGION
)
genericLambda = stack.lambdaClient.create_function(
    FunctionName="testFunction",
    Runtime="python3.7",
    Role=_get_default_role(), #defined elsewhere
    Handler="lambda_function.lambda_handler",
    Code={"ZipFile": get_test_zip_file1()}, #for example, same as in https://github.com/spulec/moto/blob/ddd3c0edc4934d84bd12d04f32df00274b8a2ff7/tests/test_awslambda/test_lambda.py#L44
    Description="test lambda function",
    Timeout=3,
    MemorySize=128,
    Publish=True,
)

stack.clientStepFunctions = boto3.client(
    'stepfunctions',
    LAMBDA_REGION,
    endpoint_url='http://localhost:8083' # provided by SAM step function local run from docker
)

name = "example_step_function"
with open('digital_Nested_Web_CI_Stack/statemachines/run_codebuild_jobs_and_process_output.asl.json', 'r') as stream:
    myTemplateJson = json.dumps(json.load(stream)).\
        replace("${buildCodebuildParametersArn}", genericLambda['FunctionArn']).\
        replace("${buildBaseMessageArn}", genericLambda['FunctionArn']).\
        replace("${buildFailingTestsMessageArn}", genericLambda['FunctionArn']).\
        replace("${postMessageArn}", genericLambda['FunctionArn']).\
        replace("${postStatusCheckArn}", genericLambda['FunctionArn']).\
        replace("${concatenateAttributeFromMapArn}", genericLambda['FunctionArn']).\
        replace("${buildCodebuildParametersArn}", genericLambda['FunctionArn']).\
        replace("${buildCoverageMessageArn}", genericLambda['FunctionArn']).\
        replace("${codebuildResourceString}", "arn:aws:states:::codebuild:startBuild")
    response = stack.clientStepFunctions.create_state_machine(
        name=name,
        definition=myTemplateJson,
        roleArn=_get_default_role(),
    )
    event = create_github_event_from_params(test_params)

    event['StageName'] = 'dummy_stage_name'
    execution = stack.clientStepFunctions.start_execution(
        stateMachineArn=response["stateMachineArn"],
        input=json.dumps(event)
    )
    description = stack.clientStepFunctions.describe_execution(executionArn=execution["executionArn"])
```

**Comment by Leooo** [comment]
@bblommers fyi in the above I see **ONE** thing which I think is a blocker to add proper testing atm: not being able to use [`start_sync_execution`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.start_sync_execution) yet - so that we can test the step function return values after everything is finished. 

Any way  I could help adding that to Moto ? (disclaimer: it would be my first open-source python contribution so woud need some guidance please..)

Thanks

**Comment by Leooo** [comment]
Note: start & stop `moto_server` and `SAM step function local` in your test with:


```python
        moto_server_cmd = subprocess.Popen(
            ['moto_server'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )
        # 'aws-stepfunctions-local-credentials.txt' defined above should be in same folder as the one where you call your tests (root?)
        sam_step_function_local_cmd = subprocess.Popen(
            ['docker', 'run', '-p', '8083:8083', '--env-file', 'aws-stepfunctions-local-credentials.txt',
             'amazon/aws-stepfunctions-local:1.7.3'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )

        try:
          # your tests
        finally:
            moto_server_cmd.terminate()
            sam_step_function_local_cmd.terminate()
```
```

**Comment by bblommers** [comment]
Thanks for the feedback, and providing a more detailed guide on how to do this, @Leooo! Good to see it works in practice, not just in theory.

> Any way I could help adding that to Moto ?

Now that all SFN calls are pointed to the Docker container it's probably not necessary at all.

Having said that, if you do want to add the method to moto, PR's are always welcome!
All it would take is another method `def start_sync_execution` in responses.py.
Considering there's no difference in functionality atm, you might just be able to get away with redirecting to the existing [start_execution method](https://github.com/spulec/moto/blob/master/moto/stepfunctions/responses.py#L134)
Testing it would then just involve a simple copy/paste of the start_execution test: https://github.com/spulec/moto/blob/master/tests/test_stepfunctions/test_stepfunctions.py#L488

**Comment by Leooo** [comment]
```LAMBDA_ENDPOINT=http://host.docker.internal:5000/``` seems to only work on my MAC, and not on `ubuntu-latest` in github actions (even with Docker 20.10.3). Tried https://stackoverflow.com/a/43541732/1984997 and others without success - this seems to be more of a [stepfunctions-local issue](https://stackoverflow.com/a/57088919/1984997) though

**Comment by bblommers** [comment]
We now have a proper SFN Parser, as of Moto >= 5.0.4.dev17.

It is disabled by default, but enabled with a simple configuration:
`@mock_aws(config={"stepfunctions": {"execute_state_machine": True}})`

This functionality was taken [from LocalStack](https://github.com/localstack/localstack/tree/master/localstack/services/stepfunctions), who developed an in-memory pure Python parser. It supports calls to other services and most of the SFN features like waits, retries, catch, etc.

Please try it out! And let us know if you run into any issues.
