### ISSUE TITLE
How to mock `invoke_endpoint` of sagemaker?

### ISSUE THREAD

**Issue by mhihasan** [getmoto/moto#4180]
Is there any way to mock `invoke_endpoint` operation of AWS Sagemaker?

Thanks

**Comment by bblommers** [comment]
Hi @mhihasan, no, not at the moment. Will mark it as an enhancement to implement this feature.

**Comment by mhihasan** [comment]
Could I own this task? Could you assign me?

**Comment by bblommers** [comment]
Definitely! There's a section in our [Contributing-doc](https://github.com/spulec/moto/blob/master/CONTRIBUTING.md#missing-services) to get you started - let me know if I can help in any way.

**Comment by ghinch** [comment]
@mhihasan did you make any progress on this?

**Comment by wolfyz-consulting** [comment]
This would be totally awesome to have

**Comment by tansaku** [comment]
I'd love this feature too - are there any other alternatives? like using https://github.com/kevin1024/vcrpy to record some request responses?  or just some kind of magic mock?

**Comment by tansaku** [comment]
I've just user `patch.object` with some success:

```py
with patch.object(MyClass, "invoke_endpoint", side_effect=lambda x, y: ([], [])) as _:
```

**Comment by mattrankin0** [comment]
Hi @tansaku what is `MyClass` here? The sagemaker client?

**Comment by drduhe** [comment]
The class that you want to override a stubbed out version of the INVOKE_ENDPOINT method the SM SDK supports @mattrankin0. It would be a local service level class where the SM client is used to invoke that method.

**Comment by bblommers** [comment]
This feature is now part of moto >= 4.2.1.dev31.

See the documentation for information on how to configure the desired response:

http://docs.getmoto.org/en/latest/docs/services/sagemaker-runtime.html

**Comment by drduhe** [comment]
Ayyyy awesome stuff and thank you!
