### ISSUE TITLE
Feature Request: Implement describe_queries and get_query_results for LogsBackend

### ISSUE THREAD

**Issue by n3rdgir1** [getmoto/moto#5015]
I get the `NotImplementedError` for `describe_queries` and `get_query_results`.

**Comment by bblommers** [comment]
Hi @n3rdgir1, thanks for raising this! Will mark it as an enhancement.

If you're interested in implementing these features yourself, PR's are always welcome! We have some documentation here: http://docs.getmoto.org/en/latest/docs/contributing/index.html - happy to answer any questions if this is something you want to look into.

**Comment by bblommers** [comment]
Hi @n3rdgir1, this is now part of moto >= 4.2.1.dev17.

The query parsing logic is quite basic for now - feel free to create a new issue if you see any problems with the result for a specific query.
