### ISSUE TITLE
Allow mock_batch_simple to mock a FAILED result

### ISSUE THREAD

**Issue by jwarwick-delfi** [getmoto/moto#5168]
The mock_batch_simple functionality is a great way to test integration with AWS batch, but it always sets the job status to SUCCEEDED. It would be great to parameterize this, so I could simulate a failure.

Something like this would be great:
```
with mock_batch_simple(succeed=False):
    ...
```

**Comment by mahi072** [comment]
Hi I would like to work on this issue

**Comment by rdbisme** [comment]
I'd love to have a timer functionality such that, after a while, the job fails.

**Comment by rafcio19** [comment]
@mahi072 how are you getting on with this? I can take over if not much progress has been made

**Comment by bblommers** [comment]
@rafcio19 Thanks for looking into this! I don't think that Moto supports anything similar at the moment, so there is no existing solution that we can apply here. When you get around to it, it might be good to share your suggested solution here first so we can talk it through, just to make sure it fits in with Moto's design.

**Comment by bblommers** [comment]
This is now part of moto >= 4.1.8.dev11. You can now set an environment variable to simulate a failure in `mock_batch_simple`:
`MOTO_SIMPLE_BATCH_FAIL_AFTER=0` --> fail immediately
`MOTO_SIMPLE_BATCH_FAIL_AFTER=x` --> fail after x seconds
