### ISSUE TITLE
Plans on Cost Explorer's get_cost_and_usage

### ISSUE THREAD

**Issue by Suzy12** [getmoto/moto#5596]
Hello! I am aware Cost Explorer is available now in moto, but only for [certain features](http://docs.getmoto.org/en/latest/docs/services/ce.html?highlight=cost%20explorer#moto.ce.models.CostExplorerBackend).
So, I have a quick question, are there any plans on mocking Cost Explorer's **get_cost_and_usage**?

**Comment by bblommers** [comment]
This is now part of `moto >= 5.0.3.dev16`.

Cost or usage is not tracked by Moto, so this call will return nothing by default. You can configure your own results though, so the API will return whatever data you want.
See the documentation here:

http://docs.getmoto.org/en/latest/docs/services/ce.html
