### ISSUE TITLE
add default policy document to create_vpc_endpoint

### ISSUE THREAD

**Issue by sergargar** [getmoto/moto#5602]
When I don't specify a policy document to create_vpc_endpoint function, moto does not create a default full access policy to the endpoint like AWS does:
> PolicyDocument (string) -- (Interface and gateway endpoints) A policy to attach to the endpoint that controls access to the service. The policy must be in valid JSON format. If this parameter is not specified, we attach a default policy that allows full access to the service.

**Comment by bblommers** [comment]
Hi @sergargar! I'm not too familiar with this area, so apologies if this is an obvious question:
Does AWS create an actual IAM policy for you, using either the provided `policy_document`-value or the default? That is currently not supported in Moto either - from what I can see, we only persist the `policy-document`-value.

And also, are you able to share the default policy that AWS provides?

**Comment by sergargar** [comment]
Hi @bblommers, thank you for your quick response!

I was able to force the creation of the default policy that AWS provides if no PolicyDocument is given:
```
  PolicyDocument=json.dumps(
      {
          "Statement": [
              {
                  "Action": "*",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Resource": "*",
              }
          ]
      }
```

AWS only attaches this policy if no policy_document is given by the user in the create_vpc_endpoint function.
