### ISSUE TITLE
Type not validated with SSM put_parameter

### ISSUE THREAD

**Issue by mdavis-xyz** [getmoto/moto#5740]
# Steps to reproduce

```
import boto3
from moto import mock_ssm

with mock_ssm():
    client=boto3.client('ssm')
    param_name = 'test_param'
    client.put_parameter(
        Name=param_name,
        Value="Contents of param", 
        Type='str' # this is a bug in my code I want moto to detect
    )
    
    client.delete_parameter(Name=param_name)
```

Run that code.
Then comment out `with mock_ssm():` and unindent the lines below that, and re-run (to run against real AWS.)

## Expected behavior

```
Traceback (most recent call last):
  File "badstr.py", line 7, in <module>
    client.put_parameter(
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutParameter operation: 1 validation error detected: Value 'str' at 'type' failed to satisfy constraint: Member must satisfy enum value set: [SecureString, StringList, String].
```

The correct usage is `Type='String'` not `Type='str'`.

## Actual behavior

The script passes. Moto did not detect that I passed invalid parameters to boto.

The parameter is created. Subsequent `describe_parameters()` calls show `Type='str'`.

**Comment by mdavis-xyz** [comment]
I've tried to spot where validation is supposed to be done.

We could add a check here somewhere:
https://github.com/spulec/moto/blob/8f074b0799e4e5303f219549e177d52b016c2dfb/moto/ssm/models.py#L188

But isn't moto supposed to do this with some programmatic magic, prior to getting to the hand-crafted code?

**Comment by bblommers** [comment]
All of our code is magic!

We always have to handcraft it though. If Boto3 doesn't complain about it, there is no way for us to know which inputs are valid/limited. Request validation typically happens in `responses.py`: 
https://github.com/spulec/moto/blob/4eb3944b1d9d8f513f1cb96425f60ae41039a831/moto/ssm/responses.py#L277

**Comment by mdavis-xyz** [comment]
What do you mean by "If boto3 doesn't complain about it"? I assume you mean if the error is raised by the service behind the API, instead of in the SDK prior to sending the request over the wire. How do I find out whether this error is thrown by boto or the service?

Note that the boto docs show this parameter as an enum, not a generic string. So that makes me think that boto3 will validate the values, which I would expect moto to check automatically.

The line you linked to, I can't see validation for *any* argument, not just this one.
[`_get_param`](https://github.com/spulec/moto/blob/4eb3944b1d9d8f513f1cb96425f60ae41039a831/moto/ssm/responses.py#L155) just reaches into the [request_params property](https://github.com/spulec/moto/blob/4eb3944b1d9d8f513f1cb96425f60ae41039a831/moto/ssm/responses.py#L17), which just calls `json.loads(self.body)`.

So I'm confused now. I thought moto used the service definition files to figure out what arguments are allowed, which are required, what their types are, etc. I thought that's part of what `scripts/scaffold.py` does. 

Or is every argument for every function manually validation like [this argument](https://github.com/spulec/moto/blob/4eb3944b1d9d8f513f1cb96425f60ae41039a831/moto/s3/models.py#L194)?

**Comment by bblommers** [comment]
> What do you mean by "If boto3 doesn't complain about it"? I assume you mean if the error is raised by the service behind the API, instead of in the SDK prior to sending the request over the wire. How do I find out whether this error is thrown by boto or the service?
> 

The fool-proof way is to invalidate your AWS keys first, and then remove the Moto-decorator. If the call to AWS fails because of invalid credentials, the error is thrown by the service.
Runtime of the test can also be a good indicator - if the test finishes in <10ms, the error is probably thrown by boto - any call to AWS/Moto takes much longer.

 
> So I'm confused now. I thought moto used the service definition files to figure out what arguments are allowed, which are required, what their types are, etc. I thought that's part of what `scripts/scaffold.py` does.
> 

`scripts/scaffold` is only used when adding a new service/method to Moto. It will read the service definition files, but just to get the list of arguments.

Using the service definitions to automatically add validation is an interesting idea, but I would be worried about a) performance and b) being too restrictive if the service definition is wrong/out of date.

> Or is every argument for every function manually validated like [this argument](https://github.com/spulec/moto/blob/4eb3944b1d9d8f513f1cb96425f60ae41039a831/moto/s3/models.py#L194)?

Yes. If validation exists, it is done manually like that.

**Comment by mdavis-xyz** [comment]
Some details that I'll add to the unit tests:

```
ex.operation_name='PutParameter'
ex.response["ResponseMetadata"]["HTTPStatusCode"]=400
ex.response["Error"]["Code"]='ValidationException'
ex.response["Error"]["Message"]="1 validation error detected: Value 'str' at 'type' failed to satisfy constraint: Member must satisfy enum value set: [SecureString, StringList, String]"
```

from:

```
import boto3

client=boto3.client('ssm')
param_name = 'test_param'
try:
    client.put_parameter(
        Name=param_name,
        Value="Contents of param", 
        Type='str' # this is a bug in my code I want moto to detect
    )
except client.exceptions.ClientError as ex:
    print(f"{ex.operation_name=}")
    print(f'{ex.response["ResponseMetadata"]["HTTPStatusCode"]=}')
    print(f'{ex.response["Error"]["Code"]=}')
    print(f'{ex.response["Error"]["Message"]=}')
else:
    client.delete_parameter(Name=param_name)
    raise ValueError("Expected error")

```
