### ISSUE TITLE
Feature request: Add support for ECDSA_SHA_256 signing

### ISSUE THREAD

**Issue by cwkang1998** [getmoto/moto#5761]
Currently, moto ignores and hardcodes signing_algorithm to RSASSA_PSS_SHA_256.

I would love to add support for ECDSA_SHA_256 signing, for `["ECC_NIST_P256", "ECC_SECG_P256K1"]` key specs. Of course, eventually hopefully we can add support for the other `ECDSA` and `RSASSA` signing algorithms as well.

Would be trying to implement this myself.

**Comment by bblommers** [comment]
Thanks for raising this @cwkang1998, and welcome to Moto! A PR would be very welcome - we have a section in our docs to get you started with contributing to Moto: 
http://docs.getmoto.org/en/latest/docs/contributing/index.html 

Please let us know if you need any help.

**Comment by tsugumi-sys** [comment]
I take on this task!

**Comment by tsugumi-sys** [comment]
| key spec | signing algorithm |
| :---: | :---: |
| `SYMMETRIC_DEFAULT` | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
| RSA_2048, 3072, 4096 | |
