### ISSUE TITLE
Feature Request: Set Event Bus from cross account as forwarding rule for Event Bridge

### ISSUE THREAD

**Issue by srinivascheeti1** [getmoto/moto#5786]
Hello :)

Thanks for developing and improving this great and helpful library!

Versions we used:

moto==4.0.3
Here's our feature request (I used the search function but didn't find a similar request):

Current state:
Trying to mock event bridge to have event bus in Account 1 send forward events to event bus in Account 2. This is currently not supported.

This feature would really help us in our testing design!

Here is a stackoverflow request for the same.

https://stackoverflow.com/questions/74842991/mocking-cross-account-event-bridge-target-rules?noredirect=1#comment132085113_74842991

**Comment by bblommers** [comment]
Hi @srinivascheeti1! This is now part of Moto 4.1.1 - I've used your test-case from SO to verify it works as expected. Please let us know if you run into any issues.
