### ISSUE TITLE
Error is not displaying when we add "deny policy" to S3 buckets.

### ISSUE THREAD

**Issue by GovindSkand** [getmoto/moto#5820]
@bblommers 

Steps:

1. Create a new S3 bucket.
2. Add the policy with the effect set to deny.
3. Upload a file and observe.

Actual: No error is displayed after uploading the file.

Expected : When our policy effect is "Deny," an access denied error message should be displayed. 

Code : 
     bucket_policy = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Deny",
                "Principal": "*",
                "Action": "s3:*",
                "Resource": ["arn:aws:s3:::testbucket","arn:aws:s3:::testbucket/*"],
                "Condition": {
                    "ArnNotLikeIfExists": {
                        "aws:PrincipalArn": [
                            "arn:aws:iam::(userid):role/lambda-execution-role"
                        ]
                    }
                }
            }
        ]
    }

    s3_client = boto3.client('s3')
    s3_client.create_bucket(Bucket='testbucket')

    file_path = 'C://Users//PycharmProjects//datbase//inputs//'
    object_name = 'expectedfile.csv'
    s3_client.put_bucket_policy(Bucket='testbucket', Policy=json.dumps(bucket_policy))
    result = s3_client.get_bucket_policy_status(Bucket='testbucket')
    path_of_file = os.path.join(file_path, object_name)
    res = s3_client.upload_file(path_of_file, 'testbucket', 'hello.csv')
    reading_content = s3_client.get_object(Bucket='testbucket', Key='hello.csv')
    print(reading_content["Body"].read())

Please do let me know where i am doing wrong.

Help me

https://www.geeksforgeeks.org/create-bucket-policy-in-aws-s3-bucket-with-python/

i need to restrict bucket policy in s3 bucket.

**Comment by bblommers** [comment]
Hi @GovindSkand, thanks for raising this. Bucket policies are not yet fully supported in Moto; at the moment we only validate the policy when calling the `get_object` operation. So we would have to extend this to also cover the `upload_file` op.

I'm not sure how we would handle the `ArnNotLikeIfExists`-condition, though. Moto does not know about IAM roles when a request comes in, as we completely ignore the provided authentication credentials.

My initial instinct would be to always evaluate the condition to True - to block all incoming `upload_object`-requests.
Would that work for you?

**Comment by GovindSkand** [comment]
@bblommers Thanks for your reply. Yeah it will work for me. I just want to know in which line I need to evaluate my condition to True. So that it can block all my upload object. Please do suggest me.

**Comment by GovindSkand** [comment]
Hello Spulec/Moto,

I have replied to the ticket. Please let me know where I need to evaluate
the condition to become true. So that it can block the upload object.

Regards,
Govind.K.R

**Comment by bblommers** [comment]
Bucket policies are not yet fully supported in Moto @GovindSkand , so we will need to make some enhancements before this works. We'll let you know when this feature is added.

**Comment by bblommers** [comment]
Hi @GovindSkand, this feature is now part of moto >= 4.1.2.dev13

Note that the action should be `"Action": "s3:*"`, with an asterisk - just `"Action":"s3:"` is not valid in Moto or AWS
