### ISSUE TITLE
Doubts with Session clients

### ISSUE THREAD

**Issue by w0rmr1d3r** [getmoto/moto#5833]
## Doubt

I have searched in GitHub issues but didn't find anything, nor in the official docs.
The question is, there's already a way to mock clients from boto3 directly, but, is there a way to mock clients based on session?

Example:
```python
# some python code
client = boto3.client("sts") # this can be mocked
response = client.assume_role(RoleArn=arn, RoleSessionName="sessionname")

credentials = response.get("Credentials")

session = boto3.Session(
    aws_access_key_id=credentials["AccessKeyId"],
    aws_secret_access_key=credentials["SecretAccessKey"],
    aws_session_token=credentials["SessionToken"],
   )

# how can I mock this using moto ?
cloudformation_client = session.client("cloudformation", region_name=self.region)
```

Thank you in advance

**Comment by bblommers** [comment]
Hi @w0rmr1d3r, that should work as well - clients based on session are mocked in the same way.
The below works, as a small standalone example:
```
import boto3
from moto import mock_sts, mock_cloudformation


@mock_cloudformation
@mock_sts
def test():
    client = boto3.client("sts")
    response = client.assume_role(RoleArn="arnasdfasdfasdfasdafas", RoleSessionName="sessionname")

    credentials = response.get("Credentials")

    session = boto3.Session(
        aws_access_key_id=credentials["AccessKeyId"],
        aws_secret_access_key=credentials["SecretAccessKey"],
        aws_session_token=credentials["SessionToken"],
    )

    # how can I mock this using moto ?
    cloudformation_client = session.client("cloudformation", region_name="us-east-1")
    stacks = cloudformation_client.list_stacks()
    print(stacks)
```

Are you running into any specific issues?

**Comment by w0rmr1d3r** [comment]
Hi @bblommers ,
Actually, we already had a couple of tests using both `mock_sts` and `mock_cloudformation`, as you show on the example. We were using `moto` in the latest release from version 3, I think it was 3.1.something.
Out of nowhere, a tests started failing in the CI, so I decided to bump `moto` to the latest version available. Then, those tests started failing for the mock on the CloudFormation client when using it from a session.

I ended up extracting that code and mocking it with `patch` from `mock`.

The client from a session gets created in some part of the code, not in the test itself, if it gives more context.

Thank you

**Comment by bblommers** [comment]
> The client from a session gets created in some part of the code, not in the test itself
>

Has the import order changed, by any chance? The boto3 clients have to be created while the mock is active, for Moto to work - see http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure

Can you create/share a small reproducible test case that is failing?

**Comment by bblommers** [comment]
Those bits of code in isolation work just fine.  I've created a sample project for this, and this simple test passes: https://github.com/bblommers/mock_test_sessions/blob/main/tests/test_session.py
The logic is here: https://github.com/bblommers/mock_test_sessions/blob/main/mock_test_sessions/logic.py

So there is something else in your setup that's causing the failure.

**Comment by w0rmr1d3r** [comment]
Thanks @bblommers .
I'll take a closer look at my setup and check what's wrong.
Will close the issue, since this seems to be related to the project and not to moto itself. Appreciate it
