### ISSUE TITLE
SES region setting is not supported

### ISSUE THREAD

**Issue by FelixRoche** [getmoto/moto#5842]
Hi,
when trying to set the region of the SES client, it seems like it is not setting the region correctly and just defaults to the global region. 
It seems like this is a bug caused in this file:
https://github.com/getmoto/moto/blob/master/moto/ses/responses.py in line 14 where the region gets set to global instead of self.region as seen here:
https://github.com/getmoto/moto/blob/master/moto/sns/responses.py on line 23.
I am currently using version 1.21.46.

**Comment by bblommers** [comment]
Hi @FelixRoche, I cannot see a mention of `global` in that particular file.

Do you have a specific test case that is failing for you?

**Comment by FelixRoche** [comment]
Hi @bblommers, the mention of global would be on the master branch in line 14 in the backend(self) method

I can provide some example on how it is working and how I would expect it to work on a region based service:
When verifying an email it verifies it on every region instead of the one specified in the client
My expected behavior would be only finding one identity not finding one in every region
Example code to check:

```
def test_for_email_safety(self):
        client = boto3.client("ses", region_name="eu-west-1")
        client.verify_email_identity(EmailAddress="foo@bar.com")

        regions = ["ap-northeast-1", "ap-southeast-1", "eu-central-1", "eu-west-1", "us-east-1", "us-west-2"]

        found_emails = 0

        for reg in regions:
            found_emails += len(client.list_identities().get("Identities"))

        assert found_emails == 1
```

**Comment by bblommers** [comment]
Ah, gotcha @FelixRoche. Looks like it was never implemented as a region-based service in the first place, and even after various refactorings we kept using it as if it was a `global` service. Marking it as a bug.

Thanks for raising this!
