### ISSUE TITLE
List object is not listing all the expected file post successful glue job execution using mock framework.

### ISSUE THREAD

**Issue by GovindSkand** [getmoto/moto#5848]
Sample code that trying to run using mock glue.

def create_glue_job():

	bucket = "mybucket"

	s3 = boto3.client('s3')
	s3.create_bucket(Bucket=bucket)

	file_path = 'C://Users//datbase//'  #Providing the local path as the glue script is placed in local machine
	object_name = 'redshiftconnector.py'

	path_of_file = os.path.join(file_path, object_name)
	file_upload = s3.upload_file(path_of_file, bucket, 'edshiftconnector.py')
	
	reading_content = s3.get_object(Bucket=bucket, Key='edshiftconnector.py')
	print(reading_content['Body'].read())  ## able to fetch the uploaded file.
	
	# Next step is use create glue jog using mock
	
	client = boto3.client('glue')
	
	response = client.create_job(
        Name='IrisJob',
        Role='AWSGlueServiceRole-Demo',
        Command={
            'Name': 'glueetl',
            'ScriptLocation': 's3://mybucket/edshiftconnector.py',
            'PythonVersion': '3'
        },
        DefaultArguments={
          '--TempDir': 's3://mybucket/temp_dir',
          '--job-bookmark-option': 'job-bookmark-disable'
        },
        MaxRetries=1,
        GlueVersion='3.0',
        NumberOfWorkers=2,
        WorkerType='Standard'
    )
	
	print(json.dumps(response, indent=4, sort_keys=True, default=str))  # Once job is created, able to see response code as 200.
	
	response1 = client.start_job_run(JobName='IrisJob')
    print("respons1", response1)  # Start job also works fine with out any issue, here also able to see response code as 200.
	
	"Checking the outcome of above run job by using list_objects".
	response = client.list_buckets()
	for key in conn.list_objects(Bucket='bucket_name')['Contents']:
		print(key['Key'])  # Expecting list of the objects inside the bucket.
		

	As part of my activity, I am trying to run the above created job(IrisJob) by passing the script location path('s3://mybucket/edshiftconnector.py') for the created Job(IrisJob). In return i am expecting 2 csv output file. when I do list objects. But it returning only uploaded script(file_upload[''edshiftconnector.py']).
	
So, Could you please let me know wheather this functionality is implemented or not. If implemented let me know what could be the issue.

**Comment by bblommers** [comment]
Hi @GovindSkand, this is not supported by Moto. We mock the Glue-methods, but the actual scripts are not executed.

Considering the scope of this feature, I'm also not keen on implementing/supporting it.

If this is something you need, you could consider Localstack? As far as I'm aware, they do have a Glue-emulator that allow you to execute scripts locally.
