### ISSUE TITLE
Is End to End AWS testing possible using moto library?

### ISSUE THREAD

**Issue by Sandeep-Dora** [getmoto/moto#5850]
Hi,

Below is my requirement which I wanted to test end to end using moto

1) Create a Glue job for connecting to DB, Extract & query the data and load the data to a CSV . 
2) Uploading the Glue script in S3
3) Run the Glue script to generate the CSV as mentioned in the step 1
4) Store the above CSV in S3

Can we perform the above testing End to End using Moto ?

Thanks In Advance!

**Comment by bblommers** [comment]
Hi @Sandeep-Dora, welcome to Moto! Our Glue implementation is mock-only. It is possible to store the script in our S3, but we do not actually execute this script when calling Glue - we only return a mocked response.

It may be worth looking into Localstack if you need this functionality. It may be a bit more effort to setup, but their implementation does execute the scripts, as far as I know.
