### ISSUE TITLE
AWS sevices which supports Moto

### ISSUE THREAD

**Issue by GovindSkand** [getmoto/moto#5851]
Hello All,

I am trying to mock AWS services like S3, Glue, and Dynamodb. I simply want to know which services have been fully implemented and how they function in real time. Please let me know. It will be a great thing to further implement.

**Comment by bblommers** [comment]
Hi @GovindSkand, the documentation lists all services that we support, and which methods for that service. See http://docs.getmoto.org/en/latest/docs/services/index.html

Does that answer your question?

**Comment by GovindSkand** [comment]
@bblommers Thanks for your reply. I gone through the S3 documentation and saw put_bucket_policy methods is implemented.But when I apply the deny policy to bucket, it not showing any error. Any reason could be.

![image](https://user-images.githubusercontent.com/122018190/212917013-629d745c-35cf-4004-b525-fc62489f05b1.png)

**Comment by bblommers** [comment]
That is an outstanding issue - see #5820

**Comment by GovindSkand** [comment]
Ok, thanks.

**Comment by bblommers** [comment]
The `put_bucket_policy` now has some basic documentation explaining what is and isn't supported: http://docs.getmoto.org/en/latest/docs/services/s3.html

I'll close but, but let us know if you have any other questions.
