### ISSUE TITLE
Got ```TypeError: 'Mock' object is not subscriptable``` when trying to read client iam response

### ISSUE THREAD

**Issue by Anatoli-deBRADKE** [getmoto/moto#5852]
Hello,

I have some issues when trying to mock the AWS iam client with moto and then create a role: when I try to access to client response (more precisely to the ARN of the ew created role) of the method **create_role** I have the following message error:

```python
import pytest

from moto import mock_iam
import boto3


pytestmark = [pytest.mark.django_db]

@mock_iam
def test_create_role():
    conn = boto3.client("iam", region_name="us-east-1")
    response = conn.create_role(
        RoleName="my-role", AssumeRolePolicyDocument="some policy", Path="/"
    )
    arn = response["Role"]["Arn"]
    assert arn == "MOCKED_ARN"
```
When running code above, the following error message raised: **TypeError: 'Mock' object is not subscriptable** (related to row `arn = response["Role"]["Arn"]`)

Do you have any idea why this behavior occurs? 

Thanks in advance for your help.

Regards

P.S: I'am currently using version moto==3.1.18

**Comment by JianXinyu** [comment]
Hello @Anatoli-deBRADKE , I also met this issue. Could you please tell me how you solved it?
