### ISSUE TITLE
ECS list_services ClusterNotFoundException Not raised

### ISSUE THREAD

**Issue by Bharat23** [getmoto/moto#5857]
## Reporting Bugs

Resource/Client:
**ECS**

Method:
**list_services**

When calling the `ecs` `list_services` with a cluster that does not exist (in moto) the API returns an empty list response.

Expected behavior:
It should raise `ClusterNotFoundException` if cluster_name is invalid.

Moto version: 4.1.0
Python: 3.9

**Comment by bblommers** [comment]
Thanks for raising this @Bharat23 - marking it as an enhancement to implement this validation.

Just as an implementation note: the docs state that `If you do not specify a cluster, the default cluster is assumed.` Which means that the same error may be raised if you do not specify a cluster, and the `default` cluster does not exist.
