### ISSUE TITLE
Docker image support for Apple Silicon?

### ISSUE THREAD

**Issue by lougreenwood** [getmoto/moto#5858]
Not sure if this is the correct repo, I don't see any other repos under this organisation for the docker images.

I tried searching issues for `docker` and also `m1`, but didn't see any obvious results for previous threads on this topic.

---

It seems that the docker image for `Moto` doesn't support Apple Silicon (e.g `linux/arm64/v8`). Is this a known issue, is it planned to publish images built for Apple Silicon?

https://hub.docker.com/r/motoserver/moto/tags 

Thanks!

**Comment by bblommers** [comment]
Hi @lougreenwood, our  main releases do support `linux/arm64` - as far as I know that is functionally equivalent to `linux/arm64/v8`. Are you into running with those releases? Or are you specifically asking for `linux/arm64` support for the `latest` tag?

**Comment by lougreenwood** [comment]
Thanks @bblommers 

We're using `motoserver/moto:latest`, but on an M1 Pro I get the following error:

```
[+] Running 0/1
 ⠏ moto Pulling                                                                                                                                                               1.8s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Also, I notice that `latest` tag only has the `linux/amd64` arch, whereas the other images have `linux/arm64` as well...

So I just tested it using `image: motoserver/moto:4.1.0` and it builds, so seems the issue is only with latest and is unfortunate timing on my part to find this issue! 😓.

So, I guess `latest` just needs tagging for arm as well?

**Comment by bblommers** [comment]
Gotcha - thanks for the explanation. #5553 brought support `linux/arm64` support for normal releases, so we'll just need to apply the same fix when releasing `latest`.
