### ISSUE TITLE
Differences in cloudfront between 4.0.11 and 4.0.12+

### ISSUE THREAD

**Issue by pll** [getmoto/moto#5868]
Hi all,

I've got 4 unit tests in my code which leverage the @mock_cloudfront decorator.  They work just fine under 4.0.11, but fail under 4.0.12+

As best I can tell, moto isn't intercepting calls to Cloudfront, but I can't figure out why. 

The call that fails is `cloudfront.update_dstribution()`. The diff between 4.0.11 & 4.0.12 seems benign enough:

```
$ git diff 4.0.11 4.0.12 -- models.py
diff --git a/moto/cloudfront/models.py b/moto/cloudfront/models.py
index 737b7d3d..52903a13 100644
--- a/moto/cloudfront/models.py
+++ b/moto/cloudfront/models.py
@@ -113,6 +113,7 @@ class Origin:
     def __init__(self, origin: Dict[str, Any]):
         self.id = origin["Id"]
         self.domain_name = origin["DomainName"]
+        self.origin_path = origin.get("OriginPath") or ""
         self.custom_headers: List[Any] = []
         self.s3_access_identity = ""
         self.custom_origin = None
@@ -329,8 +330,14 @@ class CloudFrontBackend(BaseBackend):
         dist = self.distributions[_id]

         aliases = dist_config["Aliases"]["Items"]["CNAME"]
+        origin = dist_config["Origins"]["Items"]["Origin"]
         dist.distribution_config.config = dist_config
         dist.distribution_config.aliases = aliases
+        dist.distribution_config.origins = (
+            [Origin(o) for o in origin]
+            if isinstance(origin, list)
+            else [Origin(origin)]
+        )
         self.distributions[_id] = dist
         dist.advance()
         return dist, dist.location, dist.etag
```

But, there is some added code there regarding Origins, which might be my issue, since the error I'm getting back from botocore is:

```
botocore.errorfactory.InvalidOrigin: An error occurred (InvalidOrigin) when calling the UpdateDistribution operation: The specified origin server does not exist or is not valid.
```

Since things work with 4.0.11< but not with 4.0.12+, I'm guessing I need to fix my code. But I'm not sure how.

Any help would be appreciated. Thanks!

--
Paul

**Comment by pll** [comment]
Looking into this more, I'm very confused about line 333 in moto/cloudfront/models.py:

```
        aliases = dist_config["Aliases"]["Items"]["CNAME"]
        origin = dist_config["Origins"]["Items"]["Origin"]     <---
```

That line was added in 4.0.12. And looking at the boto3 docs, I don't actually see an "Origin" key to the ["Origins"]["Items"] dict:

```
response = client.update_distribution(
    DistributionConfig={
        'CallerReference': 'string',
        'Aliases': {
            'Quantity': 123,
            'Items': [
                'string',
            ]
        },
        'DefaultRootObject': 'string',
        'Origins': {
            'Quantity': 123,
            'Items': [
                {
                    'Id': 'string',
                    'DomainName': 'string',
                    'OriginPath': 'string',
                    'CustomHeaders': {
                        'Quantity': 123,
                        'Items': [
                            {
                                'HeaderName': 'string',
                                'HeaderValue': 'string'
                            },
                        ]
                    },
                    'S3OriginConfig': {
                        'OriginAccessIdentity': 'string'
                    },
                    'CustomOriginConfig': {
                        'HTTPPort': 123,
                        'HTTPSPort': 123,
                        'OriginProtocolPolicy': 'http-only'|'match-viewer'|'https-only',
                        'OriginSslProtocols': {
                            'Quantity': 123,
                            'Items': [
                                'SSLv3'|'TLSv1'|'TLSv1.1'|'TLSv1.2',
                            ]
                        },
                        'OriginReadTimeout': 123,
                        'OriginKeepaliveTimeout': 123
                    },
                    'ConnectionAttempts': 123,
                    'ConnectionTimeout': 123,
                    'OriginShield': {
                        'Enabled': True|False,
                        'OriginShieldRegion': 'string'
                    },
                    'OriginAccessControlId': 'string'
                },
            ]
        },
...
```

I could be misunderstanding what's going on there, but both lines 332 & 333 seem to be attempting to copy dicts at locations which are lists according to the docs on Distribution Configs. (not saying this is the cause of my problems, just that I'm confused about what's going on in these lines!)

Thanks.
--
Paul

**Comment by bblommers** [comment]
Hi @pll!

`dist_config["Origins"]["Items"]["Origin"]` points to this object:
```
{
   'Id': 'string',
   'DomainName': 'string',
   'OriginPath': 'string',
    ....
```
So the `origin` variable refers to either one dict containing those values, or a list containing multiple dicts.

--------------

The `InvalidOrigin` error is thrown if the `origin`-dict does not have the `S3OriginConfig` or the `CustomOriginConfig`-field. If I read the docs correctly, either one of those fields is required in the CreateDistribution-action.

In addition, the UpdateDistribution states that:
```
The new configuration replaces the existing configuration. The values that you specify in an UpdateDistribution request are not merged into your existing configuration. Make sure to include all fields: the ones that you modified and also the ones that you didn't.
```
Which indicates that the `S3OriginConfig` or `CustomOriginConfig`-field also has to be part of the UpdateDistribution call.

**Comment by pll** [comment]
Hi Bert,

Thanks for the reply. I guess I missed that part about `S3OriginConfig` or `CustomOriginConfig` being required.

I create my mock CF distro with the following:

```
            "Items": [
                {
                    "Id": Id,
                    "DomainName": "asdf.s3.us-east-1.amazonaws.com",
                    "S3OriginConfig": {"OriginAccessIdentity": ""},
                }
            ],
```
However, when I call `get_distribution(Id=self.dist_id)` the structure I get back is:

```
[
    {
        "Id": "foo-a",
        "DomainName": "asdf.s3.us-east-1.amazonaws.com",
        "OriginPath": "",
        "CustomHeaders": {
            "Quantity": 0,
            "Items": []
        },
        "ConnectionAttempts": 3,
        "ConnectionTimeout": 10,
        "OriginShield": {
            "Enabled": false
        }
    }
]
```

So, I *think* I'm creating the distro correctly, but the dist-config I get back isn't what I created.  When updating the config, I'm creating a copy, then simply updating one of the fields (`Aliases`), but because what I get back from `get_distribtion()` is lacking the `S3OriginConfig` and/or `CustomOriginConfig`, I guess that's why I'm getting the error.

Any ideas on why the dist config I create isn't what I'm getting back?

Thanks again!
--
Paul

**Comment by pll** [comment]
DOH!  @bblommers - I'm an idiot!

```
    "S3OriginConfig": {"OriginAccessIdentity": ""},
```

Effectively makes that null, which means it no longer exists in the config. Making that a non-empty string fixes everything :)

Sorry for the bother, but thanks for being a sounding board! I'm happily running 4.1.0 now!

Paul

**Comment by bblommers** [comment]
> I'm happily running 4.1.0 now!
>

Happy to hear that! I'll close this, but us know if you run into any other issues.
