### ISSUE TITLE
EKS DescribeNodegroup not returning id or name launch template attribute in response

### ISSUE THREAD

**Issue by andypaterson40** [getmoto/moto#5879]
The boto3 EKS DescribeNodegroup response returns the following for LaunchTemplate:
`'launchTemplate': {
            'name': 'string',
            'version': 'string',
            'id': 'string'
        },`

However, the moto response for same API call only returns either name or id - depending which you specify when creating a node group using boto3 EKS API. 

I've tested this out using boto3 API against endpoints on my own AWS account and when i do a describe_nodegroup API call it returns both launcTemplate.id and launchTemplate.name in the response. But moto only returns one or the other depending which one you specify in the create_nodegroup. I know you only specify one of id or name but when you call the describe_nodegroup - it should return both attributes in the response.
This is currently breaking for our specific test.

**Comment by bblommers** [comment]
Thanks for raising this @andypaterson40 - looks like we're not doing anything with the `launchTemplate` at the moment, we just store it as is. Will mark it as an enhancement to actually verify it exists and retrieve the corresponding name/id.
