### ISSUE TITLE
ThreadPoolExecutor and IAM

### ISSUE THREAD

**Issue by mikegrima** [getmoto/moto#5881]
Hello Again!

I found an interesting issue when using a `ThreadPoolExecutor` and I wanted to document it here because it can be useful for others who encounter this.

Moto is not known to be thread safe, however, there are a number of tests that you can run safely with threads. I recently encountered the following when using code like this:

```python
def some_tasking_func(*args) -> Any:
    """do some boto thing here"""
    boto3.client("...")
    ...
    return ...

def some_func(loop: AbstractEventLoop, things_to_do: List) -> None:
    with ThreadPoolExecutor(max_workers=10) as executor:
        tasks = []

        for thing in things_to_do:
            tasks.append(loop.run_in_executor(executor, some_tasking_func, thing))

        try:
            await asyncio.gather(*tasks)
        except Exception as err:
            print("EXCEPTION ENCOUNTERED!!")
            print(err)
            raise     
```

You would get this stacktrace:
```
  File "/.../python3.10/site-packages/moto/iam/models.py", line 73, in get_account_id_from
    for account_id, account in iam_backends.items():
RuntimeError: dictionary changed size during iteration
Future exception was never retrieved
future: <Future finished exception=RuntimeError('dictionary changed size during iteration')>
```

Looking at the `get_account_id_from` function in `moto/iam/models.py`, I see that it's doing some iteration that would cause issues in threads. However, for the test that I am running, I don't really care about the account ID. So, I was able to solve this problem by doing the following in a pytest fixture:

```python
def mock_moto_accounts() -> Generator[None, None, None]:
    with mock.patch("moto.iam.models.get_account_id_from", lambda x: "123456789012"):
        yield

...
def test_some_func(mock_moto_accounts: None) -> None:
    loop = asyncio.new_event_loop()
    things_to_do = [1, 2, 3]
    try:
        loop.run_until_complete(some_func(loop, things_to_do))
    finally:
        loop.close()
```

^^ Using this fixture in my tests solved my issue. I don't think that we need to make any changes to moto, but I would like to have this documented as a workaround for the community just in case they need to do things with Threads and don't actually care about unique account IDs being returned in any of their tests.

I would be happy to add this to the docs, or just even leave this here as a GitHub issue so it can be searched for by someone later. Just let me know!

Thank You

**Comment by bblommers** [comment]
Hey @mikegrima - thanks for raising this!

Just because something is in the documentation, doesn't mean people actually know about it. I wouldn't mind actually to have a fix for this in Moto. It wouldn't make us completely thread-safe, but improving our ability to deal with concurrent requests is always good.

The easiest fix would probably be to copy the dictionary before iterating over it:
`for account_id, account in iam_backends.copy().items()`
but that is definitely not the most performant way. I'll have a think on what's the best way of doing this. PR's are always welcome, if you have a better idea and want to tackle this!

**Comment by mikegrima** [comment]
Instead of a copy, I just made it a list like so:

```python
for account_id, account in list(iam_backends.items()):
```

This would be much more performant and it did resolve the need for the mock above. I'm happy to PR this.

**Comment by mikegrima** [comment]
This might be a red herring... There is likely something else that's odd about my code. I'll report back later.

**Comment by mikegrima** [comment]
Ok so I did confirm that wrapping in a `list` worked. What's strange is, I only see this error message if I run pytest with the xdist plugin for multi-processed tests. So a threadpool being run with multiprocessing causes the error without being wrapped or mocked out 🙃 .

I'm happy to submit a PR to fix that.
