### ISSUE TITLE
lambci/lambda docker images are deprecated

### ISSUE THREAD

**Issue by wasserholz** [getmoto/moto#5886]
lambci/lambda docker images are deprecated and only support nodejs images until version 12. https://github.com/lambci/docker-lambda

Those base images should be replaced with aws lambda base image. https://github.com/aws/aws-lambda-base-images

**Comment by bblommers** [comment]
Hi @wasserholz! It is possible to configure the Docker-image used by our Lambda mock. [Our documentation](http://docs.getmoto.org/en/latest/docs/services/lambda.html) suggests to use the mLupin-images, as they do have more up-to-date (NodeJS) versions:
```MOTO_DOCKER_LAMBDA_IMAGE=mLupin/docker-lambda```

Does that solve your problem?

**Comment by wasserholz** [comment]
Thanks for the quick reply. That indeed solves the node version issue.
Do you think it would make sense to move completely away from lambci/lambda docker images as they are deprecated?

**Comment by bblommers** [comment]
It does make sense to make `mLupin` the default. 

People will still use older versions of AWSLambda though, so we still need to keep `lambci` around. For example, it's no longer possible to create Python2.7 Lambdas in AWS, but existing functions continue to work - so Moto also has to continue to support them as well.

Originally I planned to make the move to `mLupin` a breaking change, and therefore it would have to be part of a major version release. But maybe we can simply check both in our backend - first try if the existing image exists in `mLupin`, and fallback to `lambci` if that doesn't work.

**Comment by wasserholz** [comment]
I just noticed `MOTO_DOCKER_LAMBDA_IMAGE=mLupin/docker-lambda` will through an error.

```error running docker: 400 Client Error for http+docker://localhost/v1.41/images/create?tag=nodejs14.x&fromImage=docker.io%2FmLupin%2Fdocker-lambda: Bad Request ("invalid reference format: repository name must be lowercase")```

The value must be lower case, then it works: `MOTO_DOCKER_LAMBDA_IMAGE=mlupin/docker-lambda`

**Comment by bblommers** [comment]
As of moto >= 4.1.2.dev21, we should now try both `mlupin` and `lambci` as possible sources for Docker images.
The `MOTO_DOCKER_LAMBDA_IMAGE` is still in place, in case we want to add a third possible source.

Please let us know if you still run into any issues @wasserholz!

**Comment by wasserholz** [comment]
Thanks @bblommers for the quick action. I will check issues, when the new motoserver/moto docker image is out.

**Comment by bblommers** [comment]
The `latest` tag will already contains this fix! I'll try and make a full release this weekend
