### ISSUE TITLE
Mock assume role between accounts not working

### ISSUE THREAD

**Issue by pelegn** [getmoto/moto#5894]
## Reporting Bugs
Hi,
I am trying to mock account changes and creation of resources on several accounts.
I'm trying to do this with sts assume role, but the account always remains the original 123456789012 account

sample test:
```
  @moto.mock_sts
  @moto.mock_rds
  def test_multi_account():
  
      sts_client = boto3.client("sts")
      current_caller_id = sts_client.get_caller_identity()
      print(json.dumps(current_caller_id, indent=2))
      response = sts_client.assume_role(RoleArn='arn:aws:iam::444444444444:role/my_role', RoleSessionName='test')
      sts_client = boto3.client("sts",
                                aws_access_key_id=response["Credentials"]["AccessKeyId"],
                                aws_secret_access_key=response["Credentials"]["SecretAccessKey"],
                                aws_session_token=response["Credentials"]["SessionToken"],
                                region_name="us-east-1"
                                )
      current_caller_id = sts_client.get_caller_identity()
      print(json.dumps(current_caller_id, indent=2))
  
      rds_client = boto3.client("rds",
                                aws_access_key_id=response["Credentials"]["AccessKeyId"],
                                aws_secret_access_key=response["Credentials"]["SecretAccessKey"],
                                aws_session_token=response["Credentials"]["SessionToken"],
                                region_name="us-east-1")
      rds_client.create_db_instance(
          DBInstanceIdentifier="test-rds-instance",
          DBInstanceClass="db.t2.micro",
          Engine="mysql",
      )
  
      print(f"db_arn={rds_client.describe_db_instances()['DBInstances'][0]['DBInstanceArn']}")
```
Summerizing the printed logs:
First print:
"Arn": "arn:aws:sts::123456789012:user/moto", - which is expected

Second print: 
"Arn": "arn:aws:sts::123456789012:assumed-role/my_role/test"
Expected : "Arn": "arn:aws:sts::444444444444:assumed-role/my_role/test"

Third print:
db_arn=arn:aws:rds:us-east-1:123456789012:db:test-rds-instance
Expected : db_arn=arn:aws:rds:us-east-1:444444444444:db:test-rds-instance

Using:
Moto version "3.1.18"
Python 3.9.16

Thank you in advance

**Comment by bblommers** [comment]
Hi @pelegn, multi-account support was only introduced as of Moto 4: see https://github.com/getmoto/moto/blob/master/CHANGELOG.md#400

Does upgrading solve your problem?

**Comment by pelegn** [comment]
Yes it worked. missed the fact that it was introduced in moto4.
Thank you
