### ISSUE TITLE
[IAM] Adding user the same IAM group twice causes the group to become "sticky"

### ISSUE THREAD

**Issue by demosito** [getmoto/moto#5897]
Hi team.
Discovered an interesting behavior of mock_s3: if I add an IAM user to an IAM group and then remove the user from the group, everything works as expected, i.e. as a result the user is not a member of any group. However, if I add the user to the same group **twice** and then remove the user them from the group, the group membership is still retained. So it looks like adding a user to a group is not idempotent operation.

```python
from moto import mock_iam
import boto3


@mock_iam
def test_moto():
    iam = boto3.client("iam")

    def get_iam_user_groups(user_name: str) -> "list[str]":
        """List names of groups the given IAM user is member of"""
        paginator = iam.get_paginator("list_groups_for_user")
        return [
            group["GroupName"]
            for page in paginator.paginate(UserName=user_name)
            for group in page["Groups"]
        ]

    iam.create_group(Path="test", GroupName="test1")
    iam.create_user(UserName="test")

    iam.add_user_to_group(GroupName="test1", UserName="test")
    # the test works without this line and breaks with it whilst it should not affect
    iam.add_user_to_group(GroupName="test1", UserName="test")

    iam.remove_user_from_group(GroupName="test1", UserName="test")
    assert get_iam_user_groups("test") == []
```

Running this test case with pytest causes it to fail on the last line with the following error:
```
>       assert get_iam_user_groups("test") == []
E       AssertionError: assert ['test1'] == []
E         Left contains one more item: 'test1'
E         Use -v to get the full diff

mtest.py:26: AssertionError
```

If I uncomment the third line from the bottom (`iam.add_user_to_group(GroupName="test1", UserName="test")`) which is duplicate of the one above it, the test passes.

```
$ pip list | grep [bm]oto
aiobotocore                  2.3.4
boto3                        1.20.34
botocore                     1.23.34
moto                         4.1.1
$ python --version
Python 3.8.14
```

Ran pytest as `pytest -s  mtest.py`. Installed moto with `pip install moto[iam]`.

**Comment by bblommers** [comment]
Thanks for raising this @demosito! Looks like we're indeed always appending users to a group, and we don't check for duplicates. Marking it as a bug.

https://github.com/getmoto/moto/blob/c1d85a005d4a258dba98a98f875301d1a6da2d83/moto/iam/models.py#L2473

**Comment by demosito** [comment]
Fantastic! Thank you for the lightning-fast response!
