### ISSUE TITLE
create_function() return wrong "LastModified" date format

### ISSUE THREAD

**Issue by shanishiri** [getmoto/moto#5914]
create_function method is creating instance of "LambdaFunction" class, which initialize last_modified with different datetime string format then the [official boto3 docs define  ](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.create_function)

moto:
self.last_modified = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

where the datetime format should be "%Y-%m-%dT%H:%M:%S.%f+0000"

```
@mock_lambda
def test_create_function():
  func = client.create_function(
          FunctionName="1",
          Runtime="nodejs12.x",
          Role=role_arn,
          Code={"ZipFile": b""},
          Handler="original_handler",
          Environment={"Variables": {"aa": "bb"}},
          Layers=[layer]
      )
```

for func['LastModified'] expected value is: `"2023-02-09T11:02:38.281+0000"`

actual value: `"2023-02-09 11:02:38"`

using moto==4.1.2

**Comment by bblommers** [comment]
Thanks for raising this @shanishiri - marking it as a bug!

Do you want to raise a PR for this yourself?
