### ISSUE TITLE
Add Neptune 

### ISSUE THREAD

**Issue by kurtqq** [getmoto/moto#5929]
Please add Neptune so we can easily test against it.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/neptune.html

specifically:
create_db_instance
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/neptune.html#Neptune.Client.create_db_instance

start_db_cluster
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/neptune.html#Neptune.Client.start_db_cluster

**Comment by bblommers** [comment]
Hi @kurtqq, welcome to Moto! Marking it as an enhancement to add this functionality.

**Comment by bblommers** [comment]
Hi @kurtqq, this should now be part of moto >= 4.1.4.dev23. Please let us know if you run into any issues.
