### ISSUE TITLE
Incorect response when calling glue.get_table_versions

### ISSUE THREAD

**Issue by nicor88** [getmoto/moto#5933]
## Reporting Bugs

The current implementation of glue.get_table_versions, see [here](https://github.com/getmoto/moto/blob/78840fd71c365bb40214f59a9d7c5f5f3d00b850/moto/glue/responses.py#L73-L85)

it's different from the actual response from boto3. Specifically `VersionId` it's a key of Table, and not a separate Key.
Also UpdateTime seems missing...
A possibility is to do something like that:

```python
return json.dumps(
      {
          "TableVersions": [
            {"Table": {**table.as_dict(version=n), **{"VersionId": str(n + 1), "UpdateTime": ....random time}}
             for n in range(len(table.versions))
                ]
            }
        )
```

**Comment by bblommers** [comment]
Hey @nicor88, thanks for raising this. The `VersionId` should actually be returned twice, according to the AWS docs: once as part of the key of Table, and one separate. :confused: 

Marking it as a bug.

**Comment by nicor88** [comment]
@bblommers ah I see, as mentioned above also UpdateTime seems missing.

**Comment by nicor88** [comment]
@bblommers thanks for fixing so fast, when do you plan to release the changes?

**Comment by bblommers** [comment]
Happy to help @nicor88. I'll try and cut a release this weekend.

**Comment by bblommers** [comment]
Moto 4.1.3 is now available @nicor88

**Comment by nicor88** [comment]
@bblommers many thanks!
