### ISSUE TITLE
Add OpenSearch

### ISSUE THREAD

**Issue by kurtqq** [getmoto/moto#5962]
coverage for `create_domain`

https://boto3.amazonaws.com/v1/documentation/api/1.18.51/reference/services/opensearch.html#OpenSearchService.Client.create_domain

**Comment by bblommers** [comment]
Marking it as an enhancement @kurtqq. Is it just the one method that you're interested in?

**Comment by kurtqq** [comment]
for now yes

**Comment by bblommers** [comment]
Hi @kurtqq, this is now part of Moto 4.1.6. See the list of supported methods here: http://docs.getmoto.org/en/latest/docs/services/opensearch.html

Note that I wasn't able to verify the correct default values when creating a domain - please let me know if you run into any issues with this.
