### ISSUE TITLE
Feature request: Please add support for the AWS lake formation modules

### ISSUE THREAD

**Issue by SuchiDuvvuri** [getmoto/moto#5964]
I looked at the moto library for lakeformation modules and did not find any. Can you please this, so our tests can mock AWS lakeformation?

**Comment by bblommers** [comment]
Hi @SuchiDuvvuri, I'll mark it as an enhancement to add this service.  

Which methods/features do you use specifically?

**Comment by SuchiDuvvuri** [comment]
@bblommers - specifically the batch_grant_permissions, grant_permissions, batch_revoke_permissions, revoke_permissions, list_lf_tags, list_resources, list_data_cells_filter

**Comment by bblommers** [comment]
These methods are now all part of moto >= 4.1.7.dev30 @SuchiDuvvuri  - see the documentation here: http://docs.getmoto.org/en/latest/docs/services/lakeformation.html

Please let us know if you run into any issues.
