### ISSUE TITLE
Feat: Provide a Faker Provider interface / Open up make_random_id

### ISSUE THREAD

**Issue by hans-d** [getmoto/moto#5987]
For various unit testing it's beneficial to generate some mock ids (and/or arns). There is already a lot of `make_random_<name>_id` in the code that can be re-used for this.

By providing a Faker Provider (https://faker.readthedocs.io/en/master/), that code can be re-used.

I would like to know if this has some change of being incorporated if I bring a PR for that (before I start the work).

**Comment by bblommers** [comment]
Hi @hans-d! You can seed Moto, that way all ID's/ARN's should be deterministic. See the documentation here:
http://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html#deterministic-identifiers

Note that the docs are talking about using this in the context of the Recorder-feature, but seeding can be done on it's own.

Does that work for your usecase?

**Comment by hans-d** [comment]
It's more about using those ID in other code (not the moto code), that want to use "an" account id, and not needing to setup a full moto for that part of the testing.

**Comment by hans-d** [comment]
Getting something like this in moto:
```
from moto.organizations.utils import (
    make_random_account_id,
    make_random_org_id,
    ORGANIZATION_ARN_FORMAT,
)

from faker.providers import BaseProvider


class AwsProvider(BaseProvider):
    def aws_account_id(self) -> str:
        return self.aws_organizations_account_id()

    def aws_organizations_organization_arn(self) -> str:
        master_account_id = self.aws_organizations_account_id()
        organization_id = self.aws_organizations_organization_id()

        return ORGANIZATION_ARN_FORMAT.format(master_account_id, organization_id)

    def aws_organizations_account_id(self) -> str:
        return make_random_account_id()

    def aws_organizations_organization_id(self) -> str:
        return make_random_org_id()

```
and can used somewhere else like:
```
def test_something(self, _faker: Faker):
        data = call_my_real_fn(account=_faker.aws_account_id())
        
        assert len(data)==1
```

**Comment by bblommers** [comment]
Gotcha, I understand. 

I would not want that to be part of Moto though, I understand the usefulness, but I don't think it's used by enough people to offset the maintenance cost.

**Comment by hans-d** [comment]
Just what I wanted to check. Will make something separately, building on top of moto.
