### ISSUE TITLE
Allow FIFO SQS queues as event source for Lambda invocations

### ISSUE THREAD

**Issue by shamelin** [getmoto/moto#5992]
Hi! :)

I'm having some issues with the SQS module of the moto library. I created a Lambda function that would be invoked when a message is inserted into a FIFO SQS queue. It is supported by [AWS since 2019](https://aws.amazon.com/blogs/compute/new-for-aws-lambda-sqs-fifo-as-an-event-source/) but it doesn't seem to be supported by moto yet.

I've looked at the code and [it seems to be a simple condition](https://github.com/getmoto/moto/blob/master/moto/awslambda/models.py#L1648) that prevents the correct behavior. Removing the `if` condition and making the `else` content execute by default should resolve the issue in my opinion. I managed to test it locally and it successfully invoked the Lambda function.

I am using the latest version of moto (v4.1.3) as well as the latest version of boto3 (v1.26.78).

Below is an example of the correct behavior.

## Base code

```python
SQS_QUEUE_NAME = "example.fifo"

sqs_client = boto3.client("sqs", region_name=REGION)
lambda_client = boto3.client("lambda", region_name=REGION)

queue = self.client_sqs.create_queue(QueueName=SQS_QUEUE_NAME,
                                     Attributes={"FifoQueue": "true"})

# We'll try to get the ARN of the queue
SINK_QUEUE_ARN = self.client_sqs.get_queue_attributes(
    QueueUrl=queue.get("QueueUrl"),
    AttributeNames=["QueueArn"]
).get("Attributes").get("QueueArn")

# lambda role creation ...

lambda_client.create_function(
    FunctionName=LAMBDA_FUNCTION_NAME,
    Runtime="python3.9",
    Role=ROLE_ARN,
    Handler="lambda_handler.lambda_handler",
    Code={
        # ...
    },
    Timeout=300,
    MemorySize=128,
    Publish=True
)

# we subscribe lambda to the SQS queue
lambda_client.create_event_source_mapping( # <-- will throw an error
    EventSourceArn=SINK_QUEUE_ARN,
    FunctionName=LAMBDA_FUNCTION_NAME,
    StartingPosition="LATEST",
    BatchSize=10,
    Enabled=True
)

```

## What we expect
The FIFO SQS queue should be successfully mapped to the Lambda function. When a message is sent to it, the Lambda should be invoked.

## What we get
```
E botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: <?xml version="1.0" encoding="UTF-8"?>
E <ErrorResponse>
E   <Errors>
E     <Error>
E       <Code>InvalidParameterValueException</Code>
E         <Message><![CDATA[arn:aws:sqs:us-east-1:123456789012:example.fifo is FIFO]]></Message>
E     </Error>
E   </Errors>
E   <RequestId>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestId>
E </ErrorResponse>
```

**Comment by bblommers** [comment]
Hi @shamelin, thanks for raising this! That looks like the correct fix to me - I'll mark it as an enhancement to add proper support for this.

**Comment by shamelin** [comment]
Thank you so much! :) Cheers!
