### ISSUE TITLE
[DynamoDb] All Errors are deserialized as DynamoDbException in JAVA SDK

### ISSUE THREAD

**Issue by munendrasn** [getmoto/moto#5993]
Using MotoServer to test Java based services. This Service creates the DynamoDb table if it doesn't exist, ie, on ResourceNotFoundException, table is created.
When using the MotoServer, We get response

```json
{"__type": "com.amazonaws.dynamodb.v20111205#ResourceNotFoundException", "message": "Requested resource not found"}
```
When this is deserialized in java sdk, as there is no error-code for  `com.amazonaws.dynamodb.v20111205#ResourceNotFoundException` hence, All the error is wrapped, and returned as `DynamoDbException`

With other services, similar issue is not occurring. The issue exists for version>=3.1.5, and seems to be introduced by this https://github.com/getmoto/moto/pull/5012
Tried using <=3.1.4 to overcome this problem, but ended up encountering another bug related to Glue, which is fixed in the recent version. So, unable to use the older versions as a workaround

Could you please share reason behind the error message? would it be possible to have error message compatible with Java SDKs too?

**Comment by bblommers** [comment]
Thanks for raising this @munendrasn - marking it as a bug.

#5012 was an attempt to streamline all error messages - but because we only fully test against the Python SDK, which is more forgiving, we never realized it was broken. Will raise a PR shortly.

**Comment by munendrasn** [comment]
@bblommers 
Thanks for the quick fix. 

I did a quick test with `4.1.4.dev29` but encountering the same issue with Java SDK (2.17.257), ie, even though the error message proper, `Requested resource not found: Table: e9f18915466b4516adf373ae754a19ed not found` but error/exception of type DynamoDbException instead of ResourceNotFoundException

I think having the error prefix is causing the issue. Based on the description from the PR https://github.com/getmoto/moto/pull/5997#issue-1601974124, it seems prefix is required for python sdk. Is this the correct understanding?

**Comment by bblommers** [comment]
@munendrasn I actually tested this against AWS, and this format is exactly what AWS returns. So I assumed the Java SDK would be OK with it.
I'll have another look.

**Comment by bblommers** [comment]
Can you try this again with moto >= 4.1.4.dev36 @munendrasn? 

We now also have some Java tests as part of our build pipeline, so if you do come across a scenario that still fails, feel free to provide some sample Java code - we can make that part of our tests as well.

**Comment by munendrasn** [comment]
@bblommers 
I did one round of testing with 4.1.4.dev36, working as expected. Thanks for the fix.

While testing encountered another issue with Glue. CreateTable is working as expected. GetTable post successful UpdateTable still returns the older version. This issue is not specific to Java SDK

Based on the initial analysis, this issue doesn't exist in released, and seems to be related PR https://github.com/getmoto/moto/pull/5968, I think when converting table to dict https://github.com/getmoto/moto/blob/0e24b281eb12825706fd9088e8b4cd4e295af443/moto/glue/responses.py#L63, we might need to use the current version, or update the `get_table` behavior to use current_version if version is not passed as arg to `as_dict()`
Same issue might be occurring for `getTables` based on initial look, but this is not tested

Kindly, let me know if additional analysis, or test is required

**Comment by bblommers** [comment]
This didn't work quite right in 4.1.3, as far as I could tell - the version would be set to 0 if multiple versions existed. 
`get_table()` now returns the correct version + data. Thanks for raising this @munendrasn.
