### ISSUE TITLE
Add ResourceGroupsTaggingAPI Support for Aurora clusters

### ISSUE THREAD

**Issue by ppapishe** [getmoto/moto#5994]
Currently moto seems to not support rds:cluster and only supports rds:db . This issues is to ask to add support to fetch the rds aurora clusters using ResourceGroupsTaggingAPI

**Comment by bblommers** [comment]
Marking it as an enhancement @ppapishe. Thanks for raising this, and welcome to Moto!

**Comment by ppapishe** [comment]
> Marking it as an enhancement @ppapishe. Thanks for raising this, and welcome to Moto!

Wow, you are fast. Thank you so much. Now I know how to contribute if I need something else.

**Comment by bblommers** [comment]
All thanks to @bpandola for the quick fix!

**Comment by ppapishe** [comment]
Hey @bblommers and @bpandola , are you going to release a new version?
I see the latest tag is created last week.

**Comment by bblommers** [comment]
I'll try to get a release in this weekend @ppapishe

**Comment by ppapishe** [comment]
> I'll try to get a release in this weekend @ppapishe

Thank you so much

**Comment by bblommers** [comment]
@ppapishe Moto 4.1.4 is now available :+1:
