### ISSUE TITLE
Multiple AllowedOrigins domains for S3 resources result in invalid Access-Control-Allow-Origin from moto

### ISSUE THREAD

**Issue by kleinsch** [getmoto/moto#6003]
1. Start moto
2. Create a bucket
3. Add CORS config to that bucket with multiple AllowedOrigins `["http://localhost:5000", "http://localhost:6000"]`
4. Hit the bucket through a CORS request from `http://localhost:5000`

Expected: moto returns `Access-Control-Allow-Origin: http://localhost:5000`, everything works

Actual: moto returns `Access-Control-Allow-Origin: http://localhost:5000, http://localhost:6000`, browser rejects it bc that header can only have one value. Can't access the bucket.

If there are multiple values, the server is expected to match the one sent from the client and only return that one.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by bblommers** [comment]
Thanks for raising this @kleinsch, and welcome to Moto! Marking it as an bug.
