### ISSUE TITLE
get_list_from_ddb_typed_value crashes on missing value

### ISSUE THREAD

**Issue by ikonst** [getmoto/moto#6010]
Given update expression `SET #0 = list_append (#0, :0)`, if `#0` refers to a non-existent list, then `get_list_from_ddb_typed_value` crashes on
```python
assert isinstance(node, DDBTypedValue)
```
(since `node` is a `NoneExistingPath` at that point)

**Comment by bblommers** [comment]
Thanks for raising this @ikonst - marking it as a bug.
