### ISSUE TITLE
Feat: Cloudformation Stack (as cludformation resource)

### ISSUE THREAD

**Issue by hans-d** [getmoto/moto#6020]
Stacks are already supported via `mock_cloudformation`
```
boto_cloudformation_client.create_stack(StackName=stack_name, TemplateBody=str(template_dict))
```

Would be good to be able to use cloudformation as well to create new stacks.
Example resource template (fragment):
```
  "fooNestedStackResourceE0751832": {
   "Type": "AWS::CloudFormation::Stack",
   "Properties": {
    "TemplateURL": {
     "Fn::Join": ["", [ "https://s3.testing.", { "Ref": "AWS::URLSuffix" }, "/cdk-hnb659fds-assets-12345678910-testing/long-hash.json" ]]
    }
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
  },
  ```
Some likeness with awslamba, as regards to loading the data from an s3 bucket. That file is a json, containing its own resource template.

Relates to #6018, as there reference there is pointing to such an included stack (not part of the included fragment).

My understanding of the moto internals are yet not good enough to provide an initial version for this.

**Comment by bblommers** [comment]
Marking it as an enhancement to support this!
