### ISSUE TITLE
How to invoke Rest API in moto api gateway?

### ISSUE THREAD

**Issue by rajendersaini** [getmoto/moto#6030]
I could not find out how to invoke rest apis in api gateway as documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html)  in moto 

Is this implemented? if not is there any plans to implement it?

**Comment by bblommers** [comment]
Hi @rajendersaini, are you using the decorators? If so, you can just make a HTTP request to the usual endpoint, and Moto should intercept it. See the documentation here: http://docs.getmoto.org/en/latest/docs/services/apigateway.html

Note that there are quite a few limitations on what is supported for now, but we can always extend this of course.

**Comment by rajendersaini** [comment]
Thanks for quick response. @bblommers I will look into the docs.

**Comment by bressanmarcos** [comment]
Is it possible to invoke the execute-api when using moto server in docker container?
