### ISSUE TITLE
Some tests picking up available AWS env var credentials

### ISSUE THREAD

**Issue by hans-d** [getmoto/moto#6031]
Noticed for this one:
https://github.com/getmoto/moto/blob/dbb866a8c76a8b528742de40a9f11824db600876/tests/test_utilities/test_threaded_server.py#L28-L28

although the endpoint is faked, I see the aws cli trying to use existing AWS env credentials (which are wrong/expired/..). This causes the test to fail.

Expected: no usage of any pre-configured AWS env settings. These should be mocked out.

**Comment by hans-d** [comment]
In my case, I have SSO based credentials. Which may cause some additional work on the cli client before contacting the server.

**Comment by bblommers** [comment]
Ah, gotcha. OK, in that case we should have hardcoded credentials everywhere to avoid this.
