### ISSUE TITLE
Error creating secret with moto_server

### ISSUE THREAD

**Issue by kevinvalleau** [getmoto/moto#6034]
Hello, 

I'm using moto_server with command : `moto_server -p4566`.

When I try to create a simple aws secrets with Terraform, I get the following error, with no trace in moto :

```
│ Error: reading Secrets Manager Secret (arn:aws:secretsmanager:<region>:123456789012:secret:test-tls-20230308133703611100000001-RDLGSh) policy: parsing policy: unexpected result: (<nil>) "<nil>"
│
│   with aws_secretsmanager_secret.tls,
│   on secret.tf line 32, in resource "aws_secretsmanager_secret" "tls":
│   32: resource "aws_secretsmanager_secret" "tls" {
```

Here is the Terraform resource :

```hcl
resource "aws_secretsmanager_secret" "tls" {
  name_prefix = "test-tls-"
}

resource "aws_secretsmanager_secret_version" "tls" {
  secret_id     = aws_secretsmanager_secret.tls.id
  secret_string = local.secret
}
``` 

I try to add `policy=""` or `policy="{}"`, the result is the same.
And if I try to add a valid policy, I get an error because the `put_resource_policy` action is not supported.

**Comment by bblommers** [comment]
Looks like we're returning a `None` value where TF expects an empty string, somehow, somewhere. Marking it as a bug.
