### ISSUE TITLE
use of sure package for asserts make pytest output hard to use

### ISSUE THREAD

**Issue by hans-d** [getmoto/moto#6035]
When running a test (which uses pytest), on a failing test and when using regular assert statements, various good info is shown already by pytest.

Using `sure`, this generates a lot of additional stack trace garbage, making it hard to discover the issue.
I've noticed that not all modules are using sure, so by removing `sure` we get more consistency in the code and more readability in case of a test failure.

Noticed when deep-diving into #6026. I'm ok to pick this up, when that one is wrapped.

**Comment by bpandola** [comment]
🙋  Raising my hand here in support of dropping `sure`.  It served us well for a while, but I don't think the value is there anymore, especially after `moto` made the switch from `nose` to `pytest`.  The way `sure` hijacks the Python internals might have been magical at first blush, but these days it seems like a liability.  It adds numerous attributes to every object that hinders active debugging; it utterly confuses PyCharm, resulting in countless errors and warnings; and, as @hans-d points out, it doesn't play well with `pytest`.

All that said, removing `sure` seems like it would require a *ton* of manual effort.  I know there are tools that automate moving from `nose`- and `unittest`-based assert methods to `pytest`-style  assertions, but I doubt something similar exists for moving away from `sure`.

@bblommers Maybe, at a minimum, we advise against using `sure` for any new tests?

**Comment by hans-d** [comment]
some fragments directly using`unittest` are also to be found.
Working through this code to help change this will aid me in getting a better grip of moto internals. Expecting it to be done in pieces, like the mypy chnages.

**Comment by bblommers** [comment]
Well, I do prefer the sure-style, as it reads better IMO, but you're both right that there's a long list of disadvantages. 

The approach makes sense as well - for now we can just stop new tests from using `sure`, and whenever possible we'll gradually upgrade the existing tests, file by file, service by service.

**Comment by bblommers** [comment]
I haven't found a way to automate everything, but some regexes that I found helpful when tackling this:

F `(\S+)\.should.equal\((.*)\)`
F `(\S+)\.should.equal\(\s+(\S+)\s+\)`
R `assert $1 == $2`

F `(\S+)\.should.not.equal\((.*)\)`
R `assert $1 != $2`

F `(\S+.+)\.should.contain\((.*)\)`
F `(\S+.+)\.should.contain\(\s+(".+")\s+\)`
R `assert $2 in $1`

F `(\S+.+)\.shouldnt.contain\((.*)\)`
F `(\S+.+)\.should.not.contain\((.*)\)`
R `assert $2 not in $1`

F `(\S+)\.should.have.length_of\((.*)\)`
R `assert len($1) == $2`

F `(\S+)\.should.have.length_of\(\s+(\d+)\s+\)`
R `assert len($1) == $2`

F `(\S+)\.shouldnt.have.key\((.*)\)`
R `assert $2 not in $1`

F `(\S+)\.should.have.key\((.*)\).equals\((.+)\)`
F `(\S+)\.should.have.key\((.*)\).equals\(\s+(\[.+\])\s+\)`
R `assert $1[$2] == $3`

F `(\S+)\.should.have.key\((.*)\).length_of\((.+)\)`
R `assert len($1[$2]) == $3`

F `(\S+)\.should.have.key\((.*)\)`
R `assert $2 in $1`
