### ISSUE TITLE
simple guide to extending moto ?

### ISSUE THREAD

**Issue by jhw** [getmoto/moto#6036]
I want to add support for AWS Translate. Single method only, `translate_text`. Is there a simple guide to adding support for a new service? I did look at the docs but couldn't find any simple guides. I looked at the Polly code for inspiration but found it all a bit arcane with backends, responses etc. Thx

**Comment by bblommers** [comment]
Hi @jhw, did you see this section of the docs?
http://docs.getmoto.org/en/latest/docs/contributing/new_feature.html

**Comment by jhw** [comment]
missed that - thank you
