### ISSUE TITLE
Type error using AMIS[0]

### ISSUE THREAD

**Issue by tekumara** [getmoto/moto#6062]
```python
from moto.ec2.models.amis import AMIS

an_ami =  AMIS[0]["ami_id"]
```

pyright/pylance on line 3:

```
Argument of type "Literal[0]" cannot be assigned to parameter "__key" of type "str" in function "__getitem__"
  "Literal[0]" is incompatible with "str" Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

Because `AMIS` is `Any`.

moto 4.1.4

**Comment by bblommers** [comment]
Hi @tekumara !
Adding type annotations to the entire code base is a WIP, and so far we only use mypy to determine correctness. Your suggested solution to add a specific type to `AMIS` makes sense to me, to make it clear what kind of response we expect.

Note that this does not mean we officially support `pyright`. If pyright finds any other issues we will have to make a decision whether it's worth the effort to introduce this to the project, and whether that would be a replacement to MyPy or an additional check.
