### ISSUE TITLE
Adding support for SNS's subscription FilterPolicyScope

### ISSUE THREAD

**Issue by dezeroku** [getmoto/moto#6087]
At the moment moto doesn't support specifying the `FilterPolicyScope` when [creating an SNS subscription](https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html#sns-message-filtering-scope).

This attribute is only useful if you want to filter the incoming messaged based on the `MessageBody` and not the `MessageAttributes`.
Adding a support for this would require parsing the attribute in SNS subscription and validating nested filter policies (take a look at [PR from the localstack's fork](https://github.com/localstack/moto/pull/62)) and actually implementing the logic on the backend.

I'd be happy to help and try to implement it if that's OK

**Comment by bblommers** [comment]
Hi @dezeroku, thanks for raising this! A PR would be very welcome - looks like LocalStacks' implemention would be a good start, as long as we do have some tests to verify this behaviour.
