### ISSUE TITLE
Automatic removal of data on mock stop is a breaking change

### ISSUE THREAD

**Issue by mwgamble** [getmoto/moto#6105]
This change was included in v4.1.4, but wasn't mentioned in the changelog: https://github.com/getmoto/moto/pull/5958

It's a breaking change for anyone who was relying on the data to be there after stopping the mock, to assert on what happened.

It's not too difficult to work around this, but it usually makes the code more verbose, and certainly not something I'd expect to turn up in a patch release.

Is there any scope for reverting this change? Is an acceptable compromise that when you're using the mock as a context manager, `remove_data` is set to `True`, but if you're calling `stop()` directly, `remove_data` defaults to `False`?

**Comment by bblommers** [comment]
Just to give some context: This was done to ensure that any file handles that Moto opens are disposed of appropriately.

Storing any object in S3 opens a file handle (in case it's a large file that we want to persist to disk, instead of in memory). When the mock stops, we want to make sure these file handles do not leak, by closing them (and by extension resetting all data). 

If the `remove_data` arguments becomes False by default, we make it the users responsibility to cleanup our data (by forcing them to call `stop(remove_data=True)`, and that is not very nice.
As far as I'm concerned, the ability to specify `remove_data=False` is (from an API design standpoint) a good compromise where Moto is responsible for it's own data, but users can override it if they know what they're doing.

FWIW - you're right that it is a breaking change. I simply wasn't aware that people are expecting the data to still be there after a mock ends. I considered the data-state in between mocks to be an (to the user irrelevant) implementation detail.

**Comment by mwgamble** [comment]
> This was done to ensure that any file handles that Moto opens are disposed of appropriately.

Even this doesn't seem to have been mentioned in the changelog, which made diagnosing this change unnecessarily difficult.

---

In the interest of future-proofing our code as much as possible, is your recommendation to assume this will always be wiped when the mocking ends, and not rely on the ability to call `stop(remove_data=False)`?

Right now, we have code that looks like this:

```python
with mock_cloudwatch() as cloudwatch:
    function_that_does_cloudwatch_stuff()

cloudwatch_backend = cloudwatch.backends["123456789012"]["ap-southeast-2"]
assert cloudwatch_backend.metric_data == [<something>]
```

We do this primarily so that only the code that actually needs to be mocked is mocked. It avoids papering over issues with code that wasn't intended to be mocking AWS calls.

It also avoids the need to indent potentially very large chunks of code unnecessarily. Sometimes we need to mock several things at once, and then assert a bunch of stuff after the fact. If we were to have to do this:

```python
with mock_cloudwatch() as cloudwatch:
    with mock_sts() as sts:
        with mock_lambda() as lambda:
            function_that_does_aws_stuff()
```

And then perform all of our assertions within the inner-most nested `with` statement, that would get pretty hard to work with.

Maybe if the mocks were compatible with `contextlib.ExitStack` it would be a bit nicer to work with :thinking: But we'd still be looking at indenting a lot of code that doesn't need it, and mocking things for longer than is necessary.

Are we doing this wrong? Is there a better way of inspecting what the mocks did?

**Comment by bblommers** [comment]
> is your recommendation to assume this will always be wiped when the mocking ends

Yes.
As far as I can see, the `remove_data`-argument is here to stay, so theoretically you could do this:
```
mock = mock_sqs()
mock.start()
boto3.client("sqs", region_name="us-west-1").create_queue(QueueName="queue1")
mock.stop(remove_data=False)
backend = sqs_backends[DEFAULT_ACCOUNT_ID]["us-west-1"]
print(backend.queues)
```
But the lack of indentation makes it quite hard to read, so I wouldn't recommend it.

----------------------
As far as checking the mock contents, I always prefer to use the boto3-clients. How Moto this data stores exactly shouldn't matter. So your first example, I would always write it as:
```
with mock_cloudwatch() as cloudwatch:
    function_that_does_cloudwatch_stuff()

    assert boto3.client("cloudwatch")... == "..."
```
That means 1) I don't have to worry about the exact structure that Moto uses, and 2) I could just remove the Moto-bits, run the test against AWS, and use the exact same assertions.

For multiple services - you can always use `mock_all`? That way you don't have to specify every single service in use.

In general, I actually prefer to use the function-decorators to avoid the hassle with indentations, but if you also have code that `wasn't intended to be mocking AWS calls`, I understand that may not be feasible.

**Comment by bblommers** [comment]
@mwgamble Would an environment variable to make this configurable be a solution?
`MOTO_DELETE_DATA_ON_EXIT`, defaults to false, but if set to True, all data will still be there after a mock ends.

**Comment by mwgamble** [comment]
I don't think an environment variable to control the behaviour globally is a good idea. That may have unintended side-effects on certain code that was only implemented to work with one mode or the other.

I'm happy with the compromise on calling `stop(remove_data=False)` manually as a path forward. I actually don't think it's a good idea to be calling "getter" methods on boto clients to observe the outcome of a test. That has additional business logic associated with it that isn't relevant to the code under test, and may fail itself in unexpected ways. I've always preferred reaching into the backends because it's a static process that doesn't involve any business logic at all. I would much rather see the interfaces for these backends stabalised and documented, because they're incredibly helpful.

**Comment by mwgamble** [comment]
Is there any chance the changelog could be updated to mention this change?

**Comment by bblommers** [comment]
The backends were never meant to be part of the public API, actually. It would be helpful to have them stabilized and documenting, but that would require an enormous amount of effort unfortunately. (Not to mention that AWS releases new features faster then we can mock them, so it will very difficult to stabilize something that's always changing...)

I will add the fact that data is now removed to the changelog.

**Comment by bblommers** [comment]
Done!

https://github.com/getmoto/moto/blob/fa2b6d28b04915aa2e7bf23f283ba3e104846c8b/CHANGELOG.md?plain=1#L75

**Comment by mwgamble** [comment]
Thank you <3
