### ISSUE TITLE
RDS describe_db_clusters is returning cluster not found when passing ClusterArn Filter for DBClusterIdentifier

### ISSUE THREAD

**Issue by asubramani82** [getmoto/moto#6109]
RDS describe_db_clusters is returning cluster not found when passing ClusterArn Filter for DBClusterIdentifier. Boto3 allow passing either ClusterArn or DBClusterIdentifier passed as filter to look up db cluster

`@mock_rds
def create_db_clusters():
    rds_client = client("rds", region_name="us-east-1")
    rds_client.create_db_cluster(
        DBClusterIdentifier=f"test-cluster-1",
        Engine="aurora-mysql",
        MasterUsername="root",
        MasterUserPassword="test123456789"
    )
    all_cluster = rds_client.describe_db_clusters()
    cluster_lookup_id = rds_client.describe_db_clusters(DBClusterIdentifier="test-cluster-1")
    cluster_lookup_arn = rds_client.describe_db_clusters(DBClusterIdentifier = "arn:aws:rds:us-east-1:123456789012:cluster:test-cluster-1")
`

Returning response
`cluster_lookup_id = rds_client.describe_db_clusters(DBClusterIdentifier="test-cluster-1")`

Failing with cluster not found Error
`response = rds_client.describe_db_clusters(DBClusterIdentifier = "arn:aws:rds:us-east-1:123456789012:cluster:test-cluster-0")`

Expectation:
describe_db_clusters using clusterArn as filter should return data if it exists as in Boto

Actual:
describe_db_clusters using clusterArn Failing with cluster not found Error even when the record exists

**Comment by bblommers** [comment]
Thanks for raising this @asubramani82, and welcome to Moto! Marking it as a bug.
