### ISSUE TITLE
Using moto within a pipeline

### ISSUE THREAD

**Issue by WesleyHindle** [getmoto/moto#6113]
Would it be appropriate to use moto within a pipeline for using for testing TF infra?

Ideally I'd like to be able to spin up a local instance of moto setting custom endpoints so I can then deploy TF to moto server. I would then like to implement testing stages where I make API calls to moto server to test whether the infra has been deployed as intended and use this as a way of testing infrastructure. 

Would moto be appropriate to use for this?

Thanks.

**Comment by bblommers** [comment]
That makes a lot of sense @WesleyHindle - using the MotoServer would allow you to test both the infrastructure and application code in unison, and verify that it plays nice together.

Are you running into any issues, after your initial testing from #5978?

**Comment by bblommers** [comment]
I'm going to assume this has been resolved - please open a new issue if you have any specific questions.
