### ISSUE TITLE
How to test for failing jobs in AWS Batch

### ISSUE THREAD

**Issue by rdbisme** [getmoto/moto#6117]
Hello, 

how can I test again some job that has been submitted in AWS Batch and then, after a while, fails? Is there a way to register a trigger of some sort to make it respond with a `"status": "FAILED"` to simulate a failing job?

**Comment by bblommers** [comment]
That is not yet possible @rdbisme. Sounds like it could be part of #5168 when we implement that.
Can you leave a comment there that you'd like the option to have a timer? I'll close this as a duplicate then.
