### ISSUE TITLE
Duplicate AMI listed in amis.json

### ISSUE THREAD

**Issue by ashemedai** [getmoto/moto#6119]
While working on some code using moto I looked at [moto/tree/master/moto/ec2/resources/amis.json](https://github.com/getmoto/moto/blob/3adbb8136a3ae81f7d5cb403f4d0a3aa100ee16f/moto/ec2/resources/amis.json#L716-L750) and noticed that the last AMI there is a duplicate entry. Both have AMI ID `ami-0b301ce3ce347599c`.

**Comment by bblommers** [comment]
Thanks for raising this @ashemedai!
