### ISSUE TITLE
API Gateway does not support ":" character in the resource path.

### ISSUE THREAD

**Issue by alanfung** [getmoto/moto#6148]
### Expectation:
Like the real API gateway, I want to create resource path with the character ":". This is important for our use case because we follow https://google.aip.dev/136 where ":" is commonly used.

### Actual:
When trying to create resource with path `myResource:foo`, receives an error `Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end and an optional plus sign before the closing brace.`

### Version:
I use it via the latest of localstack, from looking at the source, this should also be an issue on the latest version of moto.

------

Please add support for ":" in the regular expression here: https://github.com/getmoto/moto/blame/a4fe80d274eb711213e7c3251315b27889a973bb/moto/apigateway/models.py#L1737

Thank you!

**Comment by bblommers** [comment]
Unfortunately I couldn't find any documentation around this. But it looks really we are really just missing support for `:`, nothing else, based on some cursory testing against AWS.

Thanks for raising this @alanfung - marking it as an enhancement.

**Comment by alanfung** [comment]
Thanks for resolving this so quickly.
