### ISSUE TITLE
Inconsistency in moto behavior between mock_s3 and mock_dynamodb when using different regions

### ISSUE THREAD

**Issue by denrou** [getmoto/moto#6149]
When using moto to mock AWS services, I encountered an inconsistency in behavior between the `mock_s3` and `mock_dynamodb` decorators when using different regions in the mock and test functions.

In the provided code, both `test_s3` and `test_dynamodb` functions mock a client in a region different from the one defined in the test case. However, the behavior is different for each test:

1. **`test_s3`**: The test case does not fail. The bucket created in the mock is found in the test, even though the regions used in the mock and test case are different.
2. **`test_dynamodb`**: The test case fails. The table created in the mock is not found in the test, as the regions used in the mock and test case are different.

It is unclear what the expected behavior should be. Should `test_s3` fail as well, or should `test_dynamodb` succeed when using different regions in the mock and test case? Or am I doing something wrong in my implementation?

Here is the code to reproduce the issue:

```
import boto3
import pytest
from moto import mock_s3, mock_dynamodb
import os


@pytest.fixture
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ["AWS_ACCESS_KEY_ID"] = "testing"
    os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
    os.environ["AWS_SECURITY_TOKEN"] = "testing"
    os.environ["AWS_SESSION_TOKEN"] = "testing"


@pytest.fixture
def s3_client(aws_credentials: None):
    with mock_s3():
        yield boto3.client("s3", region_name="us-east-1")


@pytest.fixture
def bucket_name():
    return "testing"


@pytest.fixture
def s3_bucket(s3_client, bucket_name):
    s3_client.create_bucket(Bucket=bucket_name)
    yield s3_client


def test_aws(s3_bucket, bucket_name):
    client = boto3.client("s3", region_name="eu-west-1")
    response = client.list_buckets()
    assert response["Buckets"][0]["Name"] == bucket_name


@pytest.fixture
def dynamodb_client(aws_credentials: None):
    with mock_dynamodb():
        yield boto3.client("dynamodb", region_name="us-east-1")


@pytest.fixture
def table_name():
    yield "testing"


@pytest.fixture
def dynamodb_test(dynamodb_client, table_name):
    dynamodb_client.create_table(
        AttributeDefinitions=[
            {"AttributeName": "test", "AttributeType": "S"},
        ],
        TableName=table_name,
        KeySchema=[
            {"AttributeName": "test", "KeyType": "HASH"},
        ],
        ProvisionedThroughput={
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5,
        },
    )
    yield dynamodb_client


def test_dynamodb(dynamodb_test, table_name):
    client = boto3.client("dynamodb", region_name="eu-west-1")
    response = client.list_tables()
    assert len(response["TableNames"]) == 1
    assert response["TableNames"][0] == table_name
```

The inconsistency between `mock_s3` and `mock_dynamodb` behavior can lead to confusion when writing tests that involve multiple AWS services. Any clarification on the expected behavior or suggestions on how to fix this issue would be greatly appreciated.

moto: 4.1.6

**Comment by bblommers** [comment]
Hi @denrou, S3 is a global service, so buckets and objects may be created in a given region, but they can be retrieved from any region. That behavior is consistent with AWS as far as I know.

**Comment by denrou** [comment]
Thank you for the answers, I learnt something today :)
