### ISSUE TITLE
No support for `create_global_cluster` and `describe_global_clusters`

### ISSUE THREAD

**Issue by kevho48** [getmoto/moto#6151]
Currently using moto "version": "==4.1.7.dev7"
Trying to use moto to mock the following calls but noticed they don't seem to be fully implemented
- create_global_cluster
- describe_global_clusters

At the moment I can create the global cluster but it wont be populated with cluster members, and I can't seem to add any cluster members on them.

**Comment by bblommers** [comment]
Hi @kevho48, thanks for raising this!

Just to make sure we're on the same page, I had a quick look at the documentation, and based on my understanding, this is how AWS behaves (and how Moto should behave):

WHEN `create_global_cluster` is called
AND `create_db_cluster` is called with `GlobalClusterIdentifier` set to the global cluster ARN
THEN `describe_global_cluster` shows the second cluster as part of the GlobalClusterMembers
AND `describe_db_clusters` shows the cluster as normal

WHEN `create_db_cluster` is called
AND `create_global_cluster` is called with SourceDBClusterIdentifier set as the earlier created db cluster
THEN that db cluster is elevated to a global cluster
AND it no longer shows up when calling `describe_db_clusters`

WHEN `create_db_cluster` is called
AND `create_db_cluster` is called again with `ReplicationSourceIdentifier` set to the first cluster
THEN `promote_read_replica_db_cluster` can be called on the second cluster, elevating it to a read/write cluster

Is that the behaviour that you had in mind? And/or are there other scenarios?

**Comment by kevho48** [comment]
Hi @bblommers  thanks for looking at this.

When `describe_db_clusters` is called on a cluster that is part of a global cluster, it will still show up.

Everything else seems good.

**Comment by bblommers** [comment]
This functionality (and everything from #6175) is now part of moto >= 4.1.7.dev38. Please let us know if you run into any issues!
