### ISSUE TITLE
ecs run_task with `FARGATE` fails with no `container_instances`

### ISSUE THREAD

**Issue by ckdake** [getmoto/moto#6153]
We use ECS clusters to run tasks, exclusively with 'FARGATE' which runs tasks on FARGATE without us setting up container instances. 

When attempting to mock things out with moto, I receive the error  "No instances found in cluster" which comes from https://github.com/getmoto/moto/blob/d0cfddebfd32211bf665d359652039185cc214a7/moto/ecs/models.py#L1232

Moto is hard coded to require container_instances, and our "clusters" don't have them. 

Moto should instead, if all tasks are "FARGATE", return the tasks instead of trying to place them on container instances.

**Comment by ckdake** [comment]
Whoops! This is on me, it does this already. "Fargate" != "FARGATE". Closing!

**Comment by bblommers** [comment]
Does AWS throw an error if you specify an unknown type (such as `Fargate`)?
If do, it would be nice if `Moto` could do the same. That would prevent this from happening to others.

**Comment by ckdake** [comment]
I suspect it does, but I was writing this test from scratch. None of our actual code had a `Fargate` in there.
