### ISSUE TITLE
stepfunctions describe_execution always returns "RUNNING"

### ISSUE THREAD

**Issue by bfbenf** [getmoto/moto#6154]
Issue: When looking at the documentation for step-functions there was no mention of having to use `SF_EXECUTION_HISTORY_TYPE` to force it to change to a `FAILED` state. I worked this out by looking at the moto tests.

Link: https://docs.getmoto.org/en/latest/docs/services/stepfunctions.html

As has been done with SES there is a really nice intro to the documentation explaining how to use it. 
Link: https://docs.getmoto.org/en/latest/docs/services/ses.html

This is less of a bug than an improvement for future users trying to mock out step functions.

**Comment by bblommers** [comment]
Good shout @bfbenf - that should've indeed been part of the docs in the first place. We've updated the SFN page to show that `SF_EXECUTION_HISTORY_TYPE` can be used to get a `failure` result in all three methods (get, describe, list).
