### ISSUE TITLE
How to specify the port on which docker container should start in LambdaBackend

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [getmoto/moto#6165]
Hello, I am using moto version 4.1.4. I am trying to run Lambda function with docker image mlupin/docker-lambda. When I call invoke on mocked lambda_client the container begins to start up, but immediately shuts down with error: "listen tcp :9001: bind: address already in use". For sure this address is already in use, and I want this container to start on another port. But I have not found any option to specify it.
I looked inside this function:
https://github.com/getmoto/moto/blob/0e58d3996bbcc2cd9743303d40e3ead425a6d266/moto/awslambda/models.py#L706
No port passing.
Am i missing something?

**Comment by bblommers** [comment]
It looks like `mLupin` provides two environment variables that you can use to configure the port:
`DOCKER_LAMBDA_API_PORT` and `DOCKER_LAMBDA_RUNTIME_PORT`

See https://hub.docker.com/r/mlupin/docker-lambda#environment-variables

Does that help?

**Comment by Nikita-Sherstnev** [comment]
Well, I solved the problem by changing MOTO_DOCKER_NETWORK_MODE from host to bridge. Container starts and works properly, but I don't know on what port :) DOCKER_LAMBDA_RUNTIME_PORT set to 6000, but it does not affect container's port, as I set this port on other running container.
Anyway, initial problem is solved.

**Comment by bblommers** [comment]
Happy to hear that solves it.

I'll close this ticket then, but let us know if you run into any other issues.
