### ISSUE TITLE
S3 CreateBucket raising 411 when no Content-Length header is set

### ISSUE THREAD

**Issue by bentsku** [getmoto/moto#6179]
Hello,

It seems moto will raise a 411 Exception when calling the `CreateBucket` operation with no `content-length` header, even when there is no body while targeting `us-east-1` (so no `CreateBucketConfiguration` with `LocationConstraint`). It seems it should accept the request, as AWS does.
I am however not sure which other `Bucket` operations would accept to not have a `content-length` for a PUT request with no body, I am only aware of `CreateBucket` for now, as it is pretty difficult to test with Python, most libraries add the header automatically. 

https://github.com/getmoto/moto/blob/f424c6ac05673830925ec0e77a7972e54d4b275a/moto/s3/responses.py#L742-L744

You can reproduce by trying to create a bucket with the following:
`curl -XPUT http://localhost:4566/testbucket` 

This was a request logged in LocalStack by a user:
```
PUT localstack:4566/fusion-clients-tests
headers={
  'amz-sdk-invocation-id': '955a2a7d-77e0-2976-6325-045ac71bfd0f',
  'amz-sdk-request': 'attempt=1; max=4',
  'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20230405/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=b5d07fc83668cb981a7cdd281ddab085b7c48a7db33719ad9d0a7a84129d75b9',
  'User-Agent': 'aws-sdk-java/2.19.32 Linux/5.13.0-1022-aws OpenJDK_64-Bit_Server_VM/17.0.6+10 Java/17.0.6 vendor/Eclipse_Adoptium io/sync http/UrlConnection cfg/retry-mode/legacy',
  'x-amz-content-sha256': 'UNSIGNED-PAYLOAD',
  'X-Amz-Date': '20230405T123838Z',
  'Accept': '*/*',
  'Host': 'localstack:4566',
  'Connection': 'keep-alive',
  'x-localstack-tgt-api': 's3',
  'x-moto-account-id': '000000000000'
}); 
```
This request would work against AWS, even without the `content-length` header set. 

It seems this behaviour was added a while ago, in 2017. #908 / #924

**Comment by bblommers** [comment]
Hey @bentsku, thanks for raising this. Based on my testing, it looks like only CreateBucket request can ignore that header - all other requests need it.

Just to make it interesting - when sending a `CreateBucket` request with a body but without `ContentLength`-header, AWS will ignore the body.
So if you include a `CreateBucketConfiguration` because you want to create the bucket in another region, it will just ignore that part and create the bucket in `us-east-1`.

**Comment by bentsku** [comment]
Hi @bblommers! Thanks for your quick reply. 

Okay, well, that makes it a bit simpler if only `CreateBucket` follows this special case.
Yes, from my "research" when looking for this bug, it seems most web servers will ignore the body if the content-length is not present and it's not `Transfer-encoding: chunked` (I guess for security reasons), so this behaviour is actually "alright" for once, coming from S3 😄
