### ISSUE TITLE
DynamoDB put_item SerializationException when any key inside the Item is 'S'

### ISSUE THREAD

**Issue by hidi-adouv** [getmoto/moto#6182]
Hey everyone, thanks for the all the great work on this library. It makes unit testing a breeze! 

I ran into a bit of a strange issue with the Table.put_item() method in a mock DynamoDB table. It looks like if any key inside the item (including nested ones) is the character 'S', we get a SerializationException. 

`botocore.exceptions.ClientError: An error occurred (SerializationException) when calling the PutItem operation: Start of structure or map found where not expected`

While there is an obvious and simple workaround, (not to use 'S' as a key), it would be great to understand why this only occurs with the upper case 'S'. I have tried all letters of the alphabet, upper and lower, and the exception is triggered exclusively with 'S'. It does not matter where in the payload it might be. It could be deeply nested, and still raise the exception. If I replace it with, say an 'A', then it works fine again. My guess is that it might be related to the encoding (the tests I ran used the string.ascii_letters elements), but I cannot really be sure.

Here is a small example to replicate this behavior:
```
import string

import boto3
import moto

KEY_SCHEMA = [{'AttributeName': 'index', 'KeyType': 'HASH'}, ]
ATTRIBUTE_DEFINITIONS = [{'AttributeName': 'index', "AttributeType": "N"}, ]
PROVISIONING = {"ReadCapacityUnits": 1, "WriteCapacityUnits": 1}


@moto.mock_dynamodb
def test():
    dynamodb = boto3.resource('dynamodb')
    dynamodb.create_table(TableName="test",
                          KeySchema=KEY_SCHEMA,
                          AttributeDefinitions=ATTRIBUTE_DEFINITIONS,
                          ProvisionedThroughput=PROVISIONING
                          )
    # payload = {'index': 0, 's': None} # works fine!!!
    # payload = {'index: 0, 'A': None} # also works fine
    payload = {'index': 0, 'S': None}  # Doesn't work
    # payload = {'index': 0, 'A': {'S': None}} # Neither does this, but clearly not because of the 'A'
    table = dynamodb.Table(name='test')
    table.put_item(Item=payload)

test()

```

Some more info on the environment:

OS: Ubuntu 22.04.02 LTS
Python: 3.10.8
boto3: 1.24.28
botocore 1.27.59
moto 4.1.4

I raised this issue mostly out of curiosity, but it might be interesting to find out why this happens with such a specific example, and not others :D

**Comment by bblommers** [comment]
Appreciate the feedback @hidi-adouv, always good to hear that Moto is useful!

When using the DynamoDB client, users have to manually set the type of their attributes - so in your example, with one Number-attribute and one String, that would result in this: `{'index': {'N': '0'}, 'S': {'S': 's'}}`

Moto does some validation to verify that the attribute-types and values line up - i.e., an N should always be followed by a number, and an `S` should always follow a string. Looks like our validation is a bit too eager, by not allowing an S to be followed by a dictionary.
