### ISSUE TITLE
Performance Issues with Moto Library Updates

### ISSUE THREAD

**Issue by jushy10** [getmoto/moto#6223]
I have been running into some weird performance issues with the moto library. 
I am using `moto[s3,sns,cognitoidp]`

I did some further testing on my project and came up with these results when running my tests:

**Version = Test Time**
3.0.5 = 6 min 31 seconds
3.1.10 = 6 min 37 seconds
3.1.13 = 6 min 42 seconds
3.1.16 = 6 min 45 seconds
4.0.8 = 6 min 52 seconds
4.0.10 = 6 min 54 seconds
4.0.13 = 7 min 9 seconds
4.1.0 = 7 min 17 seconds
4.1.4 = 7 min 18 seconds
4.1.7 = 7 min 19 seconds

It seems that with every version update, the tests become slower and slower.

I am also using: 
```
boto==2.49.0
boto3==1.26.109
```

**Comment by bblommers** [comment]
Hi @jushy10, welcome to Moto! Can you nail it down to specific methods? Or can you share a small reproducible test that shows the issue?

**Comment by bblommers** [comment]
OK, I'm going to close this - there's not much we can do without a test case to reproduce.
