### ISSUE TITLE
SSM `describe_parameters` `ParameterFilters` fails when `Values` is not provided

### ISSUE THREAD

**Issue by nerdyman** [getmoto/moto#6233]
Hi, 

I'm using Moto to mock the SSM client and am running into an error. One of my filters does not have a value which causes Moto to throw an error, but the real code works fine.

With this code:

```py
paginator = ssm.get_paginator("describe_parameters")
    paginated_parameters = paginator.paginate(
        ParameterFilters=[
            {"Key": "tag:test", "Option": "Equals", "Values": ["example-tag"]},
            {"Key": "tag:exists"},
        ],
    )
```

I get the following error:

```
An error occurred (InvalidFilterValue) when calling the DescribeParameters operation: The following filter values are missing : null for filter key Name.')
```

The docs for [`DescribeParameters`](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribeParameters.html#API_DescribeParameters_RequestParameters) say `ParameterFilters` uses an array of [`ParameterStringFilter`](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ParameterStringFilter.html#systemsmanager-Type-ParameterStringFilter-Values) objects in which `Values` is optional.

The error looks to come from here https://github.com/getmoto/moto/blob/f1286506beb524e6bb0bd6449c0e2ff4a9cfe2d0/moto/ssm/models.py#L1439 

There might be some extra logic needed to only fail if `Filters` is used and the `Values` parameter is not required as `Filters` uses [`ParametersFilter`](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ParametersFilter.html#systemsmanager-Type-ParametersFilter-Values) which *does* require `Values`?

Hopefully this is valid issue, I'm fairly new to the AWS API so might have missed something 🙏

**Comment by bblommers** [comment]
Thanks for raising this @nerdyman - that looks indeed like a bug.

**Comment by nerdyman** [comment]
Thanks for quick turnaround @bblommers, much appreciated!

**Comment by bblommers** [comment]
Happy to help @nerdyman!
