### ISSUE TITLE
Directory for s3 object

### ISSUE THREAD

**Issue by digihunch** [getmoto/moto#6267]
I used moto in Container to mock S3 service. When I store, for example, an object to S3, what is the storage location inside of the container? 
I am looking for ways to map the directory to a host directory so that the objects can persist after the moto container has been restarted.

**Comment by bblommers** [comment]
Hi @digihunch, we use a `SpooledTemporaryFile` to store uploaded files. So small objects are kept in memory, and larger objects are persisted in the temp directory.
Having a persistent directory the way you're describing is really outside the scope of Moto. 

As an alternative, you could record/replay the S3 requests to make them 'almost' automatically appear on startup: http://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html

**Comment by digihunch** [comment]
Thanks. i'll check out the recording feature which appears to be semi-helpful in my situation.
