### ISSUE TITLE
NotImplementedError: The detect_pii_entities action has not been implemented

### ISSUE THREAD

**Issue by goodspb** [getmoto/moto#6268]
I am using moto==4.1.8, and start as the server via the command: 

```bash
moto_server -p3000
```

I also set my boto3 endpoint_url=http://127.0.0.1:3000

then when I trigger my code which includes AWS Comprehend function Detect PII Entities. turns out this error from the moto_server side: 

```
NotImplementedError: The detect_pii_entities action has not been implemented
```

thanks.

**Comment by bblommers** [comment]
Thanks for raising this @goodspb, and welcome to Moto! Marking this as an enhancement to add this feature.

**Comment by rafcio19** [comment]
@goodspb the `detect_pii_entities` will return a canned response. Do you have any preference as what should that be? If not then how about something like:

```
{'Entities': [
  {'Score': 0.9999890923500061, 'Type': 'NAME', 'BeginOffset': 50, 'EndOffset': 58}, 
  {'Score': 0.9999966621398926, 'Type': 'EMAIL', 'BeginOffset': 230, 'EndOffset': 259}, 
  {'Score': 0.9999954700469971, 'Type': 'BANK_ACCOUNT_NUMBER', 'BeginOffset': 334, 'EndOffset': 349}
]}
```

**Comment by goodspb** [comment]
@rafcio19 that would be great. thanks for the help.
