### ISSUE TITLE
The behavior of ec2.describe_instances is not right

### ISSUE THREAD

**Issue by MacHu-GWU** [getmoto/moto#6282]
Basically in describe instances paginator (not the regular one) API call, if instance id is given, you could not use Pagination Config because aws expect to get small list of object. It will raise ``botocore.exceptions.ClientError: An error occurred (InvalidParameterCombination) when calling the DescribeInstances operation: The parameter instancesSet cannot be used with the parameter maxResults`` error. But moto doesn't validate the parameter.

```
# this is invalid
ec2_client.paginator("describe_instances").paginate(
     InstanceIds=instance_ids,
     PaginationConfig={
         "MaxItems": 9999,
         "PageSize": 100,
     },
)
```

**Comment by rafcio19** [comment]
@bblommers I can take a look at this
