### ISSUE TITLE
Cloud Formation delete_stack_instances implementation does not remove all instances when multiple regions are specified.

### ISSUE THREAD

**Issue by delia-iuga** [getmoto/moto#6297]
## Reporting Bugs

Cloud Formation delete_stack_instances implementation does not remove all instances when multiple regions are specified.

I am writing a test with the following steps: 

- create CF stack: 

```
create_stack_set(
        StackSetName=mock_stack_name,
        TemplateBody="{AWSTemplateFormatVersion: 2010-09-09,Resources:{}}"
    )
```

- create stack instances(in 2 regions) for an account:

```
create_stack_instances(
        StackSetName=mock_stack_name,
        Accounts=[account_id],
        Regions=['eu-west-1', 'eu-west-2']
    )
```

- list stack instances to ensure creation was successful in both regions:
```
list_stack_instances(
        StackSetName=mock_stack_name,
        StackInstanceAccount=account_id
    )
```

- delete all stack instances:
```
delete_stack_instances(
        Accounts=[account_id],
        StackSetName=mock_stack_name,
        Regions=['eu-west-1', 'eu-west-2'],
        RetainStacks=True
    )
```

- lit stack instances again to ensure all were removed:
`assert len(response['Summaries']) == 0  `
expected: PASS, actual FAIL, and when printing the length of the list, I see there is one instance left(the one from eu-west-2).

When checking the implementation in [detail](https://github.com/getmoto/moto/blob/1380d288766fbc7a284796ec597874f8b3e1c29a/moto/cloudformation/models.py#L348), I see the following:
```
for instance in self.stack_instances:
            if instance.region_name in regions and instance.account_id in accounts:
                instance.delete()
                self.stack_instances.remove(instance)
```
in my case, the self.stack_instances has initially length 2

1. first iteration: 
- before _remove_ action: index = 0, self.stack_instances length: 2
- after _remove_ action: index = 0, self.stack_instances length: 1

The second iteration will not happen since the index will be 1, the length 1 as well, and the loop will be finished, but leaving an instance that was not deleted.  And this will lead to unexpected errors when I am checking the output of the delete operation. 

I am using moto version 4.1.8

**Comment by bblommers** [comment]
Thanks for raising this @delia-iuga, and welcome to Moto! Marking it as a bug.
