### ISSUE TITLE
Create route with VPC endpoint as destination not working

### ISSUE THREAD

**Issue by kunalvudathu** [getmoto/moto#6301]
When I try to create a route containing VPC endpoint as destination, the route gets created but the response doesn't contain the vpce id

code to create: 
`ec2_client.create_route(DestinationCidrBlock=dest_cidr, VpcEndpointId=dest_resource_id,
                                  RouteTableId=rtb_id)`

Output as seen here doesn't contain vpce-id but does contain destination cidr:
![image](https://user-images.githubusercontent.com/92550453/236992651-cd37f66c-8ecc-44a6-bff5-78c6aef37fde.jpeg)

Thank you so much!

**Comment by rafcio19** [comment]
@bblommers I can take a look

**Comment by kunalvudathu** [comment]
Thank you so much!

**Comment by kunalvudathu** [comment]
Unlike [issue](https://github.com/getmoto/moto/issues/6305), Just wanted to add that tested with latest moto version, 4.1.9, this bug still exists

**Comment by kunalvudathu** [comment]
Thank you! just curious, when will 4.1.10 be released? also, what dev version can i get access to this feature?

**Comment by bblommers** [comment]
There is no date set for 4.1.10 yet @kunalvudathu - probably in about a week or so. The dev-release for this particular feature failed for some reason, but it should be part of `moto>=4.1.10.dev16`.

**Comment by bblommers** [comment]
Release is out @kunalvudathu! 

https://pypi.org/project/moto/4.1.10/
