### ISSUE TITLE
S3 Put Object results in empty object

### ISSUE THREAD

**Issue by tiger-at-cranius** [getmoto/moto#6304]
I'm using `moto==4.1.9`, `boto3==1.12.130`, `botocore==1.29.130`, installing using `pip3` and used locally with `pytest`. When I use the `mock_s3` decorator on my test function, and I use the `put_object` method, it returns a `200` response and has the correct `content-length`. However, afterwards, when listing or getting the same object, I'm seeing that the object is empty (size 0, getting response has content-length 0, empty string in StreamingBody). I tried the exact same code on actual AWS without moto and saw that it works as intended.

These lines:
```
print(client.put_object(Bucket=bucket_name, Key=object_key, Body=object_bytes))
print(client.list_objects_v2(Bucket=bucket_name))
print(client.get_object(Bucket=bucket_name, Key=object_key))
```
produce:
`{'ResponseMetadata': {'RequestId': 'i0DFcaoFLhCWtHgPf0hFwR2JJa9zhSJLdeYUXpqaO2Bw83wfJnR0', 'HTTPStatusCode': 200, 'HTTPHeaders': {'etag': '"acec3b1a0e04ec342b20a9806f457f73"', 'last-modified': 'Tue, 09 May 2023 17:27:44 GMT', 'content-length': '526', 'x-amzn-requestid': 'i0DFcaoFLhCWtHgPf0hFwR2JJa9zhSJLdeYUXpqaO2Bw83wfJnR0'}, 'RetryAttempts': 0}, 'ETag': '"acec3b1a0e04ec342b20a9806f457f73"'}`

`{'ResponseMetadata': {'RequestId': '0PFrxzxloKiRQ9H75GnB1DOxr6t4vNAJDJK72HfHvGvfIepWiid4', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '0PFrxzxloKiRQ9H75GnB1DOxr6t4vNAJDJK72HfHvGvfIepWiid4'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Contents': [{'Key': 'example', 'LastModified': datetime.datetime(2023, 5, 9, 17, 27, 44, tzinfo=tzutc()), 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'Size': 0, 'StorageClass': 'STANDARD'}], 'Name': 'test_bucket', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 1}`

`{'ResponseMetadata': {'RequestId': 'C14lrvXAODAz590NZ4ni0IVX9teLboCX6fhe3N3DbbwmVqfkONii', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'binary/octet-stream', 'content-md5': 'rOw7Gg4E7DQrIKmAb0V/cw==', 'etag': '"d41d8cd98f00b204e9800998ecf8427e"', 'last-modified': 'Tue, 09 May 2023 17:27:44 GMT', 'content-length': '0', 'acceptranges': 'bytes', 'x-amzn-requestid': 'C14lrvXAODAz590NZ4ni0IVX9teLboCX6fhe3N3DbbwmVqfkONii'}, 'RetryAttempts': 0}, 'LastModified': datetime.datetime(2023, 5, 9, 17, 27, 44, tzinfo=tzutc()), 'ContentLength': 0, 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'ContentType': 'binary/octet-stream', 'Metadata': {}, 'Body': <botocore.response.StreamingBody object at 0x109bd29a0>}`

Note the `content-length` and `Size` fields. `ETag`s also seems to confirm that after putting the object, it becomes empty, but not before.

**Comment by bblommers** [comment]
Hi @tiger-at-cranius, are you able to create a small (stand-alone) test that shows this bug?

**Comment by bblommers** [comment]
OK, so the patch-client isn't necessary in this particular example. It works if you remove that line.

Patching is only necessary if the `client` is instantiated before `moto.core` is imported.

The reason that you're seeing the error:
Both `mock_s3` and `patch_client` register the same event-handler, so that when `s3.put_object` is called, the request is now handled twice by Moto. Because the Body from the request is consumed in the first request, the second request has no Body anymore and the key is set/overwritten without content (`b''`).

I'll raise a PR shortly to prevent the event handler from being registered twice.

**Comment by tiger-at-cranius** [comment]
I thought according to this: http://docs.getmoto.org/en/latest/docs/getting_started.html#patching-the-client-or-resource
since I am importing my file with the S3 client instantiation in it at the top of the file, instead of inside the test case, I would have to patch that client. Is my understanding of this wrong?

**Comment by tiger-at-cranius** [comment]
Thank you!
But according to the [documentation](http://docs.getmoto.org/en/latest/docs/getting_started.html#patching-the-client-or-resource), they do both. Is there something I am misunderstanding?
Also of note is that I did the same thing using the mock_secretsmanager and there were no problems there.

**Comment by bblommers** [comment]
The following example would not require the client to be patched. 
```
import boto3
from moto.core import *  # anything
session = boto3.session.Session()
client = session.client(service_name='s3', region_name=os.getenv("AWS_REGION", "us-east-1"))
```

The `moto.core` module registers the necessary event handler when loaded, so simply importing it ensures that the client is ready.

-----------------

If the client is initialized first, then it _does_ need to be patched:
```
import boto3
session = boto3.session.Session()
client = session.client(service_name='s3', region_name=os.getenv("AWS_REGION", "us-east-1"))


from moto.core import patch_client
patch_client(client)
```

Does that make sense?

**Comment by tiger-at-cranius** [comment]
I see. I feel like this isn't expressed in the documentation though. It could be useful to clarify, especially in the Recommended Usage section I was looking at.

**Comment by bblommers** [comment]
That's fair @tiger-at-cranius. I've raised #6327 that explain this section a bit better. Let me know if you see any other imporovements around this.
