### ISSUE TITLE
mock_cloudformation with SNS fails to delete stack

### ISSUE THREAD

**Issue by pwrmiller** [getmoto/moto#6311]
Using the mock_cloudformation, creating a stack containing a single SNS topic, then deleting the stack fails with an invalid ARN 

## Reproduction steps:

```python
def test_failure(cloudformation_mock):
    cloudformation_mock.create_stack(
        StackName="test-stack",
        TemplateBody='{"Resources": {"Bucket": {"Type": "AWS::SNS::Topic"}}}'
    )
    cloudformation_mock.delete_stack(StackName="test-stack")
```

Error is:
```
E           botocore.exceptions.ClientError: An error occurred (NotFound) when calling the DeleteStack operation: Topic with arn arn:aws:sns:us-east-1:123456789012:arn:aws:sns:us-east-1:123456789012:test-stack-Bucket-RYQRXXZJ9IRT not found
```

Note the duplicated and invalid ARN - for some reason moto has duplicated the ARN in this resource. This does not happen for other simple resources (e.g. S3 bucket). I would expect the ARN to match what is generated by the template. 

## Version:

- moto 4.1.9
- boto3 1.26.129
- botocore 1.29.129

**Comment by bblommers** [comment]
Thanks for raising this @pwrmiller - marking it as a bug. I'll submit a PR to fix this shortly.
