### ISSUE TITLE
Error in S3 compute_checksum()

### ISSUE THREAD

**Issue by badmetacoder** [getmoto/moto#6315]
There is an issue with the way CRC32 and CRC32C checksums are computed in `compute_checksum()`. They are treated as the same, which is incorrect. See [this line](https://github.com/getmoto/moto/blob/6b2ee153e61def632808015d35ea3e32ac585483/moto/s3/utils.py#L202). Consequently, the tests for `compute_checksum()` are incorrect, see
https://github.com/getmoto/moto/blob/6b2ee153e61def632808015d35ea3e32ac585483/tests/test_s3/test_s3_utils.py#L139C1-L144

The correct value of **CRC32** for `somedata` is `Uwy90A==`
The correct value of **CRC3C** for `somedata` is `dB9qBQ==`

CRC32C computation is best handled with `crc32c`.

**Comment by bblommers** [comment]
Hi @badmetacoder, welcome to Moto! That is indeed not implemented yet, for a few reasons:

 - I wanted to avoid introducing a new dependency for functionality that will be unnoticed/unused for 99% for users
 - Libraries that compute `crc32c` are either a license-mess, and/or do not support ARM architectures

Do you have a specific test case were you need Moto to support the `CRC32C` checksum?

**Comment by badmetacoder** [comment]
> Hi @badmetacoder, welcome to Moto! That is indeed not implemented yet, for a few reasons:
> 
> * I wanted to avoid introducing a new dependency for functionality that will be unnoticed/unused for 99% for users
> * Libraries that compute `crc32c` are either a license-mess, and/or do not support ARM architectures
> 
> Do you have a specific test case were you need Moto to support the `CRC32C` checksum?

I am guessing this could be an [optional] install for those who need it. My use cases are 

1. clients uploading data via pre-signed URLs and wanting to ensure data integrity (large files containing important data);
2. processes generating reports and uploading them to S3 and then allowing external parties to download and verify integrity of downloaded data.

I have tests for these cases and right now can only verify that I am setting the Checksum algorithm to a specific type. It's something, but not ideal and doesn't test for checksum validation failures.

**Comment by bblommers** [comment]
This is now part of moto[s3crc32c] >= 4.1.14.dev8. Alternatively you can just install `crc32c` manually and Moto will use that module to compute the checksum.

Docs here: http://docs.getmoto.org/en/latest/docs/services/s3.html

Just let us know if you run into any other issues @badmetacoder
