### ISSUE TITLE
AWS SSM put Parameter HTTP header should include a last modified date

### ISSUE THREAD

**Issue by MacHu-GWU** [getmoto/moto#6321]
See this: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm/client/put_parameter.html
The response should have a ``date`` field to indicate the last modified date time

```
{
    "ResponseMetadata": {
        "HTTPHeaders": {
            "date": "last modified date in %a, %d %b %Y %H:%M:%S %Z format"
        }
    }
}
```

**Comment by rafcio19** [comment]
I can take a look at this

**Comment by MacHu-GWU** [comment]
You can do this. If it is real AWS Parameter Store, then you will see date in metadata. If you use moto, then you don't see it.

```
boto3.client("ssm").put_parameter(...)
```

**Comment by rafcio19** [comment]
@MacHu-GWU thanks for the tip, indeed there exists `date` key in `HTTPHeaders`:

```
{
	'Parameter': {
		'Name': 'test',
                 .....
		'DataType': 'text'
	},
	'ResponseMetadata': {
		'RequestId': '81aef9ae-8988-488e-8752-3329d30d606d',
		'HTTPStatusCode': 200,
		'HTTPHeaders': {
			'server': 'Server',
			'date': 'Tue, 16 May 2023 11:27:39 GMT',
			'content-type': 'application/x-amz-json-1.1',
			'content-length': '196',
			'connection': 'keep-alive',
			'x-amzn-requestid': '81aef9ae-8988-488e-8752-3329d30d606d'
		},
		'RetryAttempts': 0
	}
}
```

However, it looks like it is present in all AWS calls to all services - so it appears this is a server side timestamp of the response. I will look into how we can add this for all services
