### ISSUE TITLE
update_secret doesn't update description

### ISSUE THREAD

**Issue by mdavis-xyz** [getmoto/moto#6347]
The `update_secret` call for secretsmanager has a `description` field.
Without moto, you can update the description.
With moto, the description is not updated.

The implementation in [responses.py](https://github.com/getmoto/moto/blob/master/moto/secretsmanager/responses.py#L70-L82) and [models.py](https://github.com/getmoto/moto/blob/master/moto/secretsmanager/models.py#L348C3-L355) does not appear to mention description at all.

Steps to reproduce:

```
from random import randrange

from moto import mock_secretsmanager
import boto3


mock_secretsmanager().start()

client = boto3.client('secretsmanager')

secret_name = f'test-moto-{randrange(100)}'
secret_string = 'secretthing'

response = client.create_secret(
    Name=secret_name,
    Description='first description',
    SecretString=secret_string,
)

client.update_secret(
    SecretId=secret_name,
    Description='second description',
)

response = client.describe_secret(
    SecretId=secret_name
)
print(f"Description is {response['Description']}")
assert response['Description'] == 'second description'

client.delete_secret(
    SecretId=secret_name,
    ForceDeleteWithoutRecovery=True
)
```

If you run as is (with moto), the assertion fails, because the description is still "first description".

If you comment out `mock_secretsmanager().start()`, the assertion passes. The description was updated.

**Comment by bblommers** [comment]
Thanks for letting us know @mdavis-xyz! I've raised a PR to add this functionality
