### ISSUE TITLE
SNS topics on incorrect region unexpectedly succeeds

### ISSUE THREAD

**Issue by raffienficiaud** [getmoto/moto#6354]
## Reporting Bugs

Dear `moto` team, I am wondering if this is the expected behaviour but it seems the behaviour changed recently (`4.0.11` vs `4.1.10`, always installed with `pip`).
I am creating a topic in a region and trying to load it in another region. I was expecting this fail which was the case in 4.0.11

Step to reproduce:

```
region = "us-east-1"
region_wrong = "us-west-2"

sns_client = boto3.client("sns", region_name=region)
topic_name = "test-sns-" + str(uuid.uuid4())
response = sns_client.create_topic(
    Name=topic_name,
    Attributes={
        "DisplayName": "hello topic",
    },
)

# here the topic was created in "region", and we are fetching it in "region_wrong"
topic_arn = response["TopicArn"]
sns_resource = boto3.resource("sns", region_name=region_wrong)
topic = sns_resource.Topic(topic_arn)
topic.load()     # exception ClientError used to be raised here
```

Let me know what you think!

**Comment by bblommers** [comment]
Thanks for letting us know @raffienficiaud - looks like this we accidentally enable cross-region access while adding cross-account access. Will raise a PR shortly.
