### ISSUE TITLE
CORS rules not being applied to PUT responses

### ISSUE THREAD

**Issue by dcappellini** [getmoto/moto#6371]
Hello! I'm the author of [this issue](https://github.com/getmoto/moto/issues/4220) which was solved on [this PR](https://github.com/getmoto/moto/pull/4497). So first off I'd like to thank you for looking into it.

Some time has passed but only now we've been able to update to the new Moto and try to get rid of our workaround. Unfortunately, the change did not solve the issue for us.

Moto version: 4.1.0.dev0 (Moto standalone server)
How I installed it:

sudo apt install python-pip
pip install "moto[s3]"
pip install flask
pip install flask_cors
Environment: pipenv with Python 3.8.0 running on an Ubuntu 18.04.6 LTS machine.

The original problem was that Moto for S3 accepted GetBucketCors requests but didn't apply the CORS rules later on. We in particular needed to set `"ExposeHeaders": ["ETag"]` so that Moto would send an `Access-Control-Expose-Headers: ETag` header in the response. This is because we're using the standalone Moto server and working with a browser controlled by Selenium, and the browser won't let the S3 client running inside it ([EvaporateJS](https://github.com/TTLabs/EvaporateJS)) read the ETag if that header isn't present.

In the current version, if we add a CORS rule, Moto takes it into consideration when responding to a CORS preflight request, which is an OPTIONS request. However, our upload still isn't working. After some more investigation and debugging, we came to the conclusion that it's not enough for the browser to receive the `Access-Control-Expose-Headers: ETag` in the preflight response, the server also needs to provide that header when responding to each individual PUT request that the client does to upload the file parts. 

Here's how Amazon S3 responds to our PUT requests when we upload each part:

![image](https://github.com/getmoto/moto/assets/4132918/fc8ea5ff-b928-4dab-8313-e5e792a815db)

And here's the same response from Moto:

![image](https://github.com/getmoto/moto/assets/4132918/e0f6b3e8-39c3-4e11-a222-b9b0d9908742)

I used BurpSuite to debug the scenario, and if I add the missing header `Access-Control-Expose-Headers: ETag` to the Moto response for each part's PUT, it works fine. The header is present in the preflight response thanks to the fix from the PR I mentioned, it's just missing from the PUT response.

I looked a little bit into the code and it looks like the extra headers are added in the `_set_cors_headers()` in moto/s3/responses.py. This method is only called from `_response_options()` which handles OPTIONS request. I'm guessing something similar needs to be done in `_key_response_put()` but I don't have the expertise in this project to do it myself.

Could you please look into this one more time? Thank you very much in advance!!

**Comment by bblommers** [comment]
Hi @dcappellini, thanks for letting us know! I've raised a PR to also return these headers for GET/PUT requests.

**Comment by bblommers** [comment]
This should now be fixed as of moto >= 4.1.12.dev8 @dcappellini  - just let us know if you run into any other issues.

**Comment by dcappellini** [comment]
It looks like it works fine now, thank you so much!!
