### ISSUE TITLE
Please Mock appconfig

### ISSUE THREAD

**Issue by soren-wandrup-bendixen** [getmoto/moto#6372]
There is no mock on appconfig. I need the 
        appconfig = boto3.client('appconfig')
        response = appconfig.get_hosted_configuration_version(
            ApplicationId = event["detail"]["requestParameters"]["applicationId"],
            ConfigurationProfileId=event["detail"]["ConfigurationProfile"]["Id"],
            VersionNumber=int(event["detail"]["ConfigurationVersion"])
        )

And before that in my test I need to be able to call : 
    appconfig = boto3.client('appconfig')
    application_response = appconfig.create_application(
        Name='Test'
    )
    configuration_profile_response = appconfig.create_configuration_profile(
        ApplicationId=application_response['Id'],
        Name='Normal',
        LocationUri='hosted',
        Type='freeform'
    )
    hosted_configuration_version_response = appconfig.create_hosted_configuration_version(
        ApplicationId=application_response['Id'],
        ConfigurationProfileId=configuration_profile_response['Id'],
        Content=NORNAL_CONTENTS,
        ContentType="application/json"
    )    
Thanks in advance
Br Soren Wandrup-Bendixen
email: swb@keycore.dk

**Comment by bblommers** [comment]
Welcome to Moto @soren-wandrup-bendixen, and thanks for raising this - marking it as an enhancement to add this service.

**Comment by bblommers** [comment]
Hi @soren-wandrup-bendixen, this service is now part of moto >= 4.1.12.dev20 - see the documentation here: http://docs.getmoto.org/en/latest/docs/services/appconfig.html. 

Please let us know if you run into any issues.
