### ISSUE TITLE
add_role_to_instance_profile does not behave like aws

### ISSUE THREAD

**Issue by shughes-uk** [getmoto/moto#6404]
Moto Version: 4.1.9

When using `iam.add_role_to_instance_profile`, moto should throw the same exception that AWS does if you attempt to attach a second role to an instance profile. Their API is set up like you can attach multiple, but in the endpoint docs they explain the maximum quota for attached roles is 1 and cannot be raised.

```
An instance profile can contain only one role, and this quota cannot be increased.
```

https://docs.aws.amazon.com/IAM/latest/APIReference/API_AddRoleToInstanceProfile.html

Offhand I believe they throw a `LimitExceeded` with the message `Cannot exceed quota for InstanceSessionsPerInstanceProfile`

**Comment by bblommers** [comment]
Thanks for raising this @shughes-uk - marking it as an enhancement to add this validation to Moto.

I've just checked against AWS, and they actually give the actual quota as part of the error message: `Cannot exceed quota for InstanceSessionsPerInstanceProfile: 1`

**Comment by rafcio19** [comment]
@bblommers I can take a look
