### ISSUE TITLE
Include IoT Thing connectivity status on iot.search_index response

### ISSUE THREAD

**Issue by LVSant** [getmoto/moto#6418]
Thanks for the fantastic work you do with Moto!

I want to ask you to include the `connectivity` response to the [search_index](https://github.com/getmoto/moto/blob/master/tests/test_iot/test_iot_search.py#L24) method of IoT if possible.

You can [see how boto3 does that](https://boto3.amazonaws.com/v1/documentation/api/1.26.85/reference/services/iot/client/search_index.html), basically a few more fields inside the `things` key.

```
{
    'nextToken': 'string',
    'things': [
        {
            'thingName': 'string',
            'thingId': 'string',
            'thingTypeName': 'string',
            'thingGroupNames': [
                'string',
            ],
            'attributes': {
                'string': 'string'
            },
            'shadow': 'string',
            'deviceDefender': 'string',
            'connectivity': {
                'connected': True|False,
                'timestamp': 123,
                'disconnectReason': 'string'
            }
        },
    ],
    'thingGroups': [
        {
            'thingGroupName': 'string',
            'thingGroupId': 'string',
            'thingGroupDescription': 'string',
            'attributes': {
                'string': 'string'
            },
            'parentGroupNames': [
                'string',
            ]
        },
    ]
}
```

Thanks again!

**Comment by bblommers** [comment]
Hi @LVSant, thanks for raising this.

The `connectivity`-data is calculated by AWS, I assume? So there is no good way to emulate that - we will just have to hardcode this part of the response, and assume devices are always connected.
