### ISSUE TITLE
rds_client.create_db_snapshot, describe_db_snapshots behavior not right due to the snapshot type attribute

### ISSUE THREAD

**Issue by MacHu-GWU** [getmoto/moto#6419]
## What went wrong?

Based on this aws document [create_db_snapshot](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds/client/create_db_snapshot.html), the db snapshot created by this method should have ``SnapshotType = "manual"``.

However, in moto's implementation the [DatabaseSnapshot](https://github.com/getmoto/moto/blob/master/moto/rds/models.py#L1051) model doesn't have snapshot type attribute ( but it is defined in filters, werid)

## How to fix it 

1. add ``snapshot_type`` attribute in ``DatabaseSnapshot.__init__``
2. update ``create_db_snapshot`` method and ``describe_db_snapshots`` method.

## One more thing

I bet the ``create_db_cluster_snapshot`` related methods and datamodel has the same issue.

**Comment by bblommers** [comment]
Hi @MacHu-GWU, thanks for raising this! The SnapshotType is hardcoded manually atm:
https://github.com/getmoto/moto/blob/bec9130d4c474674ef2beb3cc4acc756aa270793/moto/rds/models.py#L1095

I'll raise a PR to fix this.
