### ISSUE TITLE
curl is used but official Docker image does not contain curl

### ISSUE THREAD

**Issue by benjamin9fin** [getmoto/moto#6423]
See https://github.com/getmoto/moto/blob/7b982522144e3f75e936560e76a92a798fe4e0fd/moto/settings.py#L125
```
 cmd = "curl -s --unix-socket /run/docker.sock http://docker/containers/$HOSTNAME/json"
```
But curl is not installed in the Dockerfile.

**Comment by bblommers** [comment]
Thank you for raising and fixing this @benjamin9fin!
