### ISSUE TITLE
Moto allows stepfunctions invocation name with length > 80 but AWS rejects it

### ISSUE THREAD

**Issue by benjamin9fin** [getmoto/moto#6438]
Moto allows a step functions invocation to have a name with a length greater than 80 characters, however if such an invocation name is used in AWS it results in an error:

```
An error occurred (ValidationException) when calling the StartExecution operation: 1 validation error detected: Value 'test.025209ba-7ed1-4c17-833d-58ae02a4d3da.event.5a16f095-76e5-8750-b331-ac534c8f305a' at 'name' failed to satisfy constraint: Member must have length less than or equal to 80
```

Moto should mimic this behaviour and raise an error if names > 80 characters are used.

**Comment by rafcio19** [comment]
@bblommers I can take a look
