### ISSUE TITLE
Is possible use decorators functionality by other languages?

### ISSUE THREAD

**Issue by izacgaldino23** [getmoto/moto#6450]
Hello guys i'm want to use moto server to test my aws connection (batch in this case). My project is wrote in Java spring boot.

I wont to know if is possible use de decorator **mock_batch_simple** passing env variables or if exists another method to make this.

I'm using docker compose to up the moto server like on the documentation.

**Comment by bblommers** [comment]
Hi @izacgaldino23! If you're running the MotoServer, then the AWS SDK that you use has to set the `endpoint_url` variable.
Normally the SDK will connect to `blah.amazonaws.com`, but overriding the endpoint allows your application to talk to the MotoServer instead.

I'm not aware of a way to set the `endpoint_url` using a environment variable - this will probably have to be set in code.
See our docs: http://docs.getmoto.org/en/latest/docs/server_mode.html#example-usage
And the AWS docs: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html

**Comment by izacgaldino23** [comment]
Hi @bblommers, i think that i can't explain exactly that i want to do.

Now I can connect into moto server perfectly, my objective now is mock a submitjob for a batch. But to do that i need create a role, a compute environment, a jobQueue and a jobDefinition. This is a lot of implementation to run only my project localy. Searching on internet I discovered that moto has a decorator **mock_batch_simple**, now I want to know if is possible simulate this behavior in my Java Spring Boot application using env variables on docker-compose or if exists another method to make this.

**Comment by bblommers** [comment]
Ah, gotcha, I misunderstood. 

The use case for `mock_batch_simple` is to verify the input parameters are correct, so the jobQueue and jobDefinition still have to exist. The difference is that it doesn't execute the actual job, but instead always marks it as `Success`. That makes it a lot quicker, and ensures that people do not have to have Docker installed/running. 
So it doesn't quite do what you're looking for.
