### ISSUE TITLE
The CreateHostedZone response for Route53 does not match the behavior of AWS

### ISSUE THREAD

**Issue by stof** [getmoto/moto#6464]
## Reporting Bugs

I'm using localstack, which implements its route53 mock service using moto.

The `CreateHostedZone` operation returns a response that misses some info compared to an actual AWS response. In particular, it misses the `Location` header, which is where official AWS SDKs are reading the location.

See https://github.com/localstack/localstack/pull/5639#issuecomment-1064527918 for a detailed analysis submitted to localstack a while ago

**Comment by bblommers** [comment]
Thanks for raising this @stof, and welcome to Moto! Marking it as an enhancement to add this field.

It doesn't look like this field is returned anywhere else, in GetHostedZone or ListHostedZones, so we'll just add it to the Create-operation.

**Comment by stof** [comment]
I confirm that the description files used by the official AWS SDKs have this field only for the `CreateHostedZone` operation.
