### ISSUE TITLE
moto[s3] cryptography dependency version

### ISSUE THREAD

**Issue by SiftRonnie** [getmoto/moto#6488]
`pip-audit` labels versions of the `cryptography` package below version 41.0.0 as having a [security vulnerability](https://github.com/advisories/GHSA-5cpq-8wj7-hf2v).  But the hook `pip-compile` reads the requirements of `moto[s3]==4.1.3` and automatically installs a lower versioned `cryptography` package, 40.0.2, which is one version previous to `cryptography 41.0.0`.  When `pip-compile` sees the requirements for `moto[s3]==4.1.3` it is specifies that it requires a version lower than `cryptography 41.0.0` and causes `pip-audit` to fail due to the security vulnerability.  

`requirement=SpecifierRequirement('cryptography<41.0.0,>=3.1.0')`

This is a request to bring `moto[s3]` up to compatibility with the `cryptography` package 41.0.0 that resolves the security vulnerability.

**Comment by bblommers** [comment]
Hi @SiftRonnie, we only have the lower limit for `cryptography`. So I don't know why `pip-compile` installs `40.0.2`, but that's not because of something that we have defined.

https://github.com/getmoto/moto/blob/3ddfc0db40a64621ae91de15c1f5f3841f57846b/setup.cfg#L31

**Comment by SiftRonnie** [comment]
My apologies. The requirement problem is with the other conflicting package. Closing issue.
