### ISSUE TITLE
Scheduler get_schedule Incomplete Response

### ISSUE THREAD

**Issue by raphcodin** [getmoto/moto#6506]
The response of Eventbridge Scheduler get_schedule is missing CreationDate and LastModificationDate. These are both part of the response syntax in the boto3 documentation and are missing. 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/get_schedule.html

The return type of get_schedule in moto is a schedule object, whose parameters can be found at the following link, with the missing parameters CreationDate and LastModificationDate:
https://github.com/getmoto/moto/blob/master/moto/scheduler/models.py#L13C9-L26C33

Version:
Moto 4.1.12

**Comment by bblommers** [comment]
Thanks for raising this @raphcodin, and welcome to Moto! I'll raise a PR soon to add these fields.
