### ISSUE TITLE
RDS start and stop instance sould not works with ARN

### ISSUE THREAD

**Issue by Flemax** [getmoto/moto#6511]
## Reporting Bugs

When I make this code for an AWS Lambda
```
# main.py
import boto3

def lambda_handler(event, context):
    rds = boto3.client('rds', region_name='eu-west-1')
    rds.stop_db_instance(DBInstanceIdentifier="arn:aws:rds:eu-west-1:123456789012:db:mydb")
```
And I test this code with moto
```
# main.test.py
import unittest

import boto3
import main
from moto import mock_rds

@mock_rds
class MainTest(unittest.TestCase):
    def setUp(self):
        rds.create_db_instance(
            DBInstanceIdentifier='test_instance_available',
            DBInstanceClass='db.t2.micro',
            Engine='mysql'
        )

    def test_main_stop(self):
        main.lambda_handler("", "")

        rds = boto3.client("rds", region_name="eu-west-1")
        instance = client_rds.describe_db_instances(DBInstanceIdentifier='test_instance_available')['DBInstances'][0]
        self.assertEqual(instance['DBInstanceStatus'], "stopped")

if __name__ == '__main__':
    unittest.main()
```

When I run this code I expected an error in my test because the instance identifier is an ARN and not a DBInstanceIdentifier

## How to reproduce the issue

Create the two files above and run python on `main.test.py` file

## What you expected to happen

An error when I use a boto3 client for RDS and I call `rds.stop_db_instance(DBInstanceIdentifier="arn:aws:rds:eu-west-1:123456789012:db:mydb")`

## What actuelly happens

No error happens

## What version of Moto you're using

moto==4.1.12
boto3==1.28.2
botocore==1.31.2

**Comment by bblommers** [comment]
Welcome to Moto @Flemax! Marking it as an enhancement to add this validation.

**Comment by rafcio19** [comment]
@bblommers I can take a look
