### ISSUE TITLE
Moto Batch Array Job Missing `arrayProperties` AND no child jobs created

### ISSUE THREAD

**Issue by oliver-helix** [getmoto/moto#6512]
## The issue
`moto` doesn't seem to play well with AWS batch array jobs. The parent job submits just fine, but it doesn't show `arrayProperties` and none of the child jobs are created.

## how to reproduce the issue**
```py
from typing import Iterator

import boto3
import pytest
from moto import mock_batch
from mypy_boto3_batch import BatchClient
from mypy_boto3_batch.type_defs import SubmitJobResponseTypeDef


@pytest.fixture
def batch_client() -> Iterator[BatchClient]:
    with mock_batch():
        yield boto3.client("batch")  # type: ignore


@pytest.fixture
def submit_batch_array_job(batch_client: BatchClient) -> SubmitJobResponseTypeDef:
    return batch_client.submit_job(
        jobName="test-job-name",
        jobDefinition=JOB_DEFINITION_NAME,
        jobQueue=JOB_QUEUE_NAME,
        arrayProperties={"size": 15},  # array properties specified
    )


def test_array_properties(batch_client: BatchClient, submit_batch_array_job: SubmitJobResponseTypeDef) -> None:
    describe_jobs_response = batch_client.describe_jobs(jobs=[submit_batch_array_job["jobId"]])
    assert describe_jobs_response.get("arrayProperties")


def test_child_job_created(batch_client: BatchClient, submit_batch_array_job: SubmitJobResponseTypeDef) -> None:
    child_job_id = f"{submit_batch_array_job['jobId']}:0"
    describe_jobs_response = batch_client.describe_jobs(jobs=[child_job_id])
    assert describe_jobs_response["jobs"]  # fails :-(
```

## what you expected to happen
After submitting a batch array job, I expect:
- the job description should contain an `arrayProperties` attribute which contains the size of the batch array
- child jobs should be created with the format `{jobId}:{batchArrayIndex}`

## what actually happens
After submitting a batch array job:
- the job description does not contain an `arrayProperties` attribute.
- No child jobs are are created with the format `{jobId}:{batchArrayIndex}`

## versions
- moto: `4.1.12`
- botocore: `1.31.2`
- boto3: `1.28.2`
- boto: NA

**Comment by bblommers** [comment]
Hi @oliver-helix, thanks for raising this - marking it as an enhancement to support this property.

**Comment by rafcio19** [comment]
@bblommers I can take a look

**Comment by bblommers** [comment]
Hi @oliver-helix - this feature is now part of moto >= 4.2.6.dev30. Please let us know if you run into any issues.
