### ISSUE TITLE
Persistence on Docker

### ISSUE THREAD

**Issue by leandromonaco** [getmoto/moto#6527]
Is persistence supported when using a Docker volume? If so, how is it configured?

**Comment by bblommers** [comment]
Hi @leandromonaco! 
There is no persistence as such. But you can use the Recorder-feature to log, and later replay, all incoming requests. See the docs here: http://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html

Does that help you?

**Comment by leandromonaco** [comment]
Thanks for the quick reply. I was not aware of that feature, I'll check it out 🙂

**Comment by leandromonaco** [comment]
@bblommers I gave the feature a try using Cognito. I'm getting an error and raise a separate issue for it 

https://github.com/getmoto/moto/issues/6531
