### ISSUE TITLE
Feature request: `ApiGatewayManagementApi` service mock

### ISSUE THREAD

**Issue by ryanblock** [getmoto/moto#6532]
Hey folks! This library is dope, thank you!

Just wanted to put my hat in for `ApiGatewayManagementApi` (aka `apigatewaymanagementapi`) support.

- See: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewaymanagementapi.html
- Sadly I'm not sure it's (fully) documented, but it's stable – as in, it hasn't changed for years. I mocked some key for a non-Python project here, if that's of interest: https://github.com/architect/sandbox/blob/batch/src/arc/_ws/index.js
- Some possibly helpful information here, too: https://github.com/aws/aws-sdk-js/blob/307e82673b48577fce4389e4ce03f95064e8fe0d/apis/apigatewaymanagementapi-2018-11-29.normal.json

Thanks for your consideration!

**Comment by bblommers** [comment]
Hi @ryanblock! Will mark it as an enhancement.

Considering Moto does not support/mock WS requests, so from what I can see now, any implementation will have quite a few limitations:
 - No validation of the ConnectionId
 - No processing of the bytes send by `post_to_connection`
 - Random values for `connectedAt` and `lastActiveAt` - maybe just set to `now()`

**Comment by ryanblock** [comment]
Probably that's ok? At least I think it will be for me, as I'm testing the correct calls are being made to the control plane, not attempting to do full round trip WebSocket client mocking.

**Comment by ryanblock** [comment]
👏🏼👏🏼👏🏼
