### ISSUE TITLE
Issue with ec2 authorize_security_group_egress

### ISSUE THREAD

**Issue by mayk0gan** [getmoto/moto#6538]
## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.
     
Code that reproduces the issue, I've added 4 egress rules but seems like it only saved the last two (the ones with the `PrefixListIds`)
 
```
import boto3
from moto import mock_ec2


@mock_ec2
def test_moto_security_groups():
    ec2 = boto3.client("ec2", region_name="us-east-1")
    ec2
    vpc = ec2.create_vpc(CidrBlock="10.0.0.0/16")
    group = ec2.create_security_group(VpcId=vpc["Vpc"]["VpcId"], GroupName="mototest", Description="mototest")
    sg_before = ec2.describe_security_groups(GroupIds=[group["GroupId"]])
    print(sg_before)

    ec2.authorize_security_group_egress(
        GroupId=group["GroupId"],
        IpPermissions=[
            {"IpProtocol": "tcp", "FromPort": 80, "ToPort": 80, "IpRanges": [{"CidrIp": "10.0.0.0/16"}]},
            {"IpProtocol": "tcp", "FromPort": 443, "ToPort": 443, "IpRanges": [{"CidrIp": "10.0.0.0/16"}]},
            {"IpProtocol": "tcp", "FromPort": 80, "ToPort": 80, "PrefixListIds": [{"PrefixListId": "pl-7dd7ec20"}]},
            {"IpProtocol": "tcp", "FromPort": 443, "ToPort": 443, "PrefixListIds": [{"PrefixListId": "pl-7dd7ec20"}]},
        ],
    )
    sg_after = ec2.describe_security_groups(GroupIds=[group["GroupId"]])
    assert len(sg_before["SecurityGroups"][0]["IpPermissionsEgress"]) + 4 == len(sg_after["SecurityGroups"][0]["IpPermissionsEgress"])
```

   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.
boto3                                   1.26.165
botocore                                1.29.165
moto                                    4.1.12

   If you do not provide all of these things, it will take us much longer to
   fix your problem.

**Comment by bblommers** [comment]
Thanks for raising this @mayk0gan. Looks like we don't correctly parse the `PrefixListIds`, so the last two permissions are somehow treated as duplicates. Marking it as a bug.

**Comment by bblommers** [comment]
I've just ran this example against AWS actually, and the provided test fails there as well. The AWS Console shows 5 `Outbound rules` but boto3 combines them (based on `From Port`, `To Port`, `IP Protocol`), and only returns three rules. 

So as far as I can see, Moto behaves correctly here.
