### ISSUE TITLE
APIGATEWAY UsagePlan

### ISSUE THREAD

**Issue by sethlambdas** [getmoto/moto#6580]
I have notice that the quota limit for usageplan on apigateway is not working.
What I did:
I tried setting the quota/limit to 5
quota/period to DAY OR MONTH
throttle/rateLimit to 1
throttle/burstLimit to 1

But then when I try to execute the endpoint it seems to not honor the limit I set, I can execute the endpoint more than the limit that I set. 

Note:
The api key does work (ticking the require api key on the resource tab).

**Comment by bblommers** [comment]
Hi @sethlambdas! 

Moto does not do anything with the `apiKeyRequired`-attribute - we only mock this. So I'm not sure what this means, or which `resource tab` you're referring to:
> The api key does work (ticking the require api key on the resource tab).
> 

Given that Moto only supports execution of a very limited number of endpoint configurations - did you mean to post this in the LocalStack repo?

**Comment by sethlambdas** [comment]
I'm gonna close this issue as I posted on the wrong repo, thank you.
