### ISSUE TITLE
Inconsistency between moto and boto when DynamoDb Query FilterExpression is empty

### ISSUE THREAD

**Issue by luisabtrace** [getmoto/moto#6599]
I have a conditional DynamoDB `Query` where, depending on the parameters, I may want to pass a `FilterExpression` or not.

Initially I wrote it like this:

```
filter_condition = Attr('permissions').contains('admin') if admins_only else ''
results = table.query(
    KeyConditionExpression=key_condition,
    FilterExpression=filter_condition
)
```

The tests were all fine, but then when I deployed it, the query failed because:

```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Invalid FilterExpression: The expression can not be empty;
```

So I had to rewrite my code as:

```
if admins_only:
    results = table.query(
        KeyConditionExpression=key_condition,
        FilterExpression=Attr('permissions').contains('admin')
    )
else:
    results = table.query(
        KeyConditionExpression=key_condition,
    )
```

I also tried to pass `None` instead of the empty string, but then the tests break in moto.

It would be nice if this inconsistency was resolved in moto, it's not the first time I was hit by this.

Thanks.

**Comment by bblommers** [comment]
Thanks for raising this @luisabtrace - marking it as an enhancement to add this validation.
