### ISSUE TITLE
Support `SM2DSA` signing algorithm for KMS

### ISSUE THREAD

**Issue by tsugumi-sys** [getmoto/moto#6608]
Let's add `SM2DSA` signing algorithm for kms.
KMS document: https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html#API_Sign_RequestSyntax

Supported algorithms:
```
RSASSA_PSS_SHA_256 | RSASSA_PSS_SHA_384 | RSASSA_PSS_SHA_512 | RSASSA_PKCS1_V1_5_SHA_256 | RSASSA_PKCS1_V1_5_SHA_384 | RSASSA_PKCS1_V1_5_SHA_512 | ECDSA_SHA_256 | ECDSA_SHA_384 | ECDSA_SHA_512 | SM2DSA
```

**Comment by tsugumi-sys** [comment]
We can add around here?
https://github.com/getmoto/moto/blob/7a17e0f89d0f36338a29968edf4295558cc745d2/moto/kms/models.py#L166-L183

**Comment by bblommers** [comment]
Hi @tsugumi-sys! Looks like we only need to extend the `signing_algorithms`, yes, considering Moto always uses the same algorithm for the actual signing ([for now](https://github.com/getmoto/moto/issues/5761)).

Do you want to submit a PR for this yourself?

**Comment by tsugumi-sys** [comment]
@bblommers 
Yes, I'll submit PR:)

And I also want to try that issue https://github.com/getmoto/moto/issues/5761
