### ISSUE TITLE
Default RecordDelimiter in select_object_content is a comma while in boto3 it's a newline

### ISSUE THREAD

**Issue by jplauri** [getmoto/moto#6613]
I'm using moto 4.1.12, but the following should still be valid for 4.1.14 (newest at time of writing).

The S3 select_object_content is a recent addition which is said to be experimental: 

http://docs.getmoto.org/en/latest/docs/services/s3.html

The docs also say that the result is always JSON and that FieldDelimiters and RecordDelimiters are ignored. As per the current implementation of moto:

https://github.com/getmoto/moto/blob/master/moto/s3/select_object_content.py#L55

The record delimiter seems to be a comma and there's no way of changing that. In contrast, the default record delimiter in boto3 is a newline character but this can be changed, i.e., _"The value used to separate individual records in the output. If no value is specified, Amazon S3 uses a newline character (’n’)."_

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/select_object_content.html

Should the default behavior for moto and boto3 be consistent here, or is the current behavior intentional?

**Comment by bblommers** [comment]
Hi @jplauri! That's just an oversight, as far as I can tell - marking it as a bug.
