### ISSUE TITLE
S3 Permissions for log delivery - policy or ACL support

### ISSUE THREAD

**Issue by pvditt** [getmoto/moto#6659]
Running moto Version: 4.1.14

**Context**
Writing unit tests for a functions that creates 2 S3 buckets - bucket A and bucket B. Bucket B is used to store the server access logs of bucket A.

When running unit tests using mock_s3 I run into error:
`Result ClientError('An error occurred (InvalidTargetBucketForLogging) when calling the PutBucketLogging operation: You must give the log-delivery group WRITE and READ_ACP permissions to the target bucket`

This occurs due to this [line](https://github.com/getmoto/moto/blob/0520df02c13ca6dae57427fd3c7e9c76925e53e9/moto/s3/models.py#L1213) which checks if an ACL exists to grant access for access log delivery.

Using ACLs to handle access for access logs is not required nor recommended according to [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html). The recommended route is to use bucket polices as opposed to ACLs. My code uses the recommended setup of using the bucket policy to handle access for log delivery with success.

I can update the code in the set_logging function to check if either ACLs or bucket policies have been added to handle server access logging.

**Comment by bblommers** [comment]
Hi @pvditt, thanks for raising this! When this was [first implemented](https://github.com/getmoto/moto/pull/1401), I think that ACL's were still the way to go - but now it would indeed be nice to have support for bucket policies.

> I can update the code in the set_logging function to check if either ACLs or bucket policies have been added to handle server access logging.
>

If you want to open a PR for this, that would be very welcome! Let me know if you need any help.
