### ISSUE TITLE
Missing transaction validation for multiple requests under the same action type

### ISSUE THREAD

**Issue by phekmat** [getmoto/moto#6685]
Similar to https://github.com/getmoto/moto/issues/5496, if you provide multiple `TransactItems` of the same type, moto will pass, but DynamoDB will fail (https://github.com/getmoto/moto/pull/5521 fixed the case where the actions differed).

Contrived modification to the example in the linked issue:
```
TransactItems = [
            {
                "Put": {
                    "Item": {"pk": {"S": 'test'}, "sk": {"S": 'test'}},
                    "TableName": "test_table",
                },
                "Put": {
                    "Key": {"pk": {"S": 'test'}, "sk": {"S": 'test'}},
                    "TableName": "test_table",
                }
            }
        ]
```

DDB will fail with:
```
TransactWriteItems failed: Validation Error: Transaction request cannot include multiple operations on one item
```

**Comment by bblommers** [comment]
Thanks for raising this @phekmat, and welcome to Moto! Marking it as an enhancement to support this validation.

**Comment by rafcio19** [comment]
@bblommers I can take a look

**Comment by rafcio19** [comment]
@phekmat when this code is run against real aws:

```python
import boto3
schema = {
    "KeySchema": [{"AttributeName": "pk", "KeyType": "HASH"}, {'AttributeName': 'sk', 'KeyType': 'RANGE'}],
    "AttributeDefinitions": [{"AttributeName": "pk", "AttributeType": "S"}, {"AttributeName": "sk", "AttributeType": "S"}],
}
dynamodb = boto3.client("dynamodb", region_name="eu-west-1")
table_name = "test-table"
dynamodb.create_table(TableName=table_name, BillingMode="PAY_PER_REQUEST", **schema)

dynamodb.transact_write_items(
            TransactItems=[
                {
                    "Put": {
                        "Item": {"pk": {"S": 'test'}, "sk": {"S": 'test'}},
                        "TableName": table_name,
                    },
                    "Put": {
                        "Key": {"pk": {"S": 'test'}, "sk": {"S": 'test'}},
                        "TableName": table_name,
                    }
                }
            ]
        )
```

it errors:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in TransactItems[0].Put: "Item"
Unknown parameter in TransactItems[0].Put: "Key", must be one of: Item, TableName, ConditionExpression, ExpressionAttributeNames, ExpressionAttributeValues, ReturnValuesOnConditionCheckFailure
```

The same error will be thrown by latest moto, I run this with latest `moto` and `boto3==1.28.33 botocore==1.31.33`

What are your library versions? Can you provide a code snippet that reproduces your issue?

**Comment by phekmat** [comment]
@rafcio19 I'm actually using Pynamo and used the example from the other issue for convenience, but had a typo in the second item (`Key` from the original `Delete`, rather than `Item`, and they should be separate dicts in the list)

I'll try to generate a working example when I get a moment and see if this is down to something deeper in the stack where Pynamo is routing around moto's patching in some cases

**Comment by bblommers** [comment]
I've had a look at this as well, but I can't find any (edge) case where Moto behaves differently from DynamoDB.

I'll close this for now, but feel free to let us know if you have a reproducible example, and we'll reopen.
