### ISSUE TITLE
DynamoDB: special characters in get_item() projection expression not handled correctly

### ISSUE THREAD

**Issue by mvts** [getmoto/moto#6696]
Hi!

I have a nested attribute inside a dynamodb table like so:
````json
{
    "device": {
        "N": "123456"
    },
    "software": {
        "M": {
            "python3.10": {
                "M": {
                    "lorem": {
                        "S": "asdf"
                    },
                    "ipsum": {
                        "S": "asdf"
                    }
                }
            },
            "curl": {
                "M": {
                    "lorem": {
                        "S": "asdf"
                    },
                    "ipsum": {
                        "S": "asdf"
                    }
                }
            }
        }
    }
}
````
Now I want to use the `get_item()` function of a dynamodb resource to only get the data of the "python3.10" entry:

````python
result = table.get_item(
    Key={"device": 123456},
    ProjectionExpression="software.#python3_10",
    ExpressionAttributeNames={"#python3_10": "python3.10"}
)
````
But I only get an empty result set (`Item: {}`).
_It works when I do this via the AWS CLI_. That leads me to believe, that this might be a moto issue. I would be very happy if someone could verify this assumption.

Thanks in advance,
Mats

**Comment by bblommers** [comment]
The Dynamo item has `software`, but the query looks for `packages` - could that be the problem?

Note that I haven't verified this in Moto.

**Comment by mvts** [comment]
> The Dynamo item has `software`, but the query looks for `packages` - could that be the problem?
> 
> Note that I haven't verified this in Moto.

No sorry, that was a mistake by me when I was constructing the example.

**Comment by bblommers** [comment]
Ah, found it. Moto doesn't play nice with attributes that contain a `.` - presumably because it assumes that it should be a map. Marking it as a bug!

**Comment by mvts** [comment]
Alright, thank you so much for the quick reply.
