### ISSUE TITLE
An error occurred (InvalidParameterException) when calling the GetLogEvents operation: 1 validation error detected: Value '5000' at 'limit' failed to satisfy constraint: Member must have value less than or equal to 10000

### ISSUE THREAD

**Issue by bharath-nz** [getmoto/moto#6718]
## Reporting Bugs

How to reproduce the issue?
1. Use boto client for "logs" object (cloudwatch AWS).
2. Use get_log_events or filter_log_events API which accept "limit" as a parameter.
3. The limit parameter in moto/logs/models.py is validated for 10000 limit while in the if condition it is validated against 1000.

What happens because of the issue?
The limit even if I give as 5000 is wrongly showing me an exception as follows
```
E           botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the GetLogEvents operation: 1 validation error detected: Value '5000' at 'limit' failed to satisfy constraint: Member must have value less than or equal to 10000

venv/lib/python3.10/site-packages/botocore/client.py:960: InvalidParameterException
```

Code causing this error:
https://github.com/getmoto/moto/blame/4dc758fd492f116b52b130a2ff93be412a412bae/moto/logs/models.py#L901

The check for limit and the error message in the subsequent line does not match

Moto Version : 4.2.0

**Comment by bblommers** [comment]
Good catch @bharath-nz - thanks for raising and investigating this. Marking it as a bug.

**Comment by bblommers** [comment]
Fixed in https://github.com/getmoto/moto/commit/d351853276c918f0350628bf53f46f9213a2d3dc

`filter_log_events` had the same problem, so that one is fixed as well.
