### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [getmoto/moto#6748]
Is it possible next time on release new version make the github release to have entry on https://github.com/getmoto/moto/releases? 🤔

I'm only asking because on the creation of a new GH release a notification is spread to all those whom have set in the web UI Watch->Releases.

My automation process uses those notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/ESSS/pytest-regressions/commit/bcd06142

**Comment by bblommers** [comment]
Yes, makes sense. Marking it as an enhancement. 

I don't know how easy it is going to be to automatically include a changelog, considering we keep all changes in a single file at the moment - maybe we just include a link to `CHANGELOG.md` itself.

**Comment by kloczek** [comment]
Thank you very much 👍 😄

**Comment by bblommers** [comment]
Done!

https://github.com/getmoto/moto/releases/tag/4.2.2

**Comment by kloczek** [comment]
My automation just processed new release notification😄 
Thank you 👍 😄
