### ISSUE TITLE
Bug: can't call SetIdentityMailFromDomain with Email address

### ISSUE THREAD

**Issue by luoxiaojun1992** [getmoto/moto#6753]
Stack:

localstack 2.2.0 docker image
go 1.21.0
aws-sdk-go-v2

Code:

```
_, err = client.SetIdentityMailFromDomain(ctx, &ses.SetIdentityMailFromDomainInput{
	Identity:            aws.String("test@foo.com"),
	BehaviorOnMXFailure: types.BehaviorOnMXFailureUseDefaultValue,
	MailFromDomain:      aws.String("bar.foo.com"),
})
```

Got error response:
Provided MAIL-FROM domain 'bar.foo.com' is not subdomain of the domain of the identity 'test@foo.com'

Possible related code:
[https://github.com/getmoto/moto/blob/master/moto/ses/models.py#L582](https://github.com/getmoto/moto/blob/master/moto/ses/models.py#L582)

Expected:
Due to the official [document](https://docs.aws.amazon.com/ses/latest/APIReference/API_SetIdentityMailFromDomain.html), the Identity parameter could be Email address.

**Comment by bblommers** [comment]
Thanks for raising this with us @luoxiaojun1992 - will open a PR with a fix shortly.

Welcome to Moto!
