### ISSUE TITLE
Performance issues (and possible memory leak)  when matching requests

### ISSUE THREAD

**Issue by scott-c-h** [getmoto/moto#6763]
## Reporting Bugs

Running moto 4.1.15 on WSL using python 3.11 installed through pip in a virtual environment,  we are seeing performance issues in `CustomRegistry.find()` in `responses_custom_registry.py`. 

It looks like the `all_possibles` variable is accidentally set to a reference of `responses._default_mock._registry.registered` and then every time `extend()` is called (every time a request is made) the amount of possible matches grows.

![image](https://github.com/getmoto/moto/assets/70872135/3e7edbad-a2fa-4fe9-83c0-b7e72f26c409)

**Comment by scott-c-h** [comment]
Forgot to add, WSL guest is Ubuntu 22.04

**Comment by MikeLeePoly** [comment]
@bblommers

**Comment by bblommers** [comment]
Good catch @scott-c-h and @MikeLeePoly!
