### ISSUE TITLE
Tests folder in Lib/site-packages

### ISSUE THREAD

**Issue by merosa20** [getmoto/moto#6768]
Hello,

When installing **moto-4.2.2** using **pip install moto[server]** an extra ``tests/`` folder is present under **venv/Lib/site-packages**.

![image](https://github.com/getmoto/moto/assets/18009024/e8df0366-e0e1-4b2e-a7c6-4621ca96f5ed)

The issue comes from the dependency **py-partiql-parser==0.3.6**. 
https://github.com/getmoto/moto/blob/master/setup.cfg#L69

It seems like a fix is has been released in version 0.3.7.
https://github.com/getmoto/py-partiql-parser/compare/0.3.6...0.3.7

**Comment by bblommers** [comment]
Thanks for raising this @merosa20! Will create a PR for this shortly.
