### ISSUE TITLE
Can I share my contributions on moto in my company tech blog?

### ISSUE THREAD

**Issue by tsugumi-sys** [getmoto/moto#6779]
If I want to publish information about moto contributors on my company's tech blog, etc., do I need to go through any procedures or confirmations?

**Comment by bblommers** [comment]
Hi @tsugumi-sys! What kind of information? If it is all public info, gathered from Github's activity log/profile pages/statistics, than I don't see an issue with it.

**Comment by tsugumi-sys** [comment]
@bblommers 
I see, thanks :) I'm want use the information about the details of contributions (codes,
review comments, e.t.c) and so on.

**Comment by bblommers** [comment]
Ah, right. I don't see an issue with that.

Appreciate the fact that you're checking before hand!
