### ISSUE TITLE
BUG: mock_dynamodb not handling query key conditions correctly

### ISSUE THREAD

**Issue by CrypticCabub** [getmoto/moto#6781]
When making a dynamo query that compares a substituted ExpressionAttributeName against a literal value, moto accepts this comparison with no issue, but real AWS resources reject it as invalid. This allowed a bug in our query logic to get past our test suites before being caught by second stage testing.

example client code:
```
client = boto3.client("dynamodb")
client.query(
      TableName="my_table",
      KeyConditionExpression="#part_key=some_literal_value",
      ExpressionAttributeNames={"#part_key": "type"},
  )
```

Behavior in the real world (moto throws no errors):
```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Invalid condition in KeyConditionExpression: Multiple attribute names used in one condition
```

'correct' code (tested in real-world)
```
client = boto3.client("dynamodb")
client.query(
    TableName="my_table",
    KeyConditionExpression="#part_key=:value",
    ExpressionAttributeNames={"#part_key": "type"},
    ExpressionAttributeValues = {":value": {"S": "foo"}}
)
```

As I understand it, a substituted attribute name can only be compared with a substituted attribute value. it is an illegal input to compare with a literal input. This may be due to the difference between low-level and high-level clients (https://aws.amazon.com/blogs/database/exploring-amazon-dynamodb-sdk-clients/) but I am not familiar enough with the dynamo apis to know for sure:

full repro example:
```
with mock_dynamodb():
    client = boto3.client("dynamodb", region_name="us-east-1")
    client.create_table(
        AttributeDefinitions=[
            {"AttributeName": "name", "AttributeType": "S"},
            {"AttributeName": "type", "AttributeType": "S"},
        ],
        TableName="my_table",
        KeySchema=[
            {"AttributeName": "type", "KeyType": "HASH"},
            {"AttributeName": "name", "KeyType": "RANGE"},
        ],
        BillingMode="PAY_PER_REQUEST",
    )

    client.query(
        TableName="my_table",
        KeyConditionExpression="#part_key=some_value",
        ExpressionAttributeNames={"#part_key": "type"},
    )
```

**Comment by bblommers** [comment]
Thanks for raising this @CrypticCabub! Marking it as a bug.
