### ISSUE TITLE
Feature Request: Support for "key" and "value" filters in autoscaling describe_tags calls

### ISSUE THREAD

**Issue by pdpol** [getmoto/moto#6787]
I'm on Moto 4.2.2. I saw [this comment](https://github.com/getmoto/moto/blob/master/moto/autoscaling/models.py#L1561) in the code that confirmed the behavior I'm seeing when I try to filter by `key` or `value` in an autoscaling service `describe_tags` call. I can provide a working code sample if necessary but figured since this missing functionality is already commented on that you're all probably aware. Wondering if there's potential to see this addressed, or if a PR would be welcome?

**Comment by bblommers** [comment]
Hi @pdpol, PR's are always welcome! Just let us know if you need any help/pointers for this feature.
