### ISSUE TITLE
Unable to use Moto and DynamoDB Local 2.0 simultaneously

### ISSUE THREAD

**Issue by jvuori** [getmoto/moto#6805]
Somewhat related to https://github.com/getmoto/moto/issues/2058

When using DynamoDB 2.0 or newer: "The updated convention specifies that the AWS_ACCESS_KEY_ID can only contain letters (A–Z, a–z) and numbers (0–9)" (https://repost.aws/articles/ARc4hEkF9CRgOrw8kSMe6CwQ/troubleshooting-the-access-key-id-or-security-token-is-invalid-error-after-upgrading-dynamodb-local-to-version-2-0-0-1-23-0-or-greater)

Now, if Moto is used for mocking any other AWS API but the (integration) test harness uses "real" DynamoDB Local, boto3 throws an exception:
```
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the Get operation: The Access Key ID or security token is invalid.
```

This is because Moto uses the following access key configuration in BaseMockAWS constructor:
```python
        self.FAKE_KEYS = {
            "AWS_ACCESS_KEY_ID": "foobar_key",
            "AWS_SECRET_ACCESS_KEY": "foobar_secret",
        }
```

Anything without underscore seems to resolve the issue. For example:
```python
"AWS_ACCESS_KEY_ID": "dummy"
```

This can be reproduced with running DynamoDB Local 2.0 and trying to query basically anything against it with the following test application:
```python
import boto3

from moto import mock_ssm

with mock_ssm():
    dynamodb_resource = boto3.resource(
        "dynamodb",
        endpoint_url="http://localhost:19802",
    )
    table = dynamodb_resource.Table("MyTable")

    table.get_item(
        Key={
            "PK": "1",
            "SK": "1",
        }
    )
    # botocore.exceptions.ClientError:
    # An error occurred (UnrecognizedClientException) when calling the
    # GetItem operation: The Access Key ID or security token is invalid.
```

Versions:
moto==4.2.2
boto3==1.28.44
botocore==1.31.44

**Comment by bblommers** [comment]
Thanks for raising this @jvuori. I don't expect anyone to rely on those specific values, so I'm happy to change them to adhere to AWS' guidelines.
