### ISSUE TITLE
`generate_presigned_url()` doesn't include `X-Amz-Date`

### ISSUE THREAD

**Issue by AdrianB-sovo** [getmoto/moto#6819]
I'm using moto v4.0.7, running under WSL2.

### Problem
When I do:

```python
url = self._s3_client.generate_presigned_url(
            ClientMethod="get_object",
            Params={"Bucket": s3_bucket_name, "Key": s3_file_path},
            ExpiresIn=86400,
        )
```

I receive something like: 
`'https://test-presign.s3.amazonaws.com/test1.txt?AWSAccessKeyId=foobar_key&Signature=ABCq08BCBaJ5ttX%2FBRzYnzXCp4Z%3D&Expires=1694902449'`

But, I would expect something like: 
`'https://test-presign.s3.amazonaws.com/test1.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&[...]&X-Amz-Date=20230907T153927Z[...]'`

The URL is missing the `X-Amz-` query parameters.
For example: `X-Amz-Date` and `X-Amz-Expires` can be used to calculate the expiration datetime.

**Comment by bblommers** [comment]
Hi @AdrianB-sovo, Moto doesn't mock this method - that's just `boto3` doing it's thing.

When I execute the provided code without any any mock active, I get the same result as what you're seeing.

**Comment by AdrianB-sovo** [comment]
So, maybe it should be mocked to reproduce what would usually be seen in prod?

**Comment by bblommers** [comment]
If you have something reproducible, I'd be happy to have a look - until then I'll just close this.

**Comment by AdrianB-sovo** [comment]
You're right, it's boto3.

For anyone encountering the same problem, I'll describe what happens.

### What I did locally, which generated the URL with values that I did not expect
- On WSL, I login with SSO:
`aws sso login --profile my_profile`

- I execute the following code:
```python
import boto3

session = boto3.Session(profile_name="my_profile")
s3 = session.client("s3")

url = s3.generate_presigned_url(
    ClientMethod="get_object",
    Params={"Bucket": "my_bucket", "Key": "/some_test.txt"},
    ExpiresIn=86400,
)

print(url)
```
Generated something like:
`https://s3.eu-west-1.amazonaws.com/my_bucket//some_test.txt?AWSAccessKeyId=A[...]P&Signature=T[...]D&x-amz-security-token=I[...]%3D&Expires=1696106620`

Which didn't match what was generated once deployed in my Lambdas.

### How to get the URL I'm looking for with boto3/moto
The problem seems that boto3 doesn't automatically select the AWS v4 signature this way, contrary to when it was running on Lambda (maybe due to a different default region?).
To have the expected behaviour with v4 signatures, the client can be created this way:
```python
s3 = session.client("s3", config=Config(signature_version='s3v4'))
```
