### ISSUE TITLE
IAM list_groups method didn't return "CreateDate" field

### ISSUE THREAD

**Issue by MacHu-GWU** [getmoto/moto#6843]
It is very simple:

based on [iam_client.list_groups() AWS Document](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam/paginator/ListGroups.html), it should returns a field ``CreateDate``.

I think you already implemented this attribute [See this source code](https://github.com/getmoto/moto/blob/master/moto/iam/models.py#L1210), but in your [response template](https://github.com/getmoto/moto/blob/master/moto/iam/responses.py#L1759), you forget to add this.

I think it is a very easy fix.

I checked list_users, list_roles, list_policies, all of them are working fine.

**Comment by bblommers** [comment]
Thanks for letting us know @MacHu-GWU - I've raised a PR with a fix.
