### ISSUE TITLE
gluet.get_tables() method should return catalog id, which is the 123456789012, the fake AWS Account Id

### ISSUE THREAD

**Issue by MacHu-GWU** [getmoto/moto#6861]
Based on [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/get_tables.html) document, ``glue.get_tables()`` should return ``{"Name": "table_name", "DatabaseName": "database_name", "CatalogId": "AwsAccountId", more attributes here}``

However moto doesn't returns catalog id, which is a very important component for unique id / arn.

I checked the source code the [FakeDatabase](https://github.com/getmoto/moto/blob/master/moto/glue/models.py#L1043) and the [FakeTable](https://github.com/getmoto/moto/blob/master/moto/glue/models.py#L1065) implementation are not correct, they should take a ``catalog_id`` argument, which is AWS Account Id of this account. The catalog id is designed for sharing glue table across account. You can find more information about catalog id in this [RePost](https://repost.aws/questions/QUWxpW7KY7RsCj2ttURvb7jQ/get-glue-data-catalog-name-id)

Here's my suggestion how to fix it:

1. first, go to fake database and fake table data class add catalog_id attribute.
2. second, go to [create_database](https://github.com/getmoto/moto/blob/master/moto/glue/models.py#L128) and [create_table](create_table) method, since the ``self`` is the ``Backend`` object, it has an attribute ``account_id``, just pass it to the dataclass.
3. third, check the get_database / get_databases / get_table / get_tables method, see if you return the catalog_id propertly.

Thank you for the awesome project

**Comment by bblommers** [comment]
Thanks for raising this @MacHu-GWU - I'll have a PR ready shortly that fixes this.
