### ISSUE TITLE
AssertionError with SES Templates containing {{#if}} inside {{#each}}

### ISSUE THREAD

**Issue by spatsatzis** [getmoto/moto#6862]
Hello team,

This issue is identical to https://github.com/getmoto/moto/issues/6206 however this is happening when you have an {{#if}}...{{/if}} inside an {{#each}}.

Example Template:

`{{#each items}} {{some_variable}} {{#if some_other_var}} print me {{/if}} {{/each}}`

Starts here https://github.com/getmoto/moto/blob/master/moto/ses/template.py#L42 and this is triggering it https://github.com/getmoto/moto/blob/master/moto/ses/template.py#L26

thanks!

**Comment by bblommers** [comment]
Thanks for raising this @spatsatzis, and welcome to Moto! I'll submit a PR with support for this use-case in a bit.

**Comment by spatsatzis** [comment]
oh wow, this is impressive. thanks for looking at this so fast, appreciated. have a nice day.
