### ISSUE TITLE
TotalStorageCapacityInMegaBytes missing from redshift.describe_clusters()

### ISSUE THREAD

**Issue by mayk0gan** [getmoto/moto#6865]
## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.
    
Use `@mock_redshift`, and call `boto3_client.describe_clusters()`.
`TotalStorageCapacityInMegaBytes` will be missing from the response.
   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?
`TotalStorageCapacityInMegaBytes` should appear in the response 
![image](https://github.com/getmoto/moto/assets/96263702/949749c9-56f3-4cc1-8532-b191630d49f5)
https://docs.aws.amazon.com/cli/latest/reference/redshift/describe-clusters.html

   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?
   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.

Python 3.9.18
boto3                               1.26.165
boto3-stubs                         1.28.51
botocore                            1.29.165
botocore-stubs                      1.29.165
moto                                4.2.0

   If you do not provide all of these things, it will take us much longer to
   fix your problem.

**Comment by bblommers** [comment]
Hi @mayk0gan! Marking it as an enhancement to add this field.

Considering we don't store any actual data for redshift, we'll probably just always return `0` here.
