### ISSUE TITLE
Feature idea: assert Eventbridge/events Detail field is a dict

### ISSUE THREAD

**Issue by jhw** [getmoto/moto#6874]
This one trips me up the entire time

Eventbridge/events Detail field is required by AWS to be a JSON object (Python dict)

I accidentally send it JSON lists all the time

Production Eventbridge just silently ignores them, leading to mucho head scratching and frustration

Moto events seems to silently allow list sending also

It would be great if moto events could raise a warning/exception on encountering a Detail in list form!

Just a thought

**Comment by bblommers** [comment]
Generally we want to behave exactly like AWS - but in this case I understand that some sort of notification can be helpful. I'll create a PR soon to raise a warning when supplying anything else than a dict.

**Comment by jhw** [comment]
I should have added that the method in question is `events.put_events`
