### ISSUE TITLE
EC2 run instances placement host id is not supported?

### ISSUE THREAD

**Issue by romanilchyshynb** [getmoto/moto#6878]
I'm checking to make sure that the system is suitable for my use case (version `4.2.5`).

My case is to run aws equivalent:
```
aws ec2 run-instances --image-id ami-0e373a2446example --instance-type m5.large --placement HostId=h-0b1b80b286example --subnet-id subnet-3862e0ex
```
The crucial here is `--placement HostId=h-0b1b80b286example` - I need created instance to have placement with specified host id.

Am I right that `add_instances` doesn't implement such placement functionality? Or maybe I miss something? 
https://github.com/getmoto/moto/blob/60fd1a5cf2eb1c1c7f8c7bbd0a81c13c5797f3ac/moto/ec2/models/instances.py#L624
Also, Is it hard to add it?

**Comment by bblommers** [comment]
Hi @romanilchyshynb, that attribute is indeed not supported at the moment.

> Also, Is it hard to add it?

That depends - what is your usecase? If you just want the attribute to show up in the `run_instances`/`describe_instances`-response, that should be easy.

**Comment by romanilchyshynb** [comment]
Thanks for quick response!
I'll try to persist placement host id and make it work. But not sure will be able to provide suitable PR as I am too far from Python.
