### ISSUE TITLE
Inspector2 support

### ISSUE THREAD

**Issue by volphy** [getmoto/moto#6887]
Is Inspector2 support planned?

It would allow mocking ECR Enhanced Scan (powered by Amazon Inspector).

**Comment by bblommers** [comment]
Hi @volphy, I'll mark it as an enhancement. Which methods do you need, specifically?

**Comment by volphy** [comment]
My Lambda functions that I would like to test required the following IAM actions:

- inspector2:ListFilters
- inspector2:CreateFilter
- inspector2:TagResource
- inspector2:DeleteFilter
- inspector2:ListFindings

There is also one more IAM action from ECR required:
- ecr:BatchGetRepositoryScanningConfiguration

**Comment by bblommers** [comment]
The `inspector2`-service is now part of moto >= 4.2.7.dev9.

The `list_findings`-method returns 0 results by default, but you can configure a custom response - see the documentation here: 
http://docs.getmoto.org/en/latest/docs/services/inspector2.html

Please let us know if you run into any issues.
