### ISSUE TITLE
Full ECR coverage

### ISSUE THREAD

**Issue by volphy** [getmoto/moto#6888]
Is full coverage of ECR planned?

As of now mocking any workflow that involves docker push to an ECR private repository is not supported.

**Comment by bblommers** [comment]
Hi @volphy, Moto's main goal is to mock the SDK's - implementing the Docker protocol is out of scope as far as I'm concerned. 

I would happily look at PR's that implement the [ECR-methods that we have not yet implemented](http://docs.getmoto.org/en/latest/docs/services/ecr.html), but as far as I can tell, that doesn't solve your problem - as `docker push` calls a different API.

**Comment by bblommers** [comment]
ECR has the `put_image` API, which is implemented by Moto. So you could use that as part of the test setup to create some images, that will then be returned by `describe_images`.
See our internal test here: 

https://github.com/getmoto/moto/blob/90fec47f5f9275200a0b659ea659234a3146a2db/tests/test_ecr/test_ecr_boto3.py#L247

**Comment by volphy** [comment]
Thanks for detailed answer.

I hoped that there would be an easier way but I understand your point.
