### ISSUE TITLE
EC2 run instances with --iam-instance-profile strange error

### ISSUE THREAD

**Issue by romanilchyshynb** [getmoto/moto#6902]
I encounter strange behavior with `aws ec2 run-instances` which includes `--iam-instance-profile` flag.
With simple
```
aws ec2 run-instances --image-id ami-example1234567890
```

it works fine, instance is created. I get 200 response in log:
```
192.168.1.1 - - [11/Oct/2023 11:52:26] "POST / HTTP/1.1" 200 -
```

In case I include `--iam-instance-profile` flag like:
```
aws ec2 run-instances --image-id ami-example1234567890 --iam-instance-profile Name="arn:aws:iam::123456789012:instance-profile/admin-role"
```
or any `Name` content like:
```
aws ec2 run-instances --image-id ami-example1234567890 --iam-instance-profile Name="test"
```

I get error `An error occurred (NoSuchEntity) when calling the RunInstances operation: Instance profile arn:aws:iam::123456789012:instance-profile/admin-role not found`. 

With log:
```
192.168.65.1 - - [11/Oct/2023 11:52:39] "POST / HTTP/1.1" 404 -
```

But even with 404 error new instance is created.
I'm not against creating instance without validating such rare flag, but it fails to return correct 200 response.

I use docker image with version `4.2.5`.
All aws client commands I run against container like:
```
aws --endpoint-url=http://localhost:5000 ec2 run-instances
```

**Comment by bblommers** [comment]
Thanks for raising this @romanilchyshynb - that's a bug indeed. I'll submit a PR shortly to make sure this validation occurs before actually creating the instance.
