### ISSUE TITLE
EC2: Add support for hibernation APIs in `describe_instances`

### ISSUE THREAD

**Issue by ericrafalovsky** [getmoto/moto#6903]
This is feature request expands on https://github.com/getmoto/moto/issues/5336. While `HibernationOptions` are supported in many AWS APIs, the other one where it would be valuable to add support is [describe_instances](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_instances.html#describe-instances).

**Comment by bblommers** [comment]
I've opened #6906 to fix this.

**Comment by ericrafalovsky** [comment]
Amazing 🤩
