### ISSUE TITLE
add support to ec2 describe-key-pairs with filters

### ISSUE THREAD

**Issue by inventvenkat** [getmoto/moto#6907]
### Overview
Implement support for describe_key_pairs with filter option.

### Steps to reproduce
```shell
awslocal ec2 describe-key-pairs --region us-east-2 --filters "Name=tag:ManagedBy,Values=hyperswitch"
```
following is the error
```shell
An error occurred (InternalFailure) when calling the DescribeKeyPairs operation: The filter 'tag:ManagedBy' for DescribeKeyPairs has not been implemented in Moto yet. Feel free to open an issue at https://github.com/getmoto/moto/issues
```

**Comment by bblommers** [comment]
Hi @inventvenkat, that filter isn't supported by AWS either, as far as I can tell? 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_key_pairs.html only lists `key-pair-id`, `fingerprint`, `key_name`, `tag-key` and `tag`.

**Comment by inventvenkat** [comment]
> Hi @inventvenkat, that filter isn't supported by AWS either, as far as I can tell?
> 
> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_key_pairs.html only lists `key-pair-id`, `fingerprint`, `key-name`, `tag-key` and `tag`.
> 
> Edit: We have internal tests for the `fingerprint` and `key-name` filters, so those are already supported.

Hi @bblommers , i missed writing tag while creating the issue. edited it now
