### ISSUE TITLE
mock_sqs's create_queue is missing "sqs" in its url

### ISSUE THREAD

**Issue by Lemorra** [getmoto/moto#6908]
Hi,

I'm trying to use the `moto` library to mock sqs functionality to write test cases for code that uses the sqs features. What I have noticed is that the `create_queue` method of the sqs client is creating the wrong url. Below is a sample code that can be used to reproduce the issue:

```python
import boto3
from moto import mock_sqs

@mock_sqs
def create_sqs_url():
    sqs_client = boto3.client(
        "sqs",
        region_name = "me-south-1"
    )

    queue_instance = sqs_client.create_queue(QueueName='test-queue')
    print(f"queue_instance: {queue_instance}")
    queue_url = queue_instance["QueueUrl"]
    print(f"queue_url : {queue_url}")

create_sqs_url()
```
Version of libraries used are as follows:
```bash
Package            Version
------------------ ---------
boto3              1.20.31
botocore           1.23.54
certifi            2023.7.22
cffi               1.16.0
charset-normalizer 3.3.0
cryptography       41.0.4
idna               3.4
Jinja2             3.1.2
jmespath           0.10.0
MarkupSafe         2.1.3
moto               4.2.5
pip                23.2.1
pycparser          2.21
python-dateutil    2.8.2
PyYAML             6.0.1
requests           2.31.0
responses          0.23.3
s3transfer         0.5.2
setuptools         68.2.2
six                1.16.0
types-PyYAML       6.0.12.12
urllib3            1.26.17
Werkzeug           3.0.0
wheel              0.41.2
xmltodict          0.13.0
```
Python version used here is 3.8 ( Using anaconda environment on Ubuntu 22.04.3 MATE 1.26.0)

Received output
```bash
queue_instance: {'QueueUrl': 'https://me-south-1.queue.amazonaws.com/123456789012/test-queue', 'ResponseMetadata': {'RequestId': 'RKDFh79QCjWDyM0B5WkMsQK2RpTBqiFjJChA0WUOqOXv9JUC5HJa', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'date': 'Fri, 13 Oct 2023 17:09:40 GMT', 'x-amzn-requestid': 'RKDFh79QCjWDyM0B5WkMsQK2RpTBqiFjJChA0WUOqOXv9JUC5HJa', 'x-amz-crc32': '2313260786'}, 'RetryAttempts': 0}}
queue_url : https://me-south-1.queue.amazonaws.com/123456789012/test-queue
```
Expected
`queue_url` should start with `https://sqs.`

I just wanted to know if this is intended or is there something wrong in my code or the wrong libraries are being used with the `moto` library.

**Comment by bblommers** [comment]
Hi @Lemorra, that behaviour is dependent on which version of `botocore`/`boto3` you use. If you upgrade both to the most recent version, it will show `https://sqs.me-south-`.....`.

Note that this is not dependent on Moto - we just intercept everything that's send to `*.queue.amazonaws.com`, and mirror whatever URL `botocore` uses. It looks like that `botocore` has changed the URL endpoint at some point.

**Comment by Lemorra** [comment]
Hi @bblommers, apologies for the late reply. Yes, after upgrading I'm able to get the proper url. Thanks!
