### ISSUE TITLE
Replace pytest-ordering with pytest-order

### ISSUE THREAD

**Issue by mweinelt** [getmoto/moto#6937]
The [pytest-ordering](https://github.com/ftobia/pytest-ordering) package is unmaintained, and its test suite is broken on recent python versions. The project recommends migrating over to [pytest-order](https://github.com/pytest-dev/pytest-order), a fork that is still maintained.

https://pytest-dev.github.io/pytest-order/stable/intro.html#relationship-with-pytest-ordering

Having working ordering of the tests is important, to run them quickly. Without ordering, we see a number of tests failing with

> botocore.exceptions.NoCredentialsError: Unable to locate credentials

In nixpkgs we cannot provide pytest-ordering any longer. Gentoo seems also affected, since they [serialize](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/moto/moto-4.2.6.ebuild#n105) these parts of the test suite.

**Comment by bblommers** [comment]
Thanks for letting us know @mweinelt  - I wasn't aware the project was unmaintained. I'll raise a PR shortly to change to `pytest-order`.
