### ISSUE TITLE
Batch client should return jobArn on submit_job

### ISSUE THREAD

**Issue by KidAmnesiac1** [getmoto/moto#6940]
Looks like jobArn isn't being returned by the batch client after calling submit_job

I believe it should per the [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch/client/submit_job.html) and [AWS API docs](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html). I may be confused though, since the docs also show without jobArn.

Looks like the return structure is set [here](https://github.com/getmoto/moto/blob/master/moto/batch/models.py#L1792) and can get the ARN from job.arn

**Comment by bblommers** [comment]
Thanks for raising this @KidAmnesiac1, and welcome to Moto! I'll submit a PR for this shortly.
