### ISSUE TITLE
`dynamodb.Table(...).get_item(...)` returns items when the sort key is different

### ISSUE THREAD

**Issue by magicmark** [getmoto/moto#6973]
Using `moto==4.2.7`, this fails:

```python
def test_yikes(dynamodb):
    dynamodb.Table("meal-orders").put_item(
        Item={
            "customer": "mark",
            "mealtime": "breakfast",
        }
    )

    assert 'Item' not in dynamodb.Table("meal-orders").get_item(
        Key={
            "customer": "mark",
            "mealtime": "lunch",
        }
    )
```

^ `get_item` happily fetches my `breakfast` row, even though i asked for `lunch` - and so the test fails.

**I verified this test passes when I change to `moto==3.1.18` so this appears to be a behaviour introduced between the two versions.**

<details>
<summary>full test file</summary>

```python
import pytest
import boto3
import moto

@pytest.fixture(autouse=True, scope="function")
def dynamodb():
    with moto.mock_dynamodb():
        dynamodb = boto3.resource("dynamodb", region_name="us-east-1")
        dynamodb.create_table(
            TableName="meal-orders",
            KeySchema=[
                {"AttributeName": "customer", "KeyType": "HASH"},
                {"AttributeName": "mealtime", "KeyType": "SORT"},
            ],
            AttributeDefinitions=[
                {"AttributeName": "customer", "AttributeType": "S"},
                {"AttributeName": "mealtime", "AttributeType": "S"},
            ],
            ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
        )
        yield dynamodb


def test_yikes(dynamodb):
    dynamodb.Table("meal-orders").put_item(
        Item={
            "customer": "mark",
            "mealtime": "breakfast",
        }
    )

    assert 'Item' not in dynamodb.Table("meal-orders").get_item(
        Key={
            "customer": "mark",
            "mealtime": "lunch",
        }
    )
```
</details>

Runnable repro here: https://github.com/magicmark/moto-issue-2/

I was worried my understanding of things is incorrect, but per https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html:

> Partition key and sort key – Referred to as a composite primary key, this type of key is composed of two attributes. The first attribute is the partition key, and the second attribute is the sort key.

thanks!

**Comment by bblommers** [comment]
Hey @magicmark, the key-types should be `HASH` and `RANGE` - not `SORT`. Moto does work as it should when you change it to:

```
KeySchema=[
    {"AttributeName": "customer", "KeyType": "HASH"},
    {"AttributeName": "mealtime", "KeyType": "RANGE"},
]
```

I'll mark this as an enhancement to add some validation here. Looks like AWS throws the following exception:
```
An error occurred (ValidationException) when calling the CreateTable operation: 1 validation error detected: Value 'SORT' at 'keySchema.2.member.keyType' failed to satisfy constraint: Member must satisfy enum value set: [HASH, RANGE]
```

**Comment by magicmark** [comment]
ah thanks! wonder how this ever worked in v3 then?

**Comment by bblommers** [comment]
IIRC that was changed in [this PR](https://github.com/getmoto/moto/pull/5919/files). 

Moto would always assume that the second Attribute was the Range-value, without actually checking what the value was.
