### ISSUE TITLE
Compatibility issue  moto[4.1.6] with boto3[1.28.81/1.28.82]

### ISSUE THREAD

**Issue by vladislavkoz** [getmoto/moto#7005]
moto==4.1.6
boto3==1.28.81/1.28.82

sqs = boto3.resource("sqs")
queue = sqs.get_queue_by_name(QueueName=queue_name)

queue - is empty dict - {}

Is it expected?

**Comment by gtmanfred** [comment]
i also ran into this issue.

**Comment by gtmanfred** [comment]
looks like this works with the latest version of moto.

**Comment by bblommers** [comment]
I haven't looked into this yet, but I'm assuming that is related to #6286

Does an upgrade to Moto >= 4.1.11.dev7 fix the problem?

**Comment by vladislavkoz** [comment]
Yes, I have fixed my issues with the latest version of moto

**Comment by bblommers** [comment]
Thanks for confirming @vladislavkoz. I'll close this then, but let us know if you run into any other issues.
