### ISSUE TITLE
AllocationTime is not presented in result of describe_hosts

### ISSUE THREAD

**Issue by dmtrhbtrs** [getmoto/moto#7008]
## Issue
In latest version of moto (and probably older ones too) `describe_hosts` function does not return AllocationTime.
From moto perspective it can be something like `date.now` when dedicated hoist being created so it can be returned when describe host being called

**Comment by bblommers** [comment]
Thanks for raising this @dmtrhbtrs, and welcome to Moto!

Marking it as an enhancement to add this property.
