### ISSUE TITLE
put_public_access_block marked as unimplemented for s3

### ISSUE THREAD

**Issue by bemoody** [getmoto/moto#7034]
In http://docs.getmoto.org/en/latest/docs/services/s3.html, `put_public_access_block` is marked as unimplemented.  `get_public_access_block` and `delete_public_access_block` are marked as implemented.

I notice that all three are marked as implemented for `s3control`.  (If I understand correctly, `S3Control.Client.put_public_access_block` is for setting *account-wide* restrictions, whereas `S3.Client.put_public_access_block` is for *per-bucket* restrictions.)

According to CHANGELOG.md, all three methods were implemented for both `s3` and `s3control` in version 1.3.16.

**Comment by bblommers** [comment]
Good catch @bemoody - I'll raise a PR for this shortly
