### ISSUE TITLE
Dynamodb query with a KeyConditionExpression should raise ClientError when the partition key is empty

### ISSUE THREAD

**Issue by LiamCato** [getmoto/moto#7062]
Moto Version: 4.2.9

In an almost identical situation to https://github.com/getmoto/moto/issues/5345, which was about this issue when using `get_item`, when using `query` instead with a KeyConditionExpression the same case can occur.

```
from boto3 import resource
from boto3.dynamodb.conditions import Attr, ConditionBase, Key

table = resource("dynamodb").Table("my_table")
table.query(KeyConditionExpression=Key("PK").eq(""))
```

should cause `botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value. Key: PK`

Instead with moto it just returns the query as normal with no results.

**Comment by bblommers** [comment]
Thanks for letting us know @LiamCato - I'll raise a PR for this shortly.
