### ISSUE TITLE
BUG: Create sagemaker.create_model_pacakge requires ModelPackageName

### ISSUE THREAD

**Issue by dylan-anson** [getmoto/moto#7098]
# Problem 
When calling sagemaker_client.create_model_package() moto assumes that ModelPackageName is a str.
The problem is that this assumption is invalid as sagemaker says, if the ModelPackageGroupName is present then the ModelPackageName is not used and not required as the model_package becomes versioned.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_model_package.html#create-model-package

# Suggested fix
In the `create_model_package` method in `moto/sagemaker/models.py` we need to handle if the `model_package_name` is None when passed into the `ModelPackage` model 
The culprit is here 
```python
 model_package_arn = arn_formatter(
            region_name=region_name,
            account_id=account_id,
            _type="model-package",
            _id=f"{model_package_name.lower()}/{model_package_version}"
            if model_package_version
            else model_package_name.lower(),
        )
```
The `_id` field tries to call `.lower()` on a potentially None value.
Check for None and then change the `_id` accordingly. 

# Error
Calling create model package using the following
```python
response = self.client.create_model_package(
    ModelPackageGroupName=model_group_name,
    ModelPackageDescription=description,
    InferenceSpecification={
        "Containers": [
            {
                "Image": image_uri,
                "ModelDataUrl": model_data_uri,
            }
        ],
        "SupportedTransformInstanceTypes": transform_instances,
        "SupportedRealtimeInferenceInstanceTypes": inference_instances,
        "SupportedContentTypes": content_types,
        "SupportedResponseMIMETypes": response_types,
    },
    ModelApprovalStatus=approval_status,
    CustomerMetadataProperties=metadata,
)
```
will cause the following error

```python
    def __init__(
        self,
        model_package_name: str,
        model_package_group_name: Optional[str],
        model_package_version: Optional[int],
        model_package_description: Optional[str],
        inference_specification: Any,
        source_algorithm_specification: Any,
        validation_specification: Any,
        certify_for_marketplace: bool,
        model_approval_status: Optional[str],
        metadata_properties: Any,
        model_metrics: Any,
        approval_description: Optional[str],
        customer_metadata_properties: Any,
        drift_check_baselines: Any,
        domain: str,
        task: str,
        sample_payload_url: str,
        additional_inference_specifications: List[Any],
        client_token: str,
        region_name: str,
        account_id: str,
        tags: Optional[List[Dict[str, str]]] = None,
    ) -> None:
        fake_user_profile_name = "fake-user-profile-name"
        fake_domain_id = "fake-domain-id"
        fake_user_profile_arn = arn_formatter(
            _type="user-profile",
            _id=f"{fake_domain_id}/{fake_user_profile_name}",
            account_id=account_id,
            region_name=region_name,
        )
        model_package_arn = arn_formatter(
            region_name=region_name,
            account_id=account_id,
            _type="model-package",
            _id=f"{model_package_name.lower()}/{model_package_version}"
>           if model_package_version
            else model_package_name.lower(),
        )
E       AttributeError: 'NoneType' object has no attribute 'lower'

.testenv/lib/python3.7/site-packages/moto/sagemaker/models.py:1022: AttributeError
```

If you need me to make a PR I can give it a go, let me know thanks :)

**Comment by bblommers** [comment]
Hi @dylan-anson, thanks for raising this. A PR would be very welcome!

Just out of interest - how does AWS behave if you don't supply the `model_package_name`? Does it assign a randomized name?

**Comment by dylan-anson** [comment]
> Hi @dylan-anson, thanks for raising this. A PR would be very welcome!
> 
> Just out of interest - how does AWS behave if you don't supply the `model_package_name`? Does it assign a randomized name?

The name is just an iteration of versions, first model created is 1 and then just iterates by 1.

**Comment by dylan-anson** [comment]
Another issue found was that it doesn't validate properly either. Sagemaker expects either ModelPackageName or ModelPackageGroupName, meaning if both are provided should through an error, however this doesn't happen, I will include this in the PR also.
