### ISSUE TITLE
How to find which versions of moto use which versions of GLIBC?

### ISSUE THREAD

**Issue by jhw** [getmoto/moto#7101]
I want to install moto as part of an AWS Lambda layer (python 3.10) but am having problems -

```
 File \"/opt/python/moto/s3/responses.py\", line 290, in bucket_response
 self.setup_class(request, full_url, headers, use_raw_body=True)
 File \"/opt/python/moto/core/responses.py\", line 386, in setup_class
 from moto.iam.models import mark_account_as_visited
 File \"/opt/python/moto/iam/__init__.py\", line 2, in <module>
 from .models import iam_backends
 File \"/opt/python/moto/iam/models.py\", line 11, in <module>
 from cryptography import x509
 File \"/opt/python/cryptography/x509/__init__.py\", line 7, in <module>
 from cryptography.x509 import certificate_transparency
 File \"/opt/python/cryptography/x509/certificate_transparency.py\", line 11, in <module>
 from cryptography.hazmat.bindings._rust import x509 as rust_x509
 ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/python/cryptography/hazmat/bindings/_rust.abi3.so
```

It seems that GLIBC_2.28 required by the (latest) version of moto I am using isn't compatible with whatever GLIBC version the AWS Lambda python 3.10 image is using

I think I can find the latter fairly easily, but how can I find which versions of moto use which versions of GLIBC, so that I can find a moto version which is compatible with my Lambda image?

TIA

**Comment by jhw** [comment]
AWS Lambda python 3.10 image runs Amazon Linux 2 which supports glibc 2.26

**Comment by bblommers** [comment]
Hi @jhw, it's the version of `cryptography` that is the problem - Moto doesn't depend on `GLIBC` directly.

```
 from cryptography import x509
 File \"/opt/python/cryptography/x509/__init__.py\", line 7, in <module>
 from cryptography.x509 import certificate_transparency
 File \"/opt/python/cryptography/x509/certificate_transparency.py\", line 11, in <module>
 from cryptography.hazmat.bindings._rust import x509 as rust_x509
 ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/python/cryptography/hazmat/bindings/_rust.abi3.so
```

This typically happens when `pip` downloads dependencies for the platform that packages the project, instead of the platform that will eventually run/execute the project.

AWSLambda is build on `manylinux2010_x86_64`, so that's the platform that would need to specify during packaging:
```
pip install --platform manylinux2010_x86_64 ...
```

As a real-world example, we solved the same problem in one of our own Terraform-projects like so:

https://github.com/getmoto/payments/blob/0483829842d2c969298e9220d50f548ae508e4fa/terraform/modules/infra/functions.tf#L13

The `cryptography` project has some threads with more info on this:
https://github.com/pyca/cryptography/issues/6390
https://github.com/pyca/cryptography/issues/6391

**Comment by jhw** [comment]
Thank you 

AWS CodeBuild (building layer via `pip install {...}` now giving me this - any thoughts?

```
ERROR: When restricting platform and interpreter constraints using --python-version, --platform, --abi, or --implementation, either --no-deps must be set, or --only-binary=:all: must be set and --no-binary must not be set (or must be set to :none:).
```

**Comment by bblommers** [comment]
@jhw This is the full command that we use:
```
pip install --platform manylinux2010_x86_64 --implementation cp --only-binary=:all: --upgrade --target my_folder jwt cryptography
```
I didn't mention the `implementation` or `only-binary` arguments, because I didn't remember why they were there - but looking at the error message, they are required as well.

**Comment by jhw** [comment]
Thank you @bblommers; however - 

```
YAML_FILE_ERROR Message: Expected Commands[2] to be of string type: found subkeys instead at line 12, value of the key tag on line 11 might be empty
```

```

artifacts:
  base-directory: build
  files:
  - '**/*'
  name: $S3_KEY
phases:
  install:
    commands:
    - pip install --upgrade pip
    - mkdir -p build/python
    - pip install --platform manylinux2010_x86_64 --implementation cp --only-binary=:all: --upgrade --target build/python $PIP_TARGET 'urllib3<2'
    runtime-versions:
      python: $PYTHON_RUNTIME
version: '0.2'

```

**Comment by jhw** [comment]
I'm wondering if an alternative route might be simpler. Is it possible to tell which versions of `moto` use the `cryptography` package compiled with GLIBC 2.26 (compatible with AWS Linux 2) rather than 2.28?

**Comment by bblommers** [comment]
YAML doesn't like colons, so that would part would have to put in quotes.

I'm guessing it can either be just the colon-part:
```
pip install --platform manylinux2010_x86_64 --implementation cp --only-binary=":all:" --upgrade --target build/python $PIP_TARGET 'urllib3<2'
```
But you might have to play around with to get the right config.

**Comment by bblommers** [comment]
> I'm wondering if an alternative route might be simpler. Is it possible to tell which versions of moto use the cryptography package compiled with GLIBC 2.26 (compatible with AWS Linux 2) rather than 2.28?

Moto depends on `cryptography>=3.3.1`, and that has been like that for a long time. It's a very wide range of acceptible versions, and that is on purpose. It is up to developers then decide which exact version of cryptography they want, if the default version doesn't work for them.

**Comment by jhw** [comment]
That works (double quotes around :all:) - thank you very much for your help @bblommers
