### ISSUE TITLE
`WebsiteRedirectLocation` system-defined S3 object's metadata value not copied using multipart copy

### ISSUE THREAD

**Issue by donsokolone** [getmoto/moto#7103]
When calling https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/object/copy.html with https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html#boto3.s3.transfer.TransferConfig passed to a call so that it triggers multipart upload for any copy operation (`Config=TransferConfig(multipart_threshold=1)`) and when passing `ExtraArgs` with `WebsiteRedirectLocation` key set to a specific value moto ignores this value and copies object with `WebsiteRedirectLocation` set to `None`. When running this code against AWS `WebsiteRedirectLocation` value is copied correctly.

Versions:
moto==4.2.11
boto3==1.26.90
s3transfer==0.6.2

**Comment by bblommers** [comment]
Thanks for raising this @donsokolone. It looks like there are a few problems in this area, as we do not respect the ChecksumAlgorithm-parameter either.

Will raise a PR with a fix shortly.
