### ISSUE TITLE
bug: describe-availability-zones filtering does not work

### ISSUE THREAD

**Issue by jrindy-iterable** [getmoto/moto#7114]
# Problem
`describe-availability-zones` returns all of the AZs in a region rather than the single, expected, filtered one.

# Reproduction
Reproduction can be done easily with AWS CLI and endpoint set to the moto-server host:port. I also see the same issues in Terraform.
```bash
# zone-id
aws --endpoint=http://localhost:5000 ec2 describe-availability-zones --zone-id "use1-az1"

# zone-name
aws --endpoint=http://localhost:5000 ec2 describe-availability-zones --zone-name "us-east-1b"

# filter
aws --endpoint=http://localhost:5000 ec2 describe-availability-zones --filters Name=zoneid,Values=use1-az4

# even something like this will still return all of the AZs even though they all have state: available
aws --endpoint=http://localhost:5000 ec2 describe-availability-zones --filters "Name=state,Values=unavailable"

# regardless of how you try to filter it, it returns all of the AZs for the region
# in this case my default region is us-east-1
{
    "AvailabilityZones": [
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-east-1",
            "ZoneName": "us-east-1a",
            "ZoneId": "use1-az6",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-east-1",
            "ZoneName": "us-east-1b",
            "ZoneId": "use1-az1",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-east-1",
            "ZoneName": "us-east-1c",
            "ZoneId": "use1-az2",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-east-1",
            "ZoneName": "us-east-1d",
            "ZoneId": "use1-az4",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-east-1",
            "ZoneName": "us-east-1e",
            "ZoneId": "use1-az3",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-east-1",
            "ZoneName": "us-east-1f",
            "ZoneId": "use1-az5",
            "ZoneType": "availability-zone"
        }
    ]
}
```

# Expectation
I expect that `describe-availability-zones` with a filter returns only the single, expected, filtered AZ instead of all AZs in a region.

# Current Setup
I have the following in my docker-compose.yml and run `docker-compose up -d` to run the moto server. I've also tried the `latest` tag as well.
```yaml
services:
  moto-server:
    image: motoserver/moto:4.2.11
    ports:
      - 5000:5000
```

**Comment by bblommers** [comment]
Hi @jrindy-iterable, thanks for raising this, and welcome to Moto!

We currently support the following filters:
 - zone-id
 - zone-type
 - zone-name
 - region-name

I'll mark it as an enhancement to also support the `zone-id`/`zone-name` parameters and the `status` filter.

**Comment by bblommers** [comment]
> aws --endpoint=http://localhost:5000 ec2 describe-availability-zones --filters Name=zoneid,Values=use1-az4

Note that this doesn't work because of the typo in the name - it does work if you use `Name=zone-id`

**Comment by jrindy-iterable** [comment]
Got it. I assumed it was just zoneid due to it being ZoneId in the `describe-availability-zones` output. Thanks for the info there @bblommers, I was able to do a filter passing it in as `zone-id`.

That being said, I am hopeful that the enhancement will fix the bug I am seeing when using it with Terraform and the aws_availability_zone data source. Sample code here for reproduction with the providers.tf just pointing ec2 to moto-server:
```hcl
data "aws_availability_zone" "test_id" {
  zone_id = "use1-az1"
  filter {
    name   = "state"
    values = ["available"]
  }
}

data "aws_availability_zone" "test_name" {
  name = "us-east-1b"
  filter {
    name   = "state"
    values = ["available"]
  }
}
```
This results in the following errors with Terraform:
```bash
 Error: multiple EC2 Availability Zones matched; use additional constraints to reduce matches to a single EC2 Availability Zone
│ 
│   with data.aws_availability_zone.test_id,
│   on az.tf line 1, in data "aws_availability_zone" "test_id":
│    1: data "aws_availability_zone" "test_id" {
│ 
╵
╷
│ Error: multiple EC2 Availability Zones matched; use additional constraints to reduce matches to a single EC2 Availability Zone
│ 
│   with data.aws_availability_zone.test_name,
│   on az.tf line 9, in data "aws_availability_zone" "test_name":
│    9: data "aws_availability_zone" "test_name" {
```

Thanks so much in advance for your help!

**Comment by bblommers** [comment]
@jrindy-iterable I've just ran your TF example, and the attached PR does indeed fix that problem.

It is now part of moto >= 4.2.12.dev20. Let us know if you run into any other issues!

**Comment by jrindy-iterable** [comment]
I swapped my compose to latest and gave it a try and it is filtering the AZ as expected now. Thanks again!
