### ISSUE TITLE
Return a Challange when initiating 'admin_initiate_auth' if MFA is enabled with "SOFTWARE_TOKEN_MFA" 

### ISSUE THREAD

**Issue by tsw025** [getmoto/moto#7125]
## Reporting Bugs
* I did look into issues to check if this has already been mentioned.

Hi, 

moto version: 4.2.11
botocore version: 1.32.7
python 3.11

I ran into this issue where the `admin_initiate_auth` method returned a valid token `AuthenticationResult` response when user MFA is enabled.  
As a result, my service returned an invalid response when the user enabled TOTP, where I was expecting a challenge from Moto. 

![image](https://github.com/getmoto/moto/assets/17696525/ce48d6fc-3f53-4214-b660-b2cc49f43b33)

You can see the response from the above image as well for my tests. 

As a fix,

I added a simple addition to moto/cognitoidp/models:admin_initiate_auth function to validate if the user has enabled MFA and TOTP is set to preferred.  which then resolved my issue.  
![image](https://github.com/getmoto/moto/assets/17696525/10878fc1-99f0-4de4-b566-4f6b6b9c2344)

The response to the challenge was already handling it correctly, so I didn't have to modify it.

I'm creating this issue as I'm unsure if this modification was needed (also as a workaround I just mocked the response in my codebase).  I forked and created a fix for this [here](https://github.com/tsw025/moto/commits/feature/add-missing-totp-admin-initiate-auth-challange). I can create a PR if this is accepted as a solution.

**Comment by bblommers** [comment]
Hi @tsw025, welcome to Moto! A PR would be very welcome.

Looking at the commits you've linked, the solution looks good to me. I do think it makes sense to extend the test case a bit, and make a call to `respond_to_auth_challenge` at the end with the appropriate parameters for a `SOFTWARE_TOKEN_MFA`-challenge. That would ensure that the response from `admin_initiate_auth` is correct, and the full flow can be mocked by a user.

**Comment by tsw025** [comment]
sure, I will extend and create a PR, thanks for the feedback!

**Comment by tsw025** [comment]
add a PR https://github.com/getmoto/moto/pull/7129
