### ISSUE TITLE
Cognito IDP - user not found after being created

### ISSUE THREAD

**Issue by nykolaslima** [getmoto/moto#7164]
I have a Flask app that renders HTML templates using jinja2.
I am creating a end to end test with Playwright that will try to make the user login.
The code is using AWS cognito to manage the user's credentials and in the test we are using moto to mock the AWS cognito.
In the test setup we create a user pool and a user inside this pool. After creating the user, executing the `list_users` methods returns the inserted user.

When our test hits the flask api that was started by `pytest flask` and we try to execute the same `list_users`. we got an empty array as response, as the pool has no users.

here is the code:
```
@pytest.yield_fixture(scope="function", autouse=True)
    def cognito_client(self):
        idp = mock_cognitoidp()
        idp.start()

        cognito_client = boto3.client('cognito-idp',
                                      region_name=get_key('AWS_REGION'),
                                      aws_access_key_id=get_key('AWS_ACCESS_KEY_ID'),
                                      aws_secret_access_key=get_key('AWS_SECRET_ACCESS_KEY'),
                                      aws_session_token=get_key('AWS_SESSION_TOKEN'))

        # configure default users pool
        user_pool = cognito_client.create_user_pool(PoolName='users')
        os.environ['COGNITO_USER_POOL_ID'] = user_pool['UserPool']['Id']
        user_pool_client = cognito_client.create_user_pool_client(UserPoolId=user_pool['UserPool']['Id'],
                                                                  ClientName='test')
        os.environ['COGNITO_CLIENT_ID'] = user_pool_client['UserPoolClient']['ClientId']

        yield cognito_client

        del os.environ['COGNITO_USER_POOL_ID']
        del os.environ['COGNITO_CLIENT_ID']
        idp.stop()
        
@fixture(scope="function", autouse=True)
    def logged_user(self, cognito_util, logged_user_password, cognito_client):
        user = UserTableFactory.create().to_domain()
        cognito_util.create_confirmed_user(user.email, logged_user_password)
        # here we got a the user that was just inserted to the pool
        cognito_client.list_users(
            UserPoolId=get_key('cognito_user_pool_id'),
            Limit=123,
        )
        return user

def test_should_sign_in(self, logged_user, logged_user_password, page, cognito_client):
        page.goto(url_for('main.load_sign_in', _external=True))
        page.get_by_label("Email").click()
        page.get_by_label("Email").fill(logged_user.email)
        page.get_by_label("Password").click()
        page.get_by_label("Password").fill(logged_user_password)
        # here we call the flask API - and the user pool is found but it returns an empty array when calling list_users
        page.get_by_role("button", name="Sign In").click()
        expect(page.get_by_role("heading", name="Recipes", exact=True)).to_be_visible()
```

inspecting the user pool I saw that the it looks like the user pool object used in the test and in the flask app code are the same (same object identifier `0x1073add90`), but the flask app has an empty users attribute:
user pool in the test context
```
result = {CognitoIdpUserPool} <moto.cognitoidp.models.CognitoIdpUserPool object at 0x1073add90>
 MAX_ID_LENGTH = {int} 55
....
 users = {OrderedDict: 1} OrderedDict([('rochapedro-henrique@rodrigues.net', <moto.cognitoidp.models.CognitoIdpUser object at 0x107af8070>)])
```

user pool in the flask app
```
result = {CognitoIdpUserPool} <moto.cognitoidp.models.CognitoIdpUserPool object at 0x1073add90>
 MAX_ID_LENGTH = {int} 55
....
 users = {OrderedDict: 0} OrderedDict()
```

Since the test runs in a thread/process and the flask app runs in another thread/process - is it possible that the user pool is found but the pool's users are stored in some kind of thread local storage?

**Comment by bblommers** [comment]
Hi @nykolaslima, both UserPools and Users are stored in the global scope. So i don't quite understand what is going wrong in your example.

Are you able to provide a full reproducible test, in a standalone repo for example?

**Comment by nykolaslima** [comment]
Hi @bblommers , thanks for helping.

I found the problem. I am using `pytest flask` in order to start the flask app that is going to be tested. So I have two fixture, on fixture to create the user in the cognito pool and other fixture to start create the flask app.
```
@fixture
def logged_user(self, cognito_client, cognito_util, logged_user_password):
  user = UserTableFactory.create().to_domain()
  cognito_util.create_confirmed_user(user.email, logged_user_password)
  return user

@fixture
def app(self, cognito_client):
  os.environ['no_proxy'] = '*'
  app = create_app()
  app.config['SERVER_NAME'] = 'localhost'
  return app
```
With this code I do not guarantee that the `logged_user` will run before the `app` fixture. And what was happening is that the `app` was created first, and then the `logged_user` is created.
Looks like somehow the state that is used by the flask app is "copied" when the app is created, as the moto objects were used by value and not by reference - and in the moment that the app was created there were not users in the cognito pool.

to solve this, add the `logged_user` fixture as a dependency of `app` fixture we guarantee that the user will be created in the pool before the flask app - and then it works.

working code:
```
@fixture
def logged_user(self, cognito_client, cognito_util, logged_user_password):
  user = UserTableFactory.create().to_domain()
  cognito_util.create_confirmed_user(user.email, logged_user_password)
  return user

@fixture
def app(self, logged_user):
  os.environ['no_proxy'] = '*'
  app = create_app()
  app.config['SERVER_NAME'] = 'localhost'
  return app
```

Anyways it looks like a strange behavior since we supposed to share the same object, and if we are changing the `users` list inside of it, it should reflect in the flask app in the runtime, doesn't it?

**Comment by bblommers** [comment]
> Looks like somehow the state that is used by the flask app is "copied" when the app is created

Based on that description, I think it is a multi-threading problem actually.
If you start a new thread, Python will copy everything in the global context to the new thread - which includes the UserPool (and now User).

Any future actions in a thread will only impact the state/global context in that thread, and resources created/updated by Flask (in the Flask-thread) will not show up in the main thread. So this setup really only works for read-only tests.

You might want to have a look at the Moto server. If all threads send their boto3-calls to a shared server, they're guaranteed to share state.

https://docs.getmoto.org/en/latest/docs/server_mode.html

**Comment by nykolaslima** [comment]
makes totally sense, thanks very much for the explanation.

actually in my context it would be ok to keep the read-only approach since I am creating the setup and doing some "black box" testing that doesn't really dig in the details of the mutate state.

I believe we can close the issue since it's not a bug but a multi thread behavior.

Do you believe it worth to mention about it somewhere in the docs?

**Comment by bblommers** [comment]
Happy to help @nykolaslima!

There is a note in the FAQ that multi-threading in general is not supported. I'll see if I can extend that with this use case as an example.

I'll close this then, but let us know if you run into any other issues.

**Comment by nykolaslima** [comment]
may I open a PR with this improvement?

I could create it if you help me to figure out where is the best place to put it.

**Comment by bblommers** [comment]
Sounds good to me! 

I was planning on extending the second question here:
https://github.com/getmoto/moto/blob/master/docs%2Fdocs%2Ffaq.rst

Which would show up here:
https://docs.getmoto.org/en/latest/docs/faq.html

**Comment by nykolaslima** [comment]
Awesome. will work on some draft here and send you a PR
