### ISSUE TITLE
Moto V5 release :rocket:  - Breaking Changes :warning: 

### ISSUE THREAD

**Issue by bblommers** [getmoto/moto#7198]
Hello all!

We are releasing Moto v5 soon, containing a number of breaking changes.

New decorator
----------------------
All service-specific decorators have been replaced with single decorator.
```
@mock_aws
def test():
    ...
```

Having a single decorator simplifies the usage of Moto, fixes a whole class of bugs surrounding state management, and will make it easier for us to add additional features in the future.

Were you using the `mock_batch_simple` or `mock_lambda_simple` decorator? These can be replaced with a new `config`-parameter:
```
@mock_aws(config={
    "batch": {"use_docker": False},
    "lambda": {"use_docker": False}
})
def test():
    ...
```

Passthrough AWS requests
----------------------------------------
You can also configure Moto to let some requests through to AWS. By default everything will still be mocked, except for requests that match a URL configured here, or that are part of a service listed here.

```
@mock_aws(
    config={"core": {"mock_credentials": False, "passthrough": {"urls": [], "services": []}}}
)
```

Note the `mock_credentials` part. Moto explicitly mocks AWS credentials, to ensure that we're not accidentally reaching out to AWS. This safeguard has to be disabled for this feature to work, as you will get `InvalidCredentials` exceptions if the credentials are still mocked.

IAM Managed Policies
---------------------------------
Moto no longer loads AWS Managed Policies by default. They will only be created if explicitly configured to do so:
`@mock_aws(config={"iam": {"load_aws_managed_policies": True}})`

Or by setting an environment variable:
`MOTO_IAM_LOAD_MANAGED_POLICIES=true`

We've just released [5.0.0alpha3](https://github.com/getmoto/moto/releases/tag/5.0.0alpha3) with these changes. Please try it out, and raise any issues that you find.

The documentation for v5 can be found here: http://docs.getmoto.org/en/v5/docs/getting_started.html

This announcement will be updated as appropriate for any other changes or any other (alpha or final) releases.

**Comment by bblommers** [comment]
Moto V5 is now out. See the documentation here: 

http://docs.getmoto.org/en/5.0.0/

**Comment by archinksagar** [comment]
@bblommers Is Moto V5 backward compatible, Can we still use service-specfic decorators for existing tests?

**Comment by bblommers** [comment]
@archinksagar No, all service-specific decorators have been removed. The functionality carries over for 99% of usecases though, so a simple find-replace within your tests (`@mock_[_a-z0-9]+` -> `@mock_aws`) should be enough to start using V5.
