### ISSUE TITLE
Cognito ID/Access Token do not contain user pool custom attributes

### ISSUE THREAD

**Issue by davidtwomey** [getmoto/moto#7209]
Hi,

I notice here that user pool [custom attributes](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes) are not injected into the JWT 

https://github.com/getmoto/moto/blob/624de34d82a1b2c521727b14a2173380e196f1d8/moto/cognitoidp/models.py#L526

As described in the [AWS Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-id-token.html):

> "The ID token can also contain custom attributes that you define in your user pool. Amazon Cognito writes custom attribute values to the ID token as strings regardless of attribute type."

Would it be possible to add the custom attributes to this method?

**Comment by bblommers** [comment]
Hi @davidtwomey, welcome to Moto! I'll raise a PR with this feature in a bit.

**Comment by bblommers** [comment]
This is now part of moto >= 4.2.14.dev8 - just let us know if you run into any (other) problems.

**Comment by davidtwomey** [comment]
Awesome that was very quick! 
Thanks @bblommers!
