### ISSUE TITLE
ACM certificate with domain validation options not idempotent

### ISSUE THREAD

**Issue by jrindy-iterable** [getmoto/moto#7228]
# Problem
This is a follow up to https://github.com/getmoto/moto/issues/7138, but is technically a different issue, so I have opened a new one. 

I noticed when doing some checks for idempotency that the acm cert was being destroyed and recreated each time when the `aws_acm_certificate_validation` resource is used causing multiple resource to be replaced in the run.

I also noticed it when the `aws_acm_certificate_validation` resource was commented out as well, but it's not every time. It seems to be after a short period of time has passed. For example, with it commented out, I could run an apply and run another one right after and it would show no changes, and possibly even a third after that, but then after waiting a short period of time then it would show the changes below even though nothing in the code changed.

It almost seems like the domain validation options are removed after a period of time passes or if they are used in subsequent code, but that could just be coincidence.

Let me know if any questions and thanks in advance!

# Reproduction
I have the following Terraform files:

providers.tf
```hcl
provider "aws" {
  region                      = "us-east-1"
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    acm     = "http://localhost:5000"
    route53 = "http://localhost:5000"
  }

  access_key = "my-access-key"
  secret_key = "my-secret-key"
}
```
acm.tf
```hcl
resource "aws_route53_zone" "test" {
  name = "test.co"
}

resource "aws_acm_certificate" "certificate" {
  domain_name       = aws_route53_zone.test.name
  validation_method = "DNS"

  subject_alternative_names = ["*.${aws_route53_zone.test.name}"]

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "certificate_validation" {
  for_each = {
    for dvo in aws_acm_certificate.certificate.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.test.zone_id
}

resource "aws_acm_certificate_validation" "validation" {
  certificate_arn = aws_acm_certificate.certificate.arn
  validation_record_fqdns = [
    for record in aws_route53_record.certificate_validation : record.fqdn
  ]
}
```

The issue:
```shell
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # aws_acm_certificate.certificate has changed
  ~ resource "aws_acm_certificate" "certificate" {
      ~ domain_validation_options = [
          - {
              - domain_name           = "*.test.co"
              - resource_record_name  = "_d930b28be6c5927595552b219965053e.*.test.co."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_c9edd76ee4a0e2a74388032f3861cc50.ykybfrwcxw.acm-validations.aws."
            },
          - {
              - domain_name           = "test.co"
              - resource_record_name  = "_d930b28be6c5927595552b219965053e.test.co."
              - resource_record_type  = "CNAME"
              - resource_record_value = "_c9edd76ee4a0e2a74388032f3861cc50.ykybfrwcxw.acm-validations.aws."
            },
        ]
        id                        = "arn:aws:acm:us-east-1:123456789012:certificate/8b6ae798-134b-4097-ba15-c6c63862cb70"
        # (14 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or
respond to these changes.
...
# All the actual run info goes here, but figured it isn't actually needed to be shown, so cut it out for now
...
Apply complete! Resources: 4 added, 0 changed, 4 destroyed.
```

# Expectation
I expect that I am able to use the domain validation options and still have the infra as code still be idempotent.

# Current Setup
```yaml
services:
  moto-server:
    image: motoserver/moto:latest # have also tried 4.2.13 specifically since I saw v5 is out in alpha, both have same issue
    ports:
      - 5000:5000
```

**Comment by bblommers** [comment]
Hey @jrindy-iterable, thanks for raising this. Moto automatically verifies any certificates after 60 seconds, and changes the status from `PENDING_VALIDATION` to `ISSUED`. But we then return different `DomainValidationOptions` based on the status, which is what confuses Terraform.

Some quick testing in AWS tells me that we should return the same `DomainValidationOptions` - I've opened a PR with a fix.

**Comment by jrindy-iterable** [comment]
That would explain why I would see the issue show up even with that one resource commented out, but it would only be after a short period amount of time. Thanks for looking into this and raising a PR. I'll be sure to test it out as soon as it is merged.
