### ISSUE TITLE
s3: Misspelling of new notification enum

### ISSUE THREAD

**Issue by kbalk** [getmoto/moto#7257]
Noticed a misspelling in one of the more recent merges -- OBJCET_CREATED_EVENT should be OBJECT_CREATED_EVENT:

https://github.com/getmoto/moto/blob/51006da6b912215514125068b5f0f4c0940f1add/moto/s3/notifications.py#L9-L11

**Comment by bblommers** [comment]
Thanks for letting me know @kbalk! I've raised #7271 to fix this
