### ISSUE TITLE
Remove mock_s3 from README.

### ISSUE THREAD

**Issue by Bougeant** [getmoto/moto#7267]
## Reporting Bugs

It seems that the `@mock_s3` decorator has been deprecated in `moto>=5.0` and replaced with `@mock_aws`. However, `mock_s3` is [still part of the README](https://github.com/getmoto/moto/blob/d98972ffc8c0cf67f7572478b722b0b59a446479/README.md?plain=1#L52):

```
@mock_s3
def test_my_model_save():
   ...

```
Running this code leads to the following error: `ImportError: cannot import name 'mock_s3' from 'moto' `

**Comment by bblommers** [comment]
Thanks for letting us know @Bougeant! That has now been updated to `mock_aws`

**Comment by jordital** [comment]
needs to be updated also from pipy: https://pypi.org/project/moto/
![image](https://github.com/getmoto/moto/assets/152229707/0cc97fd6-e4bd-4ba1-8ff2-2ecf0da3200c)

**Comment by bblommers** [comment]
PyPi takes this description from the `README` @jordital, so I would expect that to be updated at the next release.
