### ISSUE TITLE
ECS container validation is overly restrictive

### ISSUE THREAD

**Issue by jmsanders** [getmoto/moto#7272]
I love the change in https://github.com/getmoto/moto/pull/7007 but I think it might be a bit over-restrictive.

Based on my read of the [docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html), `memory`/`memoryReservation` are not needed if you're using Fargate. And they're also not needed if you have `memory` set at the task level.

**Comment by nly-droid** [comment]
Why is this set as completed? When `memory` is set at the task level and not in the container definitions, `_calculate_task_resource_requirements` still expects either `memory` or `memoryReservation` to be set in the container definition
https://github.com/getmoto/moto/blob/390954b076d18213ad4cd09c8391a4f3f63344af/moto/ecs/models.py#L1483
```
# either memory or memory reservation must be provided
if (
    "Memory" in container_definition
    or "MemoryReservation" in container_definition
):
    resource_requirements["MEMORY"] += container_definition.get(
        "Memory", container_definition.get("MemoryReservation")
    )
else:
    resource_requirements["MEMORY"] += container_definition.get(
        "memory", container_definition.get("memoryReservation")
    )
```

**Comment by bblommers** [comment]
Might be worth opening a new bug report for this @nly-droid 

Please include a fully reproducible test that shows the problem that you're facing.
