### ISSUE TITLE
Paginator has stopped working for me in moto 5

### ISSUE THREAD

**Issue by timj** [getmoto/moto#7282]
I have some code that uses pagination: https://github.com/lsst/resources/blob/main/python/lsst/resources/s3.py#L472

```python
s3_paginator = self.client.get_paginator("list_objects_v2")
for page in s3_paginator.paginate(Bucket=self.netloc, Prefix=prefix, Delimiter="/"):
    ...
```
and this works perfectly in moto 4.x. In moto 5.0.0 I never get more than one page per prefix. In the test this means I get the first 1000 entries for that prefix using the delimiter and it skips directly to the next set of keys that are "sub directories", ignoring the extra 200 that also should have been returned on page 2.

The specific test code is https://github.com/lsst/resources/blob/main/python/lsst/resources/tests.py#L800-L817 but this is a generic test (the entire point of the package is to abstract URI scheme).

The test consists of:

* Write 1200 "files" to a "directory"
* Write 100 more "files" to a "subdirectory"
* Get files with the root directory prefix but have the paginator split by "/" to emulate `os.walk`.

I am trying to migrate to v5 in lsst/resources#81 but the tests fail. Maybe I'm supposed to do something with `mock_aws` that I wasn't doing with `mock_s3` but I haven't worked it out yet.

**Comment by mehdisebbar** [comment]
Same on our side for moto 5.0.0, pagination fails for list_objects_v2

**Comment by bblommers** [comment]
Hi @timj, @mehdisebbar thanks for raising this, and welcome to Moto!

The pagination logic was refactored in #7187 - looks like we introduced the bug there. I've opened a PR with a fix.
