### ISSUE TITLE
[moto]IndexError: list index out of range

### ISSUE THREAD

**Issue by r4m4k0735w4r4r40** [getmoto/moto#7292]
I am having issue with moto dynamo db batch_execute_stetement. The details are below.

**Test Code:**
```
import pytest
from moto import mock_dynamodb
import boto3


@pytest.fixture(autouse=True)
def mock_boto():
    mock_dynamodb().start()
    ddb_res = boto3.resource('dynamodb')
    table = ddb_res.create_table(
        TableName='users',
        KeySchema=[{'AttributeName': 'username', 'KeyType': 'HASH'}],
        AttributeDefinitions=[{'AttributeName': 'username', 'AttributeType': 'S'}],
        ProvisionedThroughput={'ReadCapacityUnits': 5, 'WriteCapacityUnits': 5}
    )
    table.put_item(Item={'username': 'XXXX', 'first_name': 'test1', 'last_name': 'test2'})
    table.put_item(Item={'username': 'YYYY', 'first_name': 'test3', 'last_name': 'test4'})
    yield
    mock_dynamodb().stop()


def test_batch_exec():
    ddb_cli = boto3.client('dynamodb')
    statements = [
        {
            'Statement': 'UPDATE users SET "first_name" = ?, "last_name" = ? WHERE "username"= ?',
            'Parameters': [{"S": "test5"}, {"S": "test6"}]
        }
    ]
    response = ddb_cli.batch_execute_statement(
        Statements=statements
    )
    ddb_res = boto3.resource('dynamodb')
    table = ddb_res.Table('users')
    res = table.scan()
    print(res["Items"])
```

**Error I am getting when running the test:** 

```
 @classmethod
 def get_query_metadata(cls, query: str):
     query = query.replace("\n", " ")
     clauses = re.split("SELECT | FROM | WHERE ", query, flags=re.IGNORECASE)
     from_clauses = FromParser().parse(clauses[2])
     IndexError: list index out of range
```

**Comment by bblommers** [comment]
Hi @r4m4k0735w4r4r40, which version of `moto` and `py_partiql_parser` do you have installed?

**Comment by r4m4k0735w4r4r40** [comment]
Hi @bblommers I am using py-partiql-parser==0.4.1 and moto==4.2.14

**Comment by bblommers** [comment]
Moto 4.2.14 requires `py_partiql_parser==0.5.0` - see https://github.com/getmoto/moto/blob/24b94fc192dccb311f07d2e8246d0ab27f3d38dc/setup.cfg#L59

You might still run into other errors though, as I don't know how the parser behaves when three parameters are required, but only two are passed (`test5` and `test6`)

**Comment by r4m4k0735w4r4r40** [comment]
Updated the `py_partiql_parser` version to `0.5.0`. But still facing same error.

**Comment by bblommers** [comment]
Hi @r4m4k0735w4r4r40, can you try `py-partiql-parser==0.5.1`? That contains a bunch of bugfixes, and should fix your usecase.

Note that your example query does not work (against AWS or our parser) because the number of parameters does not match the number of `?`-s. It does work when adding the missing parameter:
```
statements = [
        {
            'Statement': 'UPDATE users SET "first_name" = ?, "last_name" = ? WHERE "username"= ?',
            'Parameters': [{"S": "test5"}, {"S": "test6"}, {"S": "XXXX"}]
        }
    ]
```

**Comment by bblommers** [comment]
And I just realized - this version should be combined with `moto >= 5.0.1.dev28`, otherwise you may run into some other validation issues.
