### ISSUE TITLE
Import error in scaffold script

### ISSUE THREAD

**Issue by archinksagar** [getmoto/moto#7295]
I get the following error when I run the scaffold script.

python scripts/scaffold.py
Traceback (most recent call last):
  File "/moto/scripts/scaffold.py", line 40, in <module>
    from moto.core import BaseBackend
ImportError: cannot import name 'BaseBackend' from 'moto.core' (/moto/moto/core/__init__.py)

**Comment by bblommers** [comment]
Thanks @archinksagar - I've raised a PR with a fix. Let me know if you run into any other issues after that's merged
