### ISSUE TITLE
route53.list_hosted_zones() does not page results

### ISSUE THREAD

**Issue by pll** [getmoto/moto#7319]
When calling `route53.list_hosted_zones()`, moto returns all hosted zones regardless of the `MaxItems` count passed to it, whereas this same call directly to AWS pages the results into multiple pages of `N` items (where `MaxItems=N` and `N <= 100`.

Steps to reproduce:

- Create greater than 100 hosted zones in Route53 while mocking with moto.
- Call `r53.list_hosted_zones(MaxItems=100))`
- The length of the returned set will equal the number originally created, NOT the value of `MaxItems`.

**Comment by bblommers** [comment]
Hi @pll, thanks for raising this! I've opened a PR that implements this.

**Comment by pll** [comment]
Oh hey, @bblommers - I'm soooo sorry. I meant to say not to worry about it, I'd implement it myself. I've got the code all ready, it's just been crazy at work this week and I haven't had time to clean things up.

But if you've got the PRs ready, I'm happy to get your changes in instead.

Again, my profuse apologies, I did not intend you to waste your time.
--
Paul

**Comment by bblommers** [comment]
No problem @pll! It gave me a reminder that the Paginator-class still needed typing, see #7330, so it was not a waste of time at all :slightly_smiling_face:

**Comment by pll** [comment]
Thanks again, @bblommers! Much appreciated! I'll try to remember to tell you next time that I plan on submitting a fix myself :) Have a great weekend!
