### ISSUE TITLE
SecurityManager is null when using moto with pyspark

### ISSUE THREAD

**Issue by conting** [getmoto/moto#7321]
Hello everyone,

I have a weird issue with moto when using pyspark to write to a s3 bucket.

I mocked a s3 bucket called sample-test and then read data from a json into a pyspark dataframe. But when I am trying to persist the data the follwing error comes up:

> org.apache.hadoop.fs.s3a.AWSClientIOException: getFileStatus on s3a://sample-test/date=2024-02-08: 
com.amazonaws.SdkClientException: Unable to unmarshall response (Cannot invoke "jdk.xml.internal.XMLSecurityManager.setLimit(String, jdk.xml.internal.JdkProperty$State, Object)" because "this.securityManager" is null). Response Code: 200, Response Text: OK: Unable to unmarshall response (Cannot invoke "jdk.xml.internal.XMLSecurityManager.setLimit(String, jdk.xml.internal.JdkProperty$State, Object)" because "this.securityManager" is null). Response Code: 200, Response Text: OK
ECaused by: com.amazonaws.SdkClientException: Unable to unmarshall response (Cannot invoke "jdk.xml.internal.XMLSecurityManager.setLimit(String, jdk.xml.internal.JdkProperty$State, Object)" because "this.securityManager" is null). Response Code: 200, Response Text: OK
Caused by: java.lang.NullPointerException: Cannot invoke "jdk.xml.internal.XMLSecurityManager.setLimit(String, jdk.xml.internal.JdkProperty$State, Object)" because **"this.securityManager"** is null

It says that the security manager is null.

Here is some example code:

```from moto import mock_aws
import boto3
from pyspark.sql import SparkSession
import os
from datetime import datetime
from moto.server import ThreadedMotoServer

def get_spark():
    return SparkSession.builder \
        .config("spark.jars.packages", "org.apache.hadoop:hadoop-aws:3.3.4,org.apache.hadoop:hadoop-client:3.3.4") \
        .config("fs.s3a.endpoint", "http://127.0.0.1:5000")\
        .config('spark.hadoop.fs.s3a.impl', 'org.apache.hadoop.fs.s3a.S3AFileSystem')\
        .getOrCreate()

@mock_aws
def test_write_bucket_spark():
  server = ThreadedMotoServer()
  server.start()
  #Create Test Bucket
  bucket_output_name = "sample-test"
  conn = boto3.resource("s3", region_name="us-east-1", endpoint_url="http://127.0.0.1:5000")
  conn.create_bucket(Bucket=bucket_output_name)
  s3 = boto3.client("s3")
  assert(s3.list_buckets()["Buckets"][0]["Name"] == bucket_output_name)
  
  #Get SparkSession
  spark = get_spark()
  df = spark.read.json(os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sample_after_processing.json')))
  regions = ['us']
  date = datetime.today().strftime('%Y-%m-%d')
  #Write data to bucket
  for region in regions:
      df_part = df.filter(df.region == region)\
          .drop('region')
      for partition in [date, 'latest']:
          path = os.path.join('s3a://', bucket_output_name, f'date={partition}')
          n = df_part.count()
          df_part.repartition(n).write.json(path, mode='overwrite')
      df_part = df_part.unpersist()
  server.stop()
```

pyspark was installed via pip install pyspark and got the version 3.5.0. I installed moto in standalone moto since i wanted to access the bucket via pyspark.

I feel like I am missing some library, but I dont know and researching the error message leads into nothing. 

Thank you in regards.

**Comment by conting** [comment]
I looked into the Spark compatibility Matrix and saw that PySpark 3.5.0 runs on Java 8/11/17 
See: https://spark.apache.org/docs/3.5.0/
Then I saw that our System ran on OpenJdk-22. After changing it to 11 or 17 everything worked fine.

**Comment by bblommers** [comment]
Hi @conting, good to hear that you've found a solution. Thanks for sharing this!
