### ISSUE TITLE
Feature Request: Route53Domains

### ISSUE THREAD

**Issue by NeevCohen** [getmoto/moto#7338]
Hello! I've recently started using Moto in a personal project of mine and it has really eased my development with AWS! 

In my project I am using the Route53Domains service and was wondering if there are any plans on adding support for it? Would you be interested for me to try and open a PR for this change?

**Comment by bblommers** [comment]
Hi @NeevCohen, welcome to Moto!

PR's are always welcome. We have some documentation here that should get you started: 
http://docs.getmoto.org/en/latest/docs/contributing/index.html

Feel free if you run into any issues though.

Out of interest, which methods/features would you like to mock?

**Comment by NeevCohen** [comment]
@bblommers Thanks!

I think I'll start with the basic ones - 
* `register_domain`
* `get_domain_detail`
* `list_domains`
* `delete_domain`
* `get_operation_detail`
* `list_operations`
* `update_domain_nameservers`

Would these be OK for now?

Another thing, would you be open to adding `Pydantic` as a dependency? I think it could be really useful in validating input parameters.

**Comment by bblommers** [comment]
> I think I'll start with the basic ones -

That's absolutely fine @NeevCohen. 

> Another thing, would you be open to adding Pydantic as a dependency?

I don't think that's a good fit for Moto honestly. We're trying to keep the project as low-profile as possible, so the least amount of dependencies. 

A lot of validation also already happens within the SDK themselves, so that's already taken care of. The additional validation that needs to be done in Moto is currently done manually (regular' old if-statements), and I don't think that it is (complex) enough to warrant a dedicated library.

**Comment by NeevCohen** [comment]
@bblommers I started working on this a bit and it might take me a little while, is it OK for me to open an WIP PR that you can take a look at to make sure I'm in the right direction?

**Comment by bblommers** [comment]
> @bblommers I started working on this a bit and it might take me a little while. Is it OK for me to open a WIP PR that you can take a look at to make sure I'm in the right direction?

Absolutely! That makes a lot of sense @NeevCohen

**Comment by NeevCohen** [comment]
@bblommers Cool! Once I'll have a feature or two ready I'll open the PR. Thanks!

**Comment by NeevCohen** [comment]
@bblommers I opene a PR #7406

**Comment by bblommers** [comment]
1. In an ideal world the error matches exactly what AWS says, but if that's too time-consuming or expensive, then something descriptive is just fine.
I already saw some negative tests in the PR, so we already assert that the exceptions work as they should - and that is the most important thing.

2. Sure, that's absolutely fine. In general, if there is specific functionality you don't personally need, don't feel forced to add it. We can always fine-tune/improve things later, as and when people need it.
