### ISSUE TITLE
SES  raise MessageRejectedError() seems to result in error message "null" on the client side (Java SES SDK v2)

### ISSUE THREAD

**Issue by code-and-such** [getmoto/moto#7339]
I'm using the moto docker container to test an SES integration I've created.

Whenever I tried to send an email I got a 400 back with error message "null".
After poking around in it I realize I ended up in 

https://github.com/getmoto/moto/blob/2e9b903ab6a4d1e2309543519249b85fd81e319b/moto/ses/models.py#L276

```
        if not self._is_verified_address(source):
            self.rejected_messages_count += 1
            raise MessageRejectedError(f"Email address not verified {source}")
```
Adding the source address as verified solved the problem and I could send emails.

So it seems like the string feed to the constructor isn't properly mapped into the response.

To reproduce: 

```java

        Message message = Message
                .builder()
                .subject(Content.builder().charset("UTF-8").data("subject").build())
                .body(Body.builder().text(Content.builder().charset("UTF-8").data("body").build()).build())
                .build();
        
        SendEmailRequest request = SendEmailRequest
                .builder()
                .source("noreply@thedomain.com")
                .destination(Destination.builder().toAddresses(List.of("one@one.com")).build())
                .message(message)
                .build();

        SendEmailResponse sendEmailResponse = sesClient.sendEmail(request);

```
The expectation here is that i would get error message "Email address not verified noreply@thedomain.com" back.

Now, if I add 

```
sesClient.verifyEmailAddress(VerifyEmailAddressRequest.builder().emailAddress("noreply@thedomain.com").build());
```
before sending the email it succeeds. Thereof my conclusion that the error message is not properly mapped into the response.

Moto image version motoserver/moto:5.0.1
SES Java SDK version: 2.24.0 (tried with 2.23.0 too)

As a last comment: a few log statements in the ses implementation would be very useful. It's awfully silent.

---- 
EDIT: I've dug into the SDK and I can see that the error message is in the response, but not where the response parser expects it to be.

The code looks like this:

```
    Optional<XmlElement> getErrorRoot(XmlElement document) {
        return document.getOptionalElementByName("Error");
    }
```
This will return and empty optional, that is the expected element "Error" does not exist. Instead Moto places the error in `Errors[].Error.Message`    

Ref: https://github.com/aws/aws-sdk-java-v2/blob/21f9e2d1e0781dbe50249e9c0281b7315382be14/core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/AwsQueryProtocolFactory.java#L116

Since `AwsQueryProtocolFactory` seems to be shared among many of the SDKs I imagine this would happen in quite some places - not just in the SES part.

**Comment by bblommers** [comment]
Hi @code-and-such, thanks for raising this, and for figuring out what's wrong. Most of our internal tests use the Python SDK, which is a more lenient on the exact XML format that can be produced - that's why we will sometimes return a response in the wrong format without noticing.

Marking it as a bug.
