### ISSUE TITLE
SESv2 Variables Mismatch

### ISSUE THREAD

**Issue by sbeninga** [getmoto/moto#7340]
I am trying to use AWS SESV2 and using moto stand alone server to mock sendEmail when I came across a bug I believe!

Comparing this file moto/sesv2/models.py to what AWS sendEmail inputs should be on SESV2, it doesn’t seem like variable names are matching up!

I don’t use python much, but can give it a try at fixing! I also wanted to bring it up in case I am just completely off base!

Here is the AWS document -> https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html#API_SendEmail_RequestSyntax

**Comment by bblommers** [comment]
Hi @sbeninga! The inputs are read in `responses.py`, and those variables line up as far as I can see. We even have a few tests that verify that everything works as expected here.

https://github.com/getmoto/moto/blob/2e9b903ab6a4d1e2309543519249b85fd81e319b/moto/sesv2/responses.py#L28

Are you running into any specific issues, where Moto isn't behaving exactly the same as AWS? If so, can you share a reproducible test case?
