### ISSUE TITLE
secretsmanager rotate_secret function always invokes lambda regardless of RotateImmediately parameter

### ISSUE THREAD

**Issue by antonmos** [getmoto/moto#7342]
## Reporting Bugs

moto3 5.0.1 installed via pip and requrirements.txt 
using python mocks with boto3 1.34.41

```
sm_client.rotate_secret(
        SecretId=secret_to_rotate_arn,
        RotationLambdaARN=lambda_res['FunctionArn'],
        RotationRules={
            'AutomaticallyAfterDays': 1,
            'Duration': '1h'
        },
        RotateImmediately=False
    )
```
invokes [all steps of rotation](https://github.com/getmoto/moto/blob/master/moto/secretsmanager/models.py#L766) but the boto3 [docs](https://boto3.amazonaws.com/v1/documentation/api/1.26.85/reference/services/secretsmanager/client/rotate_secret.html) say

> RotateImmediately (boolean) --
> Specifies whether to rotate the secret immediately or wait until the next scheduled rotation window. The rotation schedule is defined in RotateSecretRequest$RotationRules.
> 
> For secrets that use a Lambda rotation function to rotate, if you don't immediately rotate the secret, Secrets Manager tests the rotation configuration by running the [testSecretstep](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_how.html) of the Lambda rotation function. The test creates an AWSPENDING version of the secret and then removes it.
> 
> If you don't specify this value, then by default, Secrets Manager rotates the secret immediately.
>

**Comment by bblommers** [comment]
@antonmos The documentation isn't very clear on who does what when, but I assume that this is the order/responsibility:

 1. SecretsManager creates an AWSPENDING version of the secret
 2. SecretsManager invokes the `testSecretStep` of the Lambda rotation function
   2.1 The rotation function verifies the `AWSPENDING` secret is correct
 3. SecretsManager removes the `AWSPENDING` version

Or is the rotation function actually responsible for creating/removing the `AWSPENDING` version?

**Comment by antonmos** [comment]
This is a good [doc](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html#rotate-secrets_how) that explain all of the steps: createSecret, testSecret, setSecret and finishSecret.

The rotation function is responsible for creating the `AWSPENDING` version in the createSecret step, and then adding the `AWSCURRENT` tag to it in the 'finishSecret' step.

**Comment by antonmos** [comment]
Wow, thank you for fixing h this so quickly! 
When do you expect to make a release?

**Comment by bblommers** [comment]
No problem @antonmos! Moto 5.0.2 has just been released.
