### ISSUE TITLE
No way to apply Configuration Options when using Server Mode

### ISSUE THREAD

**Issue by jstockwin** [getmoto/moto#7344]
I am using moto in server mode (either by directly running it as a separate docker-compose service, or via `ThreadedMotoServer`), and as far as I can tell there is no way to specify the configuration options documented at https://docs.getmoto.org/en/latest/docs/configuration/index.html when running in this mode.

To be more specific, I would like to be able to set `config={"batch": {"use_docker": False}}`, since e.g. the docker image `motoserver/moto:latest` is not able to run docker images (which would require docker-in-docker). I believe this essentially means it's impossible to use Batch via server mode.

The specific error I get after submitting a batch  job is `docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')`, but I suspect this is a misleading error message and the root cause is it not being able to run docker (the exception is coming from `site-packages/docker/api/client.py`)

I'm not interested in testing an actual docker container, and am also planning to set the state transition to manual (so the status just increments after some number of describe job calls). I'd note that it appears as though these state transitions CAN be configured in server mode - https://docs.getmoto.org/en/latest/docs/configuration/state_transition/index.html#state-transitions-in-servermode.

I need to use sever mode as I'm writing end-to-end tests with Django using `LiveServerTestCase`, so the application server which is talking to AWS is on a different thread to my test code, hence just using the decorator etc won't work as it won't have an effect on the app servers' thread.

Any pointers on how to do this, or any workarounds would be appreciated. Otherwise, I guess some additional configuration endpoints (like `/moto-api/state-manager/set-transition`) will be required?

**Comment by bblommers** [comment]
Hi @jstockwin, welcome to Moto!

There isn't really a way to do this at the moment. I'll mark it as an enhancement to configure this somehow.

**Comment by bblommers** [comment]
Hi @jstockwin, this is now possible wit the `latest` Docker image.

You can find the documentation here: 
http://docs.getmoto.org/en/latest/docs/configuration/index.html#configuring-motoserver

Please let me know if you have any questions, or if you can think of any improvements in the docs or overall approach - happy to iterate on this.

**Comment by jstockwin** [comment]
Looks great, thanks for the quick turnaround!
