### ISSUE TITLE
Feature Request: Support apigateway patchOperations for 'path': '/apiStages'

### ISSUE THREAD

**Issue by mbenita-Cyberark** [getmoto/moto#7360]
When calling `client.update_usage_plan(usagePlanId=usage_plan_id, patchOperations=[{
        'op': 'add',
        'path': '/apiStages',
        'value': f'{api_gw_id}:{api_gw_stage}',}])`
The api-gw should be attached to the usage plan but this seemed to not be the case.
I ran this code with real boto3 client and it worked. Any plan to support `patchOperations` for `/apiStages` path?

And thanks BTW for the great project

**Comment by bblommers** [comment]
Hi @mbenita-Cyberark, welcome to Moto! I've opened a PR with support for this feature.

**Comment by mbenita-Cyberark** [comment]
Wow that was fast.
Thanks very much
