### ISSUE TITLE
S3: Let's add `upload_file` method

### ISSUE THREAD

**Issue by tsugumi-sys** [getmoto/moto#7364]
I want to add a support of the `upload_file` method of s3 client to moto.

boto3 document: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/upload_file.html

If there is no problem, I'm going to create PR :)

**Comment by bblommers** [comment]
That should already be working @tsugumi-sys. See the tests here:

https://github.com/getmoto/moto/blob/7f6c9cb1deafb280fe7fcc7551c38e397f11a706/tests/test_s3/test_s3.py#L825:L829


The `s3/responses.py` is a bit of a mess, so I couldn't easily point to the exact implementation, but it's in there somewhere :slightly_smiling_face:

**Comment by tsugumi-sys** [comment]
I see, so we need to add documentation about `upload_file` :)
https://docs.getmoto.org/en/latest/docs/services/s3.html
