### ISSUE TITLE
SNS: additional message filtering operators (`$or`, case insensitive matching, suffix matching)

### ISSUE THREAD

**Issue by bram-tv** [getmoto/moto#7386]
Extra filtering operations were added to SNS: https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-sns-message-additional-filtering-operators/

More specific:
- `$or` operator: https://docs.aws.amazon.com/sns/latest/dg/and-or-logic.html#or-operator :
```
{
  "source": [ "aws.cloudwatch" ], 
  "$or": [
    { "metricName": [ "CPUUtilization" ] },
    { "namespace": [ "AWS/EC2" ] }
  ] 
}
```
-  suffix matching: https://docs.aws.amazon.com/sns/latest/dg/string-value-matching.html#string-suffix-matching
```
"customer_interests": [{"suffix": "ball"}]
```
- Equals-ignore-case matching https://docs.aws.amazon.com/sns/latest/dg/string-value-matching.html#string-equals-ignore :
```
"customer_interests": [{"equals-ignore-case": "tennis"}]
```

Example code:
```python
import json

import boto3
from moto import mock_aws

@mock_aws
def test_subscription(filter_policy):
    sqs_client = boto3.client("sqs")
    sns_client = boto3.client("sns")

    sns_topic_arn = sns_client.create_topic(
        Name="test-topic",
    )["TopicArn"]

    sqs_queue_url = sqs_client.create_queue(
        QueueName="test-queue",
    )["QueueUrl"]

    sqs_queue_arn = sqs_client.get_queue_attributes(
        QueueUrl=sqs_queue_url,
        AttributeNames=["QueueArn"],
    )["Attributes"]["QueueArn"]

    subscription = sns_client.subscribe(
        TopicArn=sns_topic_arn,
        Protocol="sqs",
        Endpoint=sqs_queue_arn,
        Attributes={
            "FilterPolicyScope": "MessageAttributes",
            "FilterPolicy": json.dumps(filter_policy),
        },
    )
```

- `$or` operator:
```python
filter_policy = {
    "source": [ "aws.cloudwatch" ],
    "$or": [
        { "metricName": [ "CPUUtilization" ] },
        { "namespace": [ "AWS/EC2" ] },
    ],
}
test_subscription(filter_policy)
```
-> Fails with `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: FilterPolicy: Unrecognized match type metricName`

- suffix matching:
```python
filter_policy = {
    "customer_interests": [{"suffix": "ball"}]
}
test_subscription(filter_policy)
```
-> Fails with: `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: FilterPolicy: Unrecognized match type suffix`

- Equals-ignore-case matching
```python
filter_policy = {
    "customer_interests": [{"equals-ignore-case": "tennis"}]
}
test_subscription(filter_policy)
```
-> Fails with: `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: FilterPolicy: Unrecognized match type equals-ignore-case`

(The filter policies above were validated against AWS)

**Comment by bblommers** [comment]
Hi @bram-tv, thanks for letting us know. I've opened a PR that adds support for these operators.
