### ISSUE TITLE
VPC Endpoint services are missing bedrock related endpoints

### ISSUE THREAD

**Issue by jamesnixon-aws** [getmoto/moto#7469]
Attempting to call the `describe_vpc_endpoint_services` operation results in an error:

`botocore.exceptions.ClientError: An error occurred (InvalidServiceName) when calling the DescribeVpcEndpointServices operation: The Vpc Endpoint Service 'com.amazonaws.us-east-1.bedrock-agent-runtime' does not exist`

This is seemingly due to this list: https://github.com/getmoto/moto/blob/565442e23d642fc379cc1caf2dc0ce1280d6c919/moto/ec2/models/vpcs.py#L43 missing the service `bedrock-egent-runtime`.

Other services may be missing, specifically I know of `bedrock`, `bedrock-runtime`, and `bedrock-agent` in addition to `bedrock-agent-runtime`.

**Comment by bblommers** [comment]
I'll mark it as an enhancement @jamesnixon-aws. Do you want to submit a PR for this yourself?

**Comment by jamesnixon-aws** [comment]
I have created a pr adding these and all other missing services to the const
