### ISSUE TITLE
Adim: How about using `ruff format` instead of `black`

### ISSUE THREAD

**Issue by tsugumi-sys** [getmoto/moto#7473]
Moto currently uses ruff (check) and black as formatter.

```make
# Makefile
format:
	black moto/ tests/
	ruff --fix moto/ tests/
```

We can use [ruff also as a formatter](https://docs.astral.sh/ruff/formatter/) like this.

```make
# Makefile
format:
	black moto/ tests/
	ruff --fix moto/ tests/
        ruff format moto/ tests/
```

I think black can be replaced as ruff format. @bblommers, what do you think?

**Comment by bblommers** [comment]
I don't have a strong opinion either way - the formatting seems to be fairly similar. Reducing the number of tools we depend on is always good though, so why not.

We would have to pin the ruff-version though. From what I can see, a new minor version will always result in formatting changes, so pinning it is necessary for us to control when the formatting changes.
