### ISSUE TITLE
Lambda: get_policy() don't raise Lambda.Client.exceptions.ResourceNotFoundException exception when no permission is define on Lambda function

### ISSUE THREAD

**Issue by bruno-gialis-al** [getmoto/moto#7475]
Hello,

Using:
- moto v5.0.3
- boto3 v1.34.63
- botocore v1.34.63
- Python v3.12.2

After creating a fresh Lambda function using create_function(), if I try to get the policy of the function using get_policy(), the return value is:
```json
{
    "ResponseMetadata": {
        "RequestId": "EN5bgDqZ4aAWhFy8SW3CczfH9TLDsoKQZR8xAWA7rudUqigyK0UV",
        "HTTPStatusCode": 200,
        "HTTPHeaders": {
            "x-amzn-requestid": "EN5bgDqZ4aAWhFy8SW3CczfH9TLDsoKQZR8xAWA7rudUqigyK0UV"
        },
        "RetryAttempts": 0
    },
    "Policy": "{\"Version\": \"2012-10-17\", \"Id\": \"default\", \"Statement\": []}",
    "RevisionId": "7f6295e6-b494-40de-8368-7c210316e748"
}
```

The real get_policy() API call return an exception (Lambda.Client.exceptions.ResourceNotFoundException) if no permission is set up on Lambda function.

Thanks.

Regards.

**Comment by bblommers** [comment]
Hi @bruno-gialis-al! Marking it as a bug to throw the correct exception here.

**Comment by rafcio19** [comment]
@bblommers I can take a look
