### ISSUE TITLE
Adding `StreamSummaries` to kinesis.list_streams response

### ISSUE THREAD

**Issue by LMaterne** [getmoto/moto#7476]
The default [boto3 response](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesis/client/list_streams.html) includes the `StreamSummaries` key. Can this be included?
https://github.com/getmoto/moto/blob/69fc969e9835a5dd30d4e4d440d0639049b1f357/moto/kinesis/responses.py#L55-L57

**Comment by bblommers** [comment]
Marking it as an enhancement @LMaterne!

**Comment by LMaterne** [comment]
@bblommers how can I add the enhancement?

**Comment by bblommers** [comment]
The specific response format is determined here:

https://github.com/getmoto/moto/blob/0f6f6893539eca7dfe3ca2693c5c053a16c2e217/moto/kinesis/responses.py#L38

We already have access to the Stream-objects there, which has  (as far as I can tell) all the information necessary to add StreamSummaries.

Ideally this is also tested - we can extend the following test to verify the response format is correct:

https://github.com/getmoto/moto/blob/0f6f6893539eca7dfe3ca2693c5c053a16c2e217/tests/test_kinesis/test_kinesis.py#L70

**Comment by LMaterne** [comment]
Thanks for the reply, that was what I was going for. However, I am not able to create a branch with my changes

**Comment by bblommers** [comment]
You would have to fork the project, create a branch on your own fork, and open a PR against that branch.

See the Github docs here: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

And our own docs with some info on how to get started when contributing to Moto: http://docs.getmoto.org/en/latest/docs/contributing/installation.html
