### ISSUE TITLE
AWS Batch create-compute-environment fails with `Could not find IAM role` in moto_server

### ISSUE THREAD

**Issue by msumner91** [getmoto/moto#7492]
**Environment**
Moto version: `5.0.3`
Executable: `moto_server -p3000`
Env vars:
```export AWS_ACCESS_KEY_ID='testing'
export AWS_SECRET_ACCESS_KEY='testing'
export AWS_SECURITY_TOKEN='testing'
export AWS_SESSION_TOKEN='testing'
export AWS_DEFAULT_REGION='us-east-1'
export MOTO_IAM_LOAD_MANAGED_POLICIES=true
```

**Issue:**
When I try to create a compute environment with the AWS CLI for the `batch` service I get an error of the form:
```
aws --endpoint-url=http://localhost:3000 batch create-compute-environment --compute-environment-name test --type UNMANAGED

An error occurred (InvalidParameterValue) when calling the CreateComputeEnvironment operation: Could not find IAM role None
```
If I instead try to set the `--service-role` arg to `AWSBatchServiceRole` or even a fully qualified `arn:...` string from the managed policies does not seem to work either:
```
aws --endpoint-url=http://localhost:3000 batch create-compute-environment --compute-environment-name test --type UNMANAGED --service-role=AWSBatchServiceRole

An error occurred (InvalidParameterValue) when calling the CreateComputeEnvironment operation: Could not find IAM role None
```

I think the issue is that for some reason the standalone server mode is not correctly loading the managed / default policies even when this environment variable is set but I am not sure. I have also tried POSTing updates to the config endpoint (/moto-api/config) to set `“iam”: {“load_aws_managed_policies”: True}` but that did not seems to help either.

Perhaps I am missing something obvious, but any help would be much appreciated!

**Comment by rafcio19** [comment]
Hi @msumner91 👋 

moto does not create any IAM roles by default, but it will create IAM policies if `MOTO_IAM_LOAD_MANAGED_POLICIES=true`. I cannot reproduce your subsequent error for

```
aws --endpoint-url=http://localhost:3000 batch create-compute-environment --compute-environment-name test --type UNMANAGED --service-role=AWSBatchServiceRole
```

On a vanilla `ubuntu 22.04, python 3.10.12, moto 5.0.3` that call results in an expected error:

```bash
An error occurred (InvalidParameterValue) when calling the CreateComputeEnvironment operation: Could not find IAM role AWSBatchServiceRole
```

To get moving, you will have to create a dummy IAM role and reference its ARN when calling `create-compute-environment`:

```bash
$ aws iam create-role --role-name batchRole --assume-role-policy-document "foo" --endpoint-url=http://localhost:3000
127.0.0.1 - - [21/Mar/2024 16:46:33] "POST / HTTP/1.1" 200 -
{
    "Role": {
        "Path": "/",
        "RoleName": "batchRole",
        "RoleId": "AROARZPUZDIKKONVWVZL7",
        "Arn": "arn:aws:iam::123456789012:role/batchRole",
        "CreateDate": "2024-03-21T15:46:33.558000+00:00",
        "AssumeRolePolicyDocument": "foo",
        "MaxSessionDuration": 3600,
        "RoleLastUsed": {}
    }
}
$ aws --endpoint-url=http://localhost:3000 batch create-compute-environment --compute-environment-name test --type UNMANAGED --service-role='arn:aws:iam::123456789012:role/batchRole'
127.0.0.1 - - [21/Mar/2024 16:47:13] "POST /v1/createcomputeenvironment HTTP/1.1" 200 -
{
    "computeEnvironmentName": "test",
    "computeEnvironmentArn": "arn:aws:batch:us-east-1:123456789012:compute-environment/test"
}
```

On moto side, it should validate presence of service-role parameter, as real AWS would throw error:

```
$ aws batch create-compute-environment --compute-environment-name test --type UNMANAGED
An error occurred (ClientException) when calling the CreateComputeEnvironment operation: Error executing request, Exception : ServiceRole is required., RequestId: b09833bb-68e1-4ad1-aa44-257acab447aa
```

I will create a PR for that validation.

**Comment by rafcio19** [comment]
@bblommers I added a PR
