### ISSUE TITLE
S3 Select: gzip input and CSV output

### ISSUE THREAD

**Issue by LucasPickering** [getmoto/moto#7499]
I'm testing some code that uses S3 Select and have a need for two unsupported features:

- Gzip-encoded input (in my case the compressed content is CSV, although I don't think that matters)
- CSV output (right now it only outputs JSON)

I was able to get the gzip working pretty easily with this code snippet (in `s3/models.py:select_object_content`):

```python
if input_details.get('CompressionType') == 'GZIP':
    import gzip
    from io import BytesIO
    with gzip.open(BytesIO(key.value), 'rt') as f:
        query_input = f.read()
else:
    query_input = key.value.decode("utf-8")  # type: ignore
```

The CSV output seems a bit trickier.

**Comment by bblommers** [comment]
Hi @LucasPickering, thanks for raising this - will mark it as an enhancement.

**Comment by bblommers** [comment]
Hi @LucasPickering, both features are now part of moto >= 5.0.4.dev46. 
Please let us know if you run into any other issues.
