### ISSUE TITLE
DynamoDB: transact_write_items does not return Item in CancellationReasons

### ISSUE THREAD

**Issue by EmmaStott** [getmoto/moto#7523]
moto 5.0.3 does not return `Item` under `err.response["CancellationReasons"][n]` when a transaction fails, despite setting `"ReturnValuesOnConditionCheckFailure": "ALL_OLD"`

This appears to be a regression of https://github.com/getmoto/moto/issues/5204

Comparing https://github.com/getmoto/moto/pull/5482/commits/970aee335bdee6ea226888229ca2e009cb979d3e to the latest version https://github.com/getmoto/moto/blob/master/moto/dynamodb/exceptions.py#L232-L256, it looks like the fix was dropped somewhere along the line.

**Comment by bblommers** [comment]
Hi @EmmaStott! We have a unit test for this, which asserts that we do return the item:

https://github.com/getmoto/moto/blob/1fc22000d9de73fae0874276ff340bda0d57d4d8/tests/test_dynamodb/test_dynamodb.py#L3805

Can you share a reproducible test case where it is not being returned?

**Comment by bblommers** [comment]
Going to close this due to a lack of response - if there is a reproducible case I'd be happy to reopen.
