### ISSUE TITLE
5.0.4 introduces stepfunctions related files in very deep path which don't install on standard Windows configuration

### ISSUE THREAD

**Issue by rdbisme** [getmoto/moto#7536]
Hello, the recent 5.0.4 version of `moto` introduces some stepfunctions related files (parser state management) which fail to install on Windows because they live in a very deep file hierarchy, and on my machine the install fails with `FileNotFoundError` because of the `MAX_PATH` on Windows. 

I know that length can be increased, but requires a registry edit which can't be performed on corporate environment without admin rights.

Any chance that might be flattened a bit?

**Comment by rdbisme** [comment]
```
• Updating moto (5.0.3 -> 5.0.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: 'C:\\Users\\rdibattista\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\app-tGjm5KPq-py3.11\\Lib\\site-packages\\moto\\stepfunctions\\parser\\asl\\component\\state\\state_execution\\state_map\\item_reader\\resource_eval\\resource_output_transformer\\resource_output_transformer_csv.

```

**Comment by rdbisme** [comment]
@bblommers

**Comment by bblommers** [comment]
Hi @rdbisme, sure - sorry about that. 

It looks like, given the path that you've provided, there are only three files with a length > 256, and the max is 265 chars long - so it doesn't need much trimming to make it work. And there are definitely some paths/files that can be shortened without an impact on readability, so that shouldn't be a problem.

**Comment by rdbisme** [comment]
@bblommers Ehi, no need to be sorry about anything :). Thanks for the quick response.

**Comment by bblommers** [comment]
Hi @rdbisme, the source tree is now flattened quite a bit with moto >= 5.0.5.dev13.

Are you able to upgrade and verify this now works for you?

**Comment by rdbisme** [comment]
Thanks @bblommers! Indeed it works. Thanks for the prompt response :)
