### ISSUE TITLE
DynamoDB Table batch_writer does not error on duplicate keys

### ISSUE THREAD

**Issue by jagoodhand** [getmoto/moto#7538]
**Problem**: moto doesn't throw an error when you attempt to write duplicate keys to a dynamodb table using the table batch_writer.

**How to reproduce the issue**: Batch write multiple same keys to a dynamodb table.

**What I expect to happen**: boto3 should throw an error when you attempt to batch_write with duplicate keys:

`An error occurred (ValidationException) when calling the BatchWriteItem operation: Provided list of item keys contains duplicates`

**What actually happens**: No error is thrown. All items are written, the last item overwrites any previous keys.

**Versions**:
moto - 5.0.4
boto3 - 1.34.73
botocore - 1.34.73

Installed using poetry, executed using python mocks.

*I think that the same problem occurs with the batch_get method, but I haven't had a chance to double check*

**Comment by rafcio19** [comment]
@bblommers I can take a look

**Comment by jagoodhand** [comment]
Thanks for the effort @rafcio19 !
