### ISSUE TITLE
IAM Managed Policy Regression for AWS Managed Policies

### ISSUE THREAD

**Issue by mikegrima** [getmoto/moto#7539]
There appears to be a regression in the IAM managed policy logic #6482) where AWS managed policies are not attachable since they are not seen in the state.

I am going to make a PR to address by checking the ARN of the policy to see if it fits the format of  an AWS managed policy and to simply pass it when attempting to attach it to a role.

This also is not resolvable by creating a managed policy since you can't actually create the AWS managed ones.

**Comment by mikegrima** [comment]
I wonder if the issue is that the init logic is injecting the AWS account ID into the ARN:
```python
    def _init_aws_policies(self) -> List[ManagedPolicy]:
        if not load_iam_aws_managed_policies():
            return []
        # AWS defines some of its own managed policies
        # we periodically import them via `make aws_managed_policies`
        aws_managed_policies_data_parsed = json.loads(aws_managed_policies_data)
        return [
            AWSManagedPolicy.from_data(name, self.account_id, d)
            for name, d in aws_managed_policies_data_parsed.items()
        ]
```

**Comment by mikegrima** [comment]
Oh, so it turns out you need to export this environment variable if you want to make use of AWS Managed policies: `MOTO_IAM_LOAD_MANAGED_POLICIES` set to `true`.

**Comment by bblommers** [comment]
Yup, this was one of the changes in v5. Because loading/parsing all the policies took an extraordinarily amount of time, I decided to make it opt-in instead.

If you're using the decorator, you can also configure it on a per-test basis:
```
@mock_aws(config={"iam": {"load_aws_managed_policies": True}})
```
