### ISSUE TITLE
AWS TgwRT : Attachment Propagations should be a list of dicts

### ISSUE THREAD

**Issue by Cupidazul** [getmoto/moto#7556]
https://github.com/getmoto/moto/blob/a7ce969b260ac87604d7b87a171d8ce5d3c7b60c/moto/ec2/models/transit_gateway_route_tables.py#L31

FROM:
```
        self.route_table_association: Dict[str, str] = {}
        self.route_table_propagation: Dict[str, str] = {}
```

TO:
```
        self.route_table_association: Dict[str, str] = {}
        self.route_table_propagation: Dict[str, str] = [{}]
```

Object should be "appended" instead of current static assignment...

FROM:
```
(...).propagation = ...
```

TO
`
.... .propagation.append( [ {
  "state": "enable",
  "TransitGatewayRouteTableId: "tgw-attach-xxxxxxxx"
 } ] 
)
`

Important note:
Seams like currently propagations are being handled by moto the same way as associations, i feel it shouldnt.
Attach-Associations, have a 1 to 1 relation with route tables.
Attach-Propagations, have a N to 1 relation with route tables.

The same way the TGW Peering-Attachments may be propagated to many routing tables: https://github.com/getmoto/moto/blob/a7ce969b260ac87604d7b87a171d8ce5d3c7b60c/moto/ec2/models/transit_gateway_attachments.py#L321

--- 

AWS:
`
aws ec2 get-transit-gateway-route-table-propagations --transit-gateway-route-table-id tgw-rtb-xxxxxxxx 
`

"get-transit-gateway-route-table-propagations" should list all "tgw-attach-xxxxxxxx" propagated that exist in a routing table.

**Current Behaviour:**
`
aws ec2 enable-transit-gateway-route-table-propagation --transit-gateway-attachment-id tgw-attach-xxxxxx  --transit-gateway-route-table-id tgw-rtb-xxxxxx
`

When we enable propagations (add new "tgw-attach-xxxxxxxx" to a route table), only the last one is saved in Moto.

**Expected behaviour:**
1. enable-transit-gateway-route-table-propagation  and disable, will add/remove attachments "tgw-attach-xxxxxxxx" from a specific tgw route table.
2. get-transit-gateway-route-table-propagations should list all enabled propagations (attachments propagated in a TgwRT)

**Comment by bblommers** [comment]
Hi @Cupidazul, thanks for raising this! I've verified this against AWS, and they indeed record/return multiple propagations.

Marking it as an enhancement - I'll probably have a PR with a fix ready for this either today or tomorrow.
