### ISSUE TITLE
SQS queue creation returns an extra slash in the queue URL

### ISSUE THREAD

**Issue by mikedambrogia** [getmoto/moto#7559]
```
import boto3
from moto import mock_aws

@mock_aws
def test_ssm():

    # setup the SQS queue
    response = boto3.client("sqs").create_queue(
        QueueName="/my/test/sqs_queue"
    )
    assert response["ResponseMetadata"]["HTTPStatusCode"] == 200

    # assert will fail since QueueUrl contains 'https://sqs.us-west-2.amazonaws.com/123456789012//my/test/sqs_queue'

    assert response["QueueUrl"] == "https://sqs.us-west-2.amazonaws.com/123456789012/my/test/sqs_queue"
```
Also, when the assert testing response["QueueUrl"] fails, VS Code reports the @moto_aws decorator as the culprit, vs the line with the failing assert which seems wonky.  If I dig into the TestFailureMessage I can then see the actual problem

![image](https://github.com/getmoto/moto/assets/13759478/d626068c-f67c-487e-bfc1-5ee80c81db5f)

Temp workaround is to .replace("//", "/") the QueueUrl value

**Comment by rafcio19** [comment]
@bblommers I can take a look

**Comment by rafcio19** [comment]
According to [AWS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#SQS-CreateQueue-request-QueueName) the queue name should only be:

> - up to 80 characters.
> - Valid values: alphanumeric characters, hyphens (-), and underscores (_).
> - A FIFO queue name must end with the .fifo suffix.
> Queue URLs and names are case-sensitive. 

so the name `/my/test/sqs_queue` would never be allowed. I will add a PR with this validation.

**Comment by mikedambrogia** [comment]
> so the name `/my/test/sqs_queue` would never be allowed. I will add a PR with this validation.

the name component is `sqs_queue`, which matches your "Valid values" in your comment.  

The pathing of `/my/test/` is valid to get to the valid queue name

`/my/test/sqs_queue` is valid

**Comment by rafcio19** [comment]
`/` is not allowed, you can verify yourself by trying to create a queue with this name in AWS:

```python
import boto3
boto3.client("sqs").create_queue(QueueName="/my/test/sqs_queue")

Traceback (most recent call last):
...
...
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateQueue operation: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length

```

**Comment by mikedambrogia** [comment]
my test code:

```
    # setup the SQS queue
    response = boto3.client("sqs").create_queue(
        QueueName="/my/test/sqs_queue"
    )
    assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
```

asserts as true

**Comment by rafcio19** [comment]
Looks like your boto calls must not be reaching the real AWS. Perhaps you are calling `moto_server`, local stack or you have `@mock_aws` somewhere in your code? 

You can attempt to create the sqs queue `/my/test/sqs_queue` from AWS console and you will see the same error 🤷

**Comment by mikedambrogia** [comment]
no, it's all mocked.  The info comes back with the account set to 1234567890, which isn't the actual account.  You can see that in the 2nd message above in the QueueUrls section

is there deeper output I can provide to help you?

**Comment by rafcio19** [comment]
@mikedambrogia I realise now I wasn't clear in my first message. Yes moto will allow an invalid name with `/`, this is the crux of your double `//` issue. The extra `/` in the url is the `/` from your invalid queue name. For valid names, the queue url is returned correctly. The reason your code works in moto is because we don't validate the queue name, however if you tried the same call against AWS then it would fail. That's what https://github.com/getmoto/moto/issues/7559#issuecomment-2040202207 is about.

I created a PR to fix the name validation issue, however there is no deeper problem with moto and sqs urls. Does that make more sense?

**Comment by mikedambrogia** [comment]
> however if you tried the same call against AWS then it would fail

I have the same test as an _IT test that interacts with AWS, and the test runs properly and does not return that extra slash in the QueueUrl

> Does that make more sense?

Until that extra / is removed on the moto QueueUrl on create_queue() I still think this is borken 

I have no control over the QueueUrl being generated with the double slash on create_queue()

I reran the code in the initial post with the debugger show show state, and added a send_message() write.  I'm paused on #L12 with the response variable opened on the L side which is immed after the create_queue() call.  You can see that the create_queue() returned a 200/success, and the QueueUrl in the response object has the double slash

![image](https://github.com/getmoto/moto/assets/13759478/dbda1c01-43f4-4343-adc9-70d0b9f2a573)

Running the send_message() using the response["QueueUrl"] value results in an exception 'QueueDoesNotExist('An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist for this wsdl version.')` due to the invalid QueueUrl from the extra slash

The only queue that exists is 'https://sqs.us-west-2.amazonaws.com/123456789012//my/test/sqs_queue' (with the double slashes), so setting the QueueUrl in send_message as a literal of the URL stripped of the extra slash still results in a queue not found since that queue was never created, only the double slashed one exists, but is inaccessable.

![image](https://github.com/getmoto/moto/assets/13759478/77da5132-1956-4994-bf4c-1e13e6c48e35)

This is why I think there is still a problem, and a fix to remove either a leading or trailing slash when building the QueueUrl in moto is needed

Hope this helps, if there is better info I can provide please let me know

**Comment by rafcio19** [comment]
@bblommers I've run out of the ways I can explain "you cannot create an sqs q with `/` in the name in AWS", perhaps you can help 🙏 
Or perhaps @mikedambrogia is right and I am missing something.

**Comment by mikedambrogia** [comment]
I'm testing the same code, but directly to AWS without moto, more in a few

**Comment by rafcio19** [comment]
Awesome, I'm glad we got to the bottom of it.
