### ISSUE TITLE
DynamoDB scan with LastEvaluatedKey doesn't return items on version 5.0.4 of moto

### ISSUE THREAD

**Issue by ricardomfmartins** [getmoto/moto#7570]
Using version 1.34.78 of boto3 and version 5.0.4 of moto returns no item, but on version 5.0.3 it returned 1 item as it was expected.

Example:
I've create 2 records with a sort key on the mocked DynamoDb like the following:
[{'itemId': '66f5dc65-fc32-40e5-8f37-613da3ce26e2', 'prefix': 'test', 'createdDate': '2024-04-05T11:43:30.150049', 'lastUpdatedDate': '2024-04-05T11:43:30.150063', 'sk': 'itemId#66f5dc65-fc32-40e5-8f37-613da3ce26e2'}, {'itemId': '52a2d0e0-371f-478d-9453-1dafaba7ad02', 'prefix': 'test', 'createdDate': '2024-04-05T11:43:30.157959', 'lastUpdatedDate': '2024-04-05T11:43:30.157968', 'sk': 'itemId#52a2d0e0-371f-478d-9453-1dafaba7ad02'}]

Requested a scan to get records using the first item as the LastEvaluatedKey  with a body like the following:
{'ProjectionExpression': '#itemId,#sk', 'ExpressionAttributeNames': {'#itemId': 'itemId', '#sk': 'sk'}, 'ExclusiveStartKey': {'itemId': '66f5dc65-fc32-40e5-8f37-613da3ce26e2', 'sk': 'itemId#66f5dc65-fc32-40e5-8f37-613da3ce26e2'}}

On version 5.0.3 this returns the second item
On version 5.0.4 no item is returned

**Comment by bblommers** [comment]
Hi @ricardomfmartins, we pushed a few bugfixes already around DynamoDB. 

Can you still reproduce this issue when installing the latest dev-release?
`moto==5.0.5.dev23`

**Comment by aarora08** [comment]
> Hi @ricardomfmartins, we pushed a few bugfixes already around DynamoDB.
> 
> Can you still reproduce this issue when installing the latest dev-release? `moto==5.0.5.dev23`

Hi @bblommers , I ran into the same issue. Yes, the latest dev-release — `moto==5.0.5.dev23` fixes this issue. Do you know when it will be released?

**Comment by bblommers** [comment]
@aarora08 [Moto 5.0.5 is out now ](https://github.com/getmoto/moto/releases/tag/5.0.5)

**Comment by Restructodev** [comment]
Appreciate the quick response @bblommers! 5.0.5 fixes the last evaluated key issue. 

However, I noticed that the pytest fixture with yielding a resource (as recommended [here](https://docs.getmoto.org/en/latest/docs/getting_started.html#example-on-usage)) does not work on moto 5. It throws an error that the resource already exists. I'm guessing the moto resource state isn't getting cleared between test runs. I'll try to debug further before creating an issue.

**Comment by aarora08** [comment]
Appreciate the quick response @bblommers! 5.0.5 fixes the last evaluated key issue. 

However, I noticed that the pytest fixture with yielding a resource (as recommended [here](https://docs.getmoto.org/en/latest/docs/getting_started.html#example-on-usage)) does not work on moto 5. It throws an error that the resource already exists. I'm guessing the moto resource state isn't getting cleared between test runs. I'll try to debug further before creating an issue.

**Comment by ricardomfmartins** [comment]
Sorry for the late reply the fix solved the issue shown above.
Thank you for your hard work.

**Comment by bblommers** [comment]
Great - thanks for confirming @ricardomfmartins!

@aarora08 Yes, if you can create a new issue with a reproducible test case, that would be great.
