### ISSUE TITLE
Cryptic error when using start_execution with Moto 5.0.5 

### ISSUE THREAD

**Issue by lephuongbg** [getmoto/moto#7583]
## Reporting Bugs

Moto version: 5.0.5

Issue: Currently can not test `send_task_success` or `send_task_failure` with Moto 5.0.4+ yet due to the state machine doesn't run properly with `waitForTaskToken` integration type.

Running following test snippet:

```python

@pytest.fixture(autouse=True)
def mock_state_machine():
    ddb_client = boto3.client("dynamodb")
    ddb_client.create_table(
        TableName="TransfersTable",
        KeySchema=[{"AttributeName": "ID", "KeyType": "HASH"}],
        AttributeDefinitions=[{"AttributeName": "ID", "AttributeType": "N"}],
        BillingMode="PAY_PER_REQUEST",
    )

    sf_client = boto3.client("stepfunctions")
    response = sf_client.create_state_machine(
        name="test",
        definition=json.dumps(
            {
                "StartAt": "WaitForTransferFinished",
                "States": {
                    "WaitForTransferFinished": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::aws-sdk:dynamodb:updateItem.waitForTaskToken",
                        "Parameters": {
                            "TableName": "TransfersTable",
                            "Key": {"ID": {"N": "1"}},
                            "UpdateExpression": "SET StepFunctionTaskToken = :taskToken",
                            "ExpressionAttributeValues": {
                                ":taskToken": {"S": "$$.Task.Token"}
                            },
                        },
                        "End": True,
                    }
                },
            }
        ),
        roleArn="arn:aws:iam::123456789012:role/test",
    )
    sf_client.start_execution(stateMachineArn=response["stateMachineArn"])
```

will results in error log in pytest's captured log call

> WARNING  moto.stepfunctions.parser.asl.component.state.exec.execute_state:execute_state.py:135 State Task encountered > an unhandled exception that lead to a State.Runtime error.
ERROR    moto.stepfunctions.parser.asl.component.eval_component:eval_component.py:35 Exception=FailureEventException, Error=States.Runtime, Details={"taskFailedEventDetails": {"error": "States.Runtime", "cause": "'Task'"}} at '(StateTaskServiceAwsSdk| {'comment': None, 'input_path': (InputPath| {'input_path_src': '$'}, 'output_path': (OutputPath| {'output_path': '$'}, 'state_entered_event_type': 'TaskStateEntered', 'state_exited_event_type': 'TaskStateExited', 'result_path': (ResultPath| {'result_path_src': '$'}, 'result_selector': None, 'retry': None, 'catch': None, 'timeout': (TimeoutSeconds| {'timeout_seconds': 99999999, 'is_default': None}, 'heartbeat': None, 'parameters': (Parameters| {'payload_tmpl': (PayloadTmpl| {'payload_bindings': [(PayloadBindingValue| {'field': 'TableName', 'value': (PayloadValueStr| {'val': 'TransfersTable'}}, (PayloadBindingValue| {'field': 'Key', 'value': (PayloadTmpl| {'payload_bindings': [(PayloadBindingValue| {'field': 'ID', 'value': (PayloadTmpl| {'payload_bindings': [(PayloadBindingValue| {'field': 'N', 'value': (PayloadValueStr| {'val': '1'}}]}}]}}]}}, 'name': 'WaitForTransferFinished', 'state_type': <StateType.Task: 16>, 'continue_with': <moto.stepfunctions.parser.asl.component.state.state_continue_with.ContinueWithEnd object at 0x7f4f4ba90b00>, 'resource': (ServiceResource| {'_region': '', '_account': '', 'resource_arn': 'arn:aws:states:::aws-sdk:dynamodb:getItem.waitForTaskToken', 'partition': 'aws', 'service_name': 'aws-sdk', 'api_name': 'dynamodb', 'api_action': 'getItem', 'condition': 'waitForTaskToken'}}'

**Comment by bblommers** [comment]
Hi @lephuongbg! This particular example does not work in AWS either, as they do no pass the actual token to DynamoDB. They pass the literal value instead:
```
[{'id': {'S': '1'}, 'StepFunctionTaskToken': {'S': '$$.Task.Token'}}]
```
Because as a user, we never get the Token, we can never call `SendTaskSuccess`, so the StepFunction just keeps running.

I'll see if I can improve Moto's implementation to at least not throw an error here, though.

**Comment by lephuongbg** [comment]
@bblommers Was a typo on my part. The actual code is:

```
[{'id': {'S': '1'}, 'StepFunctionTaskToken': {'S.$': '$$.Task.Token'}}]
```
Note the `S.$` (instead of `S`) to instruct state machine to substitute the token into the payload.

But regardless of what payload value was saved to dynamodb, the `waitForTaskToken` in the `Resource` attribute is the one that instructs the state machine to wait until receiving `send_task_success` or `send_task_failure`, not the payload though.

It would be nice (though I don't know if it's already possible or not) if moto can keep the state machine running, and have a helper function to query the generated task token from moto state.

**Comment by bblommers** [comment]
@lephuongbg Moto does keep the state machine running in the background. The proper taskToken is already stored in DynamoDB, and as of the latest dev version (`moto >= 5.0.6.dev19`, just released) you can call `send_task_success()` with this token.

In our tests, we verify this workflow this by continuously polling `describe_execution` and calling this helper function to check when the test succeeds (i.e., when the TaskToken appears in DynamoDB and when SFN has finished the execution):
```
    def _verify_result(client, execution):
        if execution["status"] == "RUNNING":
            items = dynamodb.scan(TableName=table_name)["Items"]
            if len(items) > 0:
                assert len(items) == 1
                token = items[0]["StepFunctionTaskToken"]["S"]
                client.send_task_success(taskToken=token, output=json.dumps(output))

        if execution["status"] == "SUCCEEDED":
            assert json.loads(execution["output"]) == output
            return True

        return False
```
