### ISSUE TITLE
Use execution parameters in Athena backend

### ISSUE THREAD

**Issue by ori-n** [getmoto/moto#7587]
I'm trying to update the AthenaBackend, so I will be able to create a mock based on common SQL statements I use in my tests.
I changes the start_query_execution and get_query_results methods, and it works well for me.

I'm missing in both statements the query execution parameters, which are used by Athena prepared statements. Is there any option to get to this information and use it?
see examples for parameterized queries here: https://docs.aws.amazon.com/athena/latest/ug/querying-with-prepared-statements.html

Thanks

**Comment by bblommers** [comment]
Hi @ori-n, thanks for raising this. Did you mean the `get_query_execution`-operation? That is now part of `moto >= 5.0.7.dev13`, it will return the execution parameters set by `start_query_execution`.

**Comment by ori-n** [comment]
I just checked it and it works as expected
