### ISSUE TITLE
Default cache cluster for elasticcache

### ISSUE THREAD

**Issue by archinksagar** [getmoto/moto#7591]
When we call create_cache_cluster, an additional cluster ("default") gets created, This is causing problem with our testing.
What is the reason for adding the default cluster? Can that be removed?

https://github.com/getmoto/moto/blob/cc1193076090f9daf90970db286b6b41581dd8bc/moto/elasticache/models.py#L157

**Comment by bblommers** [comment]
@jfmainville I think this was added in your PR originally, #6754 

Do you remember why you added the default cluster? Is that automatically added in specific regions, or automatically created when a user creates clusters/users? 
I've tried this out in AWS, but i can't replicate a scenario where the `default` cluster is created automatically.

**Comment by jfmainville** [comment]
Indeed, it's an oversight on my end, the default `cache_cluster` creation shouldn't be included as part of the Elasticache cache clusters initialization process, I created the MR #7622 to fix this issue.

**Comment by bblommers** [comment]
Fixed as of moto >= 5.0.6.dev30. Thank you for raising this @archinksagar, and thanks again for the fix @jfmainville!
