### ISSUE TITLE
SNS: `create_platform_endpoint` is not idempotent with default attributes

### ISSUE THREAD

**Issue by DiegoHDMGZ** [getmoto/moto#7609]
According to [AWS Documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns/client/create_platform_endpoint.html#), `create_platform_endpoint` is idempotent, so if an endpoint is created with the same token and attributes, it would just return the endpoint.

I think moto has that logic implemented. For example, the following snippet will work as expected in moto.
```python
client = boto3.client("sns")
token = "test-token"

platform_application_arn = client.create_platform_application(
    Name="test", Platform="GCM", Attributes={}
)["PlatformApplicationArn"]

client.create_platform_endpoint(
    PlatformApplicationArn=platform_application_arn, Token=token
)
client.create_platform_endpoint(
    PlatformApplicationArn=platform_application_arn,
    Token=token,
    Attributes={"Enabled": "true"},
)
```

However, I think the logic is not correct when we create the endpoint with the default attributes. The following example code will raise an exception in moto but will pass without problems in real AWS.

**Example code:** 
```python
client = boto3.client("sns")
token = "test-token"

platform_application_arn = client.create_platform_application(
    Name="test", Platform="GCM", Attributes={}
)["PlatformApplicationArn"]

client.create_platform_endpoint(
    PlatformApplicationArn=platform_application_arn, Token=token
)
client.create_platform_endpoint(
    PlatformApplicationArn=platform_application_arn, Token=token
)
```

**Expected result:** The last call to `create_platform_endpoint` should not raise an exception

To add further details, I think the problem is the default value in this line: https://github.com/getmoto/moto/blob/9713df346755561d66986c54a4db60d9ee546442/moto/sns/models.py#L682

**Moto version:** 5.0.5

**Comment by bblommers** [comment]
Hi @DiegoHDMGZ, thanks for raising this - looks like AWS indeed allows this call. I'll open a PR with a fix soon.
