### ISSUE TITLE
EC2 DescribeRouteTables filter 'route.transit-gateway-id' not implemented

### ISSUE THREAD

**Issue by aranjan1002** [getmoto/moto#7735]
It appears that the filter 'route.trasit-gateway-id' is not implemented for DescriteRouteTables. Other related filters which are [implemented ](https://github.com/getmoto/moto/blob/master/moto/ec2/models/route_tables.py#L81)are route.gateway-id, route.vpc-peering-connection-id and route.nat-gateway-id.

I can start working on this if this can be identified as a valid issue. Thanks!

**Comment by bblommers** [comment]
Hi @aranjan1002, a PR would be very welcome! Let me know if you need any help with that.

See here for a similar PR, if you want to get an idea of the changes required: https://github.com/getmoto/moto/pull/5932/files

**Comment by aranjan1002** [comment]
Hi @bblommers . I just created the PR: https://github.com/getmoto/moto/pull/7744
Please review.

I have a follow up: I need to filter based on regular expression. For example, in the above PR, I should be able to filter using "tgw-*". Should I open a new issue and start working on that? Thanks!

**Comment by bblommers** [comment]
> I have a follow up: I need to filter based on regular expression. For example, in the above PR, I should be able to filter using "tgw-*". Should I open a new issue and start working on that? Thanks!

@aranjan1002 Sounds good! Opening a issue can be useful for discussing large changes, or for requesting a feature that you'd like others to work on, but for such a small change it isn't really required. So if you're doing the work anyway, you can just open a PR.
