### ISSUE TITLE
Unable to create rds cluster

### ISSUE THREAD

**Issue by aranjan1002** [getmoto/moto#7747]
I tried creating a RDS cluster using Terraform but it gets stuck with the message: "Still creating.."

Here is a sample terraform code:

```
resource "aws_rds_cluster" "postgresql" {
  cluster_identifier      = "aurora-cluster-demo"
  engine                  = "aurora-postgresql"
  availability_zones      = ["us-east-1a"]
  database_name           = "mydb"
  master_username         = "foo"
  master_password         = "barbarbar"
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
}
```

I wonder if it is because the status is set to "creating" [here](https://github.com/getmoto/moto/blob/master/moto/rds/models.py#L195). It is previously set to "active" [here](https://github.com/getmoto/moto/blob/master/moto/rds/models.py#L160)

**Comment by bblommers** [comment]
Hi @aranjan1002, thanks for raising this! There were two issues, actually - the status was indeed incorrect, and the generated XML was sending an invalid value (`None` instead of `false`).

The attached PR fixes both, and validates that the TF is now happy.
