### ISSUE TITLE
Supporting 'appemsh' service

### ISSUE THREAD

**Issue by yafimvo** [getmoto/moto#7757]
Hello, are you planning to support the appmesh service in the near future?

[boto3 appmesh api](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/appmesh.html)

**Comment by bblommers** [comment]
Hi @yafimvo, there are no plans yet, but I'll mark it as an enhancement.

Which operations specifically would you like to see supported?

**Comment by armichaud** [comment]
Working on this with #7987
