### ISSUE TITLE
[Feature Request] Modify Backend Dict

### ISSUE THREAD

**Issue by gadelkareem** [getmoto/moto#7762]
We need a simple way to modify the backend dictionary supported by Moto out of the box.
Current:
```python
moto.backends.get_backend("rds")["123456789012"]["us-east-1"].databases[
        "instance-1"
    ].instance_create_time = now()
```

Improved:
```python
moto.backends.get_backend("rds").modify_db_instance("instance-1",  "123456789012", instance_create_time = now())
```

**Comment by bblommers** [comment]
Hi @gadelkareem!

The Backend isn't part of the public API. It can be used for convenience, but it is only designed to support the relevant boto3-operations. 

Making the API more user-friendly is out of scope as far as I'm concerned, just because it's adds an enormous amount of maintenance.
