### ISSUE TITLE
S3: get/head with partNumber is returning 200 status code instead of 206

### ISSUE THREAD

**Issue by vincer** [getmoto/moto#7779]
```
s3 = boto3.resource("s3")
s3.create_bucket(Bucket="bucket")
s3.Object("bucket", "some-key").put(Body="foo")

assert s3.meta.client.head_object(Bucket="bucket", Key="some-key", PartNumber=1)["ResponseMetadata"]["HTTPStatusCode"] == 206
```

Since it's effectively a range request, it should return 206, not 200.  Same for `get_object`.

**Comment by bblommers** [comment]
Hi @vincer, thanks for raising this! This should now be fixed as of `moto >= 5.0.12.dev18`. 

I think it also partially fixes your other S3 request, but not completely - so I'll look into that later.
