### ISSUE TITLE
Moto fails to process cloudwatch get_metric_data with Expression

### ISSUE THREAD

**Issue by Clueless1996** [getmoto/moto#7781]
**Versions used:**
**Python:** 3.11
**Moto:** 5.0.9
**Botocore:** 1.34.129

**Issue:**

Moto cloudwatch client fails on **get_metric_data** when an Expression is passed as part of MetricDataQueries argument

**Steps to reproduce:**

1. Create a pytest fixture that returns a boto3 cloudwatch client
```

pytest.fixture
def cloudwatch_client(aws_credentials):
    with mock_aws():
        yield boto3.client('cloudwatch', region_name=REGION)
```
2. Use the client to run `put_metric_data` then attempt to get it back with `get_metric_data` using an Expression query:

```
def test_cloudwatch_moto(cloudwatch_client):
  cloudwatch_client.put_metric_data(Namespace='Test/FakeNamespace', MetricData=[
        {
            'MetricName': 'ApiResponse',
            'Dimensions': [
                {
                    'Name': 'Path',
                    'Value': API_PATH_VAR
                },
                {
                    'Name': 'Audience',
                    'Value': AUDIENCE_VAR
                }
            ],
            'Timestamp': datetime.datetime.utcnow(),
            'StatisticValues': {
                'Maximum': 10,
                'Minimum': 0,
                'Sum': 10,
                'SampleCount': 10
            }
        }
    ])

expression = F'SELECT SUM(ApiResponse) FROM "Test/FakeNamespace" WHERE PATH = \'{API_PATH_VAR}\' GROUP BY Audience'
start_time = datetime.datetime.utcnow() - timedelta(hours=1)
end_time = datetime.datetime.utcnow()

result = cloudwatch_client.get_metric_data(StartTime=start_time, EndTime=end_time,
                                               MetricDataQueries=[
                                                   {
                                                       'Id': 'query',
                                                       'Period': 3600,
                                                       'ReturnData': True,
                                                       'Expression': expression,
                                                       'Label': 'Test'
                                                   }
                                               ])
```

The above returns an empty [] result, instead of the expected metric value we just put in.

**Possible cause:**

When looking through the cloudwatch client code in Moto, we have some doubts regarding it's handling of queries within expressions:

![image](https://github.com/getmoto/moto/assets/102912787/b45a4b1b-dda8-41f8-af9c-796c54e7f241)

Firstly, it fails to run when not supplied with a `Label` as part of the `MetricDataQueries` argument with and `Expression` -- this parameter is not mandatory as per boto3 docs.

Second, looking at the for-loop iterating through the `expression_queries` (Line 733) -- it references variables (Line 734) that are initialised in the previous for-loop, which is not run when using `Expression` and applies only when `MetricStat` is provided (Line 661).

The `parse_expression` call (Line 735), takes in `results` (which is empty - from line 659) and then operates on the `expression` only if `results` are present -- it return empty `([])` in our case, obviously.

![image](https://github.com/getmoto/moto/assets/102912787/b9137abd-8fd6-4257-bada-5a5e3f70abd5)

Then the parent function (`get_metric_data`) appends these results and returns `[]`.

Thus, we suspect the handling of Expression-based queries in `get_metric_data` is broken completely -- and there exist other issues regarding non-mandatory parameters being required too.

**Comment by bblommers** [comment]
Hi @Clueless1996, thank you for raising this and for debugging what's going on.

Full support for Expressions (i.e., a full-fledged SQL parser) is going to be quite an effort. However, we can fix this so that Moto a) no longer throws an error and b) at least returns some data.

When the attached PR is merged, Moto will:
 - process all data within the supplied time frame when a `Metrics Insights Query` is supplied
 - Return the SUM for all values - the actual Function that is supplied by the user is ignored for now.

Hopefully that will do - but let us know if you would like to see anything more advanced.
