### ISSUE TITLE
Plans to add support for the Transfer client?

### ISSUE THREAD

**Issue by jenstroeger** [getmoto/moto#7790]
Thank you for the great work on this package! Are there any plans to support the [Transfer client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer.html), particulalry these methods:

- [create_user](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer/client/create_user.html) and [describe_user](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer/client/describe_user.html) and [delete_user](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer/client/delete_user.html); and
- [import_ssh_public_key](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer/client/import_ssh_public_key.html) and [delete_ssh_public_key](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer/client/delete_ssh_public_key.html).

If not, then what’s your recommendation to handle such non-moto supported services?

**Comment by bblommers** [comment]
Hi @jenstroeger, we don't have any plans yet, but I'll mark it as an enhancement to add this service.

Our documentation has more info on how you can manually mock services that aren't supported yet:
http://docs.getmoto.org/en/latest/docs/services/patching_other_services.html

**Comment by armichaud** [comment]
Working on this

**Comment by jenstroeger** [comment]
Oh that’s great news 👍🏼

**Comment by jenstroeger** [comment]
@armichaud do you have a guesstimate for how long this might take?

**Comment by armichaud** [comment]
@jenstroeger It's ready for review, see #7891
