### ISSUE TITLE
EFS not supported by resourcegroupstaggingapi

### ISSUE THREAD

**Issue by rdbatch02** [getmoto/moto#7805]
Apologies, I'm back again with another resource groups tagging api feature request. It looks like EFS file systems aren't supported in moto's implementation, though they are supported in this api by AWS (https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html).

```python
@mock_aws
class MyTestClass(unittest.TestCase):
    def setUp(self):
        efs = boto3.client("efs", region_name="us-east-1")
        efs.create_file_system(CreationToken="1234")

    def test_stuff(self):
        boto3.client("resourcegroupstaggingapi", region_name="us-east-1")
            .get_resources()["ResourceTagMappingList"] # No resources are returned, expected the file system created in setUp()
```
Taking a look in the implementation it looks like this is missing altogether so this would be a net-new feature rather than a bug with any existing code https://github.com/getmoto/moto/blob/master/moto/resourcegroupstaggingapi/models.py.

Relevant Versions:
moto - 5.0.9
boto3 - 1.34.135
Python - 3.11.6
MacOS - 14.5

**Comment by bblommers** [comment]
The more the merrier @rdbatch02!

This is already part of `moto >= 5.0.11.dev11`.

**Comment by rdbatch02** [comment]
Amazing, thanks @bpandola and @bblommers for the super quick turnaround!
