### ISSUE TITLE
Dynamo DB - Cannot use ARN in place of TableName across multiple methods

### ISSUE THREAD

**Issue by ncilfone** [getmoto/moto#7843]
For instance, from the boto3 docs:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/describe_table.html

> Parameters:
> 
>     TableName (string) –
> 
>     [REQUIRED]
> 
>     The name of the table to describe. You can also provide the Amazon Resource Name (ARN) of the table in this parameter.

If you look at the moto implementation of `describe_table` you can see that only the table name can be used and not the ARN since `self.table[name]` is only in reference to the table name :

https://github.com/getmoto/moto/blob/1c8c0fe4d9c7f5481a40814a8a6459a5142707ff/moto/dynamodb/models/__init__.py#L165-L169

**Comment by alexevansigg** [comment]
I have the same issue using DynamoDB Resource and batch_get_item metthod... here in the requestItems argument the map keys are the ARN or Table Name.... when I use the ARN it doesn't mock correctly. (see [doc](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/batch_get_item.html#:~:text=PARAMETERS%3A-,RequestItems,-(dict)%20%E2%80%93))

**Comment by bblommers** [comment]
Hi @alexevansigg and @ncilfone, thanks for raising this! The attached PR fixes this, so ARN's are now allowed for all methods that take a `TableName`-parameter.
