### ISSUE TITLE
SSM: Missing parameters for certain regions

### ISSUE THREAD

**Issue by viren-nadkarni** [getmoto/moto#7869]
Moto fetches SSM parameters from AWS and saves them at `moto/ssm/resources/ami-amazon-linux-latest`. However, the files are missing for the following regions:

- ap-southeast-4
- ca-west-1
- il-central-1

Upon checking the [latest scheduled GitHub action](https://github.com/getmoto/moto/actions/runs/9742195445/job/26883002927#step:5:266) that keeps these files up to date, I noticed that these regions are skipped because of an exception.

It is possible that the AWS account used for this action does not have access to these regions, and enabling these regions would fix this issue.

**Comment by bblommers** [comment]
Hey @viren-nadkarni, thanks for letting me know! That was indeed the problem - I've updated the AWS account for one that does have access to all regions in #7877, and with #7878 Mot now contains the instance data for all regular regions, including the ones  you listed.

**Comment by viren-nadkarni** [comment]
Thanks @bblommers!
