### ISSUE TITLE
ThreadedMotoServer: support automatic port picking

### ISSUE THREAD

**Issue by soxofaan** [getmoto/moto#7894]
ThreadedMotoServer uses the werkzeug's `make_server`, which refers to [`run_simple`](https://werkzeug.palletsprojects.com/en/3.0.x/serving/#werkzeug.serving.run_simple) for documentation:

> port (int) – The port to bind to, for example 8080. **Using 0 tells the OS to pick a random free port.**

This feature to automatically get a free port when providing `port=0` is handy in test situations where you want to avoid collision with other existing services or running tests.

Currently however, to obtain the actual port number, one has to do something along the lines of

```python
server = moto.server.ThreadedMotoServer(port=0)
server.start()
host, port = server._server.server_address
endpoint = f"http://{host}:{port}"
```

which goes through a private attribute `_server`, and doesn't feel future proof.

Would it be possible to provide a method to get the actual port in a cleaner way?

Some implementation options:
-  make the `_port` attribute public and update it after starting the server, so one can just use `server.port`
- add method to get actual port number as int
- add method to get the full `_server.server_address` (a (host, port) tuple)
- add method to directly get a ready to use endpoint_url ( ` f"http://{host}:{port}"`)

**Comment by bblommers** [comment]
That's a good point - I've added a new method called `get_host_and_port()`. :+1:
