### ISSUE TITLE
Document how to use ThreadedMotoServer as pytest fixture

### ISSUE THREAD

**Issue by soxofaan** [getmoto/moto#7895]
I've been playing with ThreadedMotoServer in a pytest fixture to automatically spin up the server when selected tests need it:

```python
# Note: pick an appropriate fixture "scope" for your use case
@pytest.fixture(scope="module")
def moto_server():
    """Fixture to run a mocked AWS server for testing."""
    # Note: pass `port=0` to get a random free port.
    server = moto.server.ThreadedMotoServer(port=0)
    host, port = server._server.server_address
    server.start()
    yield f"http://{host}:{port}"
    server.stop()

@pytest.fixture
def s3_client(moto_server):
    return boto3.client("s3", endpoint_url=moto_server)

...
```

I think it makes sense to include something like this in the pytest related docs.

Note: this ticket is related to
-  #7892 
-  #7894

**Comment by soxofaan** [comment]
Or maybe even better, one step further: 
provide this as built-in fixture so that users just have to install `moto[server]` and directly can use a `moto_server` fixture

**Comment by bblommers** [comment]
Adding an example to the docs makes a lot of sense @soxofaan. You can see a preview here:
https://moto--7949.org.readthedocs.build/en/7949/docs/server_mode.html#start-within-python

Note that it already uses the new `get_host_and_port()` method, as you suggested in your other post.
