### ISSUE TITLE
Large size on disk when installing for just one service

### ISSUE THREAD

**Issue by AlecRosenbaum** [getmoto/moto#7909]
This isn't really a bug, but more just unexpected behavior for me.

`moto` is a relatively large dependency on-disk, installed it's around 58MB for me. A huge portion of that seems to be big json files that define things like AMI's available for every region, all ec2 types, etc.

We only use `moto` for s3, and when I saw there was a way to install `moto[s3]` I assumed that also meant I wouldn't be downloading big json files for all the other AWS services `moto` supports mocking out. 

Is there any way to exclude data for other services? `moto` is now the largest dependency of our pretty heavy monolithic application. `botocore` has a [similar issue](https://github.com/boto/botocore/issues/1543), but currently it's down to 17MB on disk.

**Comment by bpandola** [comment]
Doing what `botocore` did, by just including gzip'd versions of the larger resource files as part of the distribution, seems like the right path here.  Marking this as an enhancement.
