### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [getmoto/moto#7941]
### Description:

In the "moto/moto/kms/utils.py", I have identified a security vulnerability about insecure cryptographic algorithm. PKCS1v1.5  is vulnerable to the chosen-ciphertext attack.

### Location:

https://github.com/getmoto/moto/blob/master/moto/kms/utils.py#L212

```python
elif signing_algorithm == SigningAlgorithm.RSASSA_PKCS1_V1_5_SHA_256:
           pad = padding.PKCS1v15()
           algorithm = hashes.SHA256()
elif signing_algorithm == SigningAlgorithm.RSASSA_PKCS1_V1_5_SHA_384:
           pad = padding.PKCS1v15()
           algorithm = hashes.SHA384()
else:
           pad = padding.PKCS1v15()
           algorithm = hashes.SHA512()
```

### Reference

- **CWE-780: Use of RSA Algorithm without OAEP**

### Recommendations:

Try using other padding(OAEP) instead of PKCS1v1.5.

**Comment by bblommers** [comment]
This is a test tool - any CWE's are not relevant.

Moreover, we mock AWS features - if AWS uses PKCS1v1.5, so should we.

Please don't spam repositories like this @lialon - open source maintainers have better things to do. Only open issues if they are legitimate security threats, with the steps to reproduce it against that particular library.
