### ISSUE TITLE
Directory Service: DescribeDirectories expects LaunchTime to be a JSON Number, got string instead

### ISSUE THREAD

**Issue by lorengordon** [getmoto/moto#7947]
Hello,
I'm using moto server with Terraform, creating a AWS Directory Service instance. I think there was a change in the API for `ds:DescribeDirectories`, or maybe just new validation on the response. But using the latest moto version, 5.0.12, I'm seeing the following error:

```
Error: reading Directory Service Directory (d-7b4fdb73d6): operation error Directory Service: DescribeDirectories, https response error StatusCode: 200, RequestID: QjGxElo4976zUbXqHjhAzLjSYn2WHHZ0VA46AmJTfyjldHWH6hVP, deserialization failed, failed to decode response body, expected LaunchTime to be a JSON Number, got string instead

  with module.directory_service.aws_directory_service_directory.this,
  on ../../main.tf line 1, in resource "aws_directory_service_directory" "this":
   1: resource "aws_directory_service_directory" "this" {
```

Checking the code, I see it is writing a datetime string in isoformat:

https://github.com/getmoto/moto/blob/2a8bb4a6fc06ad91ad1b234ccb11c1199b0898f2/moto/ds/models.py#L83

Looking up the API doc for the command, the response syntax for LaunchTime is actually a number.

https://docs.aws.amazon.com/directoryservice/latest/devguide/API_DescribeDirectories.html#API_DescribeDirectories_Examples

**Comment by lorengordon** [comment]
Actually, near identical issue on CodeBuild Projects. The codebuild:CreateProject response expects both `TimeStamp` and `BuildTimeOut` to be a number, but it's getting a string. 

```
Error: creating CodeBuild Project (tardigrade-test-branch-flow-ci-branch-master-flow-ci): operation error CodeBuild: CreateProject, https response error StatusCode: 200, RequestID: 0btCD9rbQYZDkxcRWJCHux6XSJy7z6pJUzPY7X1sPRCd6Gcpinve, deserialization failed, failed to decode response body, expected BuildTimeOut to be json.Number, got string instead

  with module.test_branch["master_branch"].module.runner.aws_codebuild_project.this,
  on ../../modules/_internal/runner/main.tf line 168, in resource "aws_codebuild_project" "this":
 168: resource "aws_codebuild_project" "this" {

Error: creating CodeBuild Project (tardigrade-test-branch-flow-ci-branch-testempty-flow-ci): operation error CodeBuild: CreateProject, https response error StatusCode: 200, RequestID: bu61y90m14BiKzBPndSMQxGcyinqauHLzy5Tzgs7LX3yIpJhchxn, deserialization failed, failed to decode response body, expected Timestamp to be a JSON Number, got string instead

  with module.test_branch["test_empty_list"].module.runner.aws_codebuild_project.this,
  on ../../modules/_internal/runner/main.tf line 168, in resource "aws_codebuild_project" "this":
 168: resource "aws_codebuild_project" "this" {
```

I think these are where it's set in moto:

https://github.com/getmoto/moto/blob/2a8bb4a6fc06ad91ad1b234ccb11c1199b0898f2/moto/codebuild/models.py#L120

https://github.com/getmoto/moto/blob/2a8bb4a6fc06ad91ad1b234ccb11c1199b0898f2/moto/codebuild/models.py#L130

And here's the api doc with the response syntax indicating those should be numbers:

https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateProject.html#API_CreateProject_ResponseSyntax

**Comment by bblommers** [comment]
Hi @lorengordon! I've opened a PR that fixes both issues (+ a bunch of other things to make TF happy).
