### ISSUE TITLE
The filter 'kms-key-id' for DescribeSnapshots has not been implemented in Moto yet

### ISSUE THREAD

**Issue by plyDataiku** [getmoto/moto#7977]
Hello

Tried to create the following unit test : 
create a volume
create a snapshot of the volume
copy the snapshot with a new KMS key
then call `describe_snapshots` with this filter `[{"Name": "kms-key-id", "Values": [kms_key]}]`

and got` moto.ec2.exceptions.FilterNotImplementedError: The filter 'kms-key-id' for DescribeSnapshots has not been implemented in Moto yet.`

**Comment by bblommers** [comment]
Thanks for raising this @plyDataiku, and for adding the reproduction steps - I'll mark it as enhancement to add this filter.
