### ISSUE TITLE
Autoscaling groups do not pass launch template to EC2 instances.

### ISSUE THREAD

**Issue by Skyscimitar** [getmoto/moto#7979]
When creating an Auto Scaling Group using moto, the launch template argument is ignored when creating instances in the autoscaling group (only launch config is taken into account). This means that any properties of instances managed by the AutoScaling group and set in the launch template are not transferred to the instance. (In `moto.autoscaling.models.FakeAutoScalingGroup.replace_autoscaling_group_instances`, we see that only the launch config is used to pass configuration to the created instances and not the launch template). 

moto version: 5.0.12 installed using poetry.

**Comment by bblommers** [comment]
Hi @Skyscimitar, welcome to Moto.
We do pass some launch template values, like ImageId, InstanceType, and a few others:

https://github.com/getmoto/moto/blob/fc60bd1c5f6e6184e30a6db8b65059a2855cd28e/moto/autoscaling/models.py#L692

Which other properties would you like to see support for?
