### ISSUE TITLE
Bug in RDS modify_db_instance with CloudwatchLogsExportConfiguration

### ISSUE THREAD

**Issue by heldersepu** [getmoto/moto#7990]
## how to reproduce the issue

```
import boto3
from moto import mock_aws

@mock_aws
def rds():
    client = boto3.client("rds")
    response = client.create_db_instance(
        DBInstanceIdentifier="test",
        DBInstanceClass="db.m5.large",
        Engine="sqlserver-se",
        MasterUsername='string',
        MasterUserPassword='string123',
        LicenseModel="license-included",
        AllocatedStorage=32
    )
    print(response)
    print("---")

    response = client.modify_db_instance(
        DBInstanceIdentifier="test",
        CloudwatchLogsExportConfiguration={'EnableLogTypes':['error']}
    )
    print(response)
    print("---")

    response = client.describe_db_instances(DBInstanceIdentifier="test")
    print(response)
    print("---")

rds()
```

## what you expected to happen
After calling the `modify_db_instance` with the `CloudwatchLogsExportConfiguration` it should have the enabled log types

## what actually happens
The response is the same, nothing shows on the CW logs

## what version of Moto you're using
Latest ([5.0.12](https://github.com/getmoto/moto/releases/tag/5.0.12))

## how you installed it
`pip install 'moto[all]`

**Comment by bblommers** [comment]
Hi @heldersepu, thanks for raising this! This property is now updated properly as of moto >= 5.0.13.dev58.

**Comment by heldersepu** [comment]
> Hi @heldersepu, thanks for raising this! This property is now updated properly as of moto >= 5.0.13.dev58.

@bblommers Can I get that version with pip?

**Comment by bblommers** [comment]
@heldersepu In this case, you can just install `moto==5.0.13`, as I've just released a new version. :slightly_smiling_face: 

But in general, if you want a development version, you can explicitly specify the version during installation:
```
pip install moto==5.0.13.dev58
```
