### ISSUE TITLE
Route53 should raise an exception when provided with an invalid domain name

### ISSUE THREAD

**Issue by philipstarkey** [getmoto/moto#7999]
## `boto3` behaviour

The boto3 Route53 `client.list_resource_record_sets()` method raises a `client.errorfactory.InvalidInput` exception if the `StartRecordName` isn't valid.

For example:

```
# Add appropriate `HostedZoneID` and `StartRecordType` kwargs
# Note the space in the subdomain which is invalid
client.list_resource_record_sets(StartRecordName="Invalid Subdomain.example.com.", ...)
```

Would raise the exception:

```
   ...
  File "python/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "python/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidInput: An error occurred (InvalidInput) when calling the ListResourceRecordSets operation: FATAL problem: UnsupportedCharacter (Value contains unsupported characters) encountered with ' '
```

## `moto` behaviour

Unfortunately, `moto` doesn't raise this exception this and will happily accept invalid domain names.

## Use case

The `InvalidInput` exception is dynamically created by `botocore` when the Route53 client is created. This means that unless you have access to the client, you can't catch the exception (unless you just broadly catch all `ClientError` exceptions which I don't want to do). This is often the case if the exception is bubbling up. I'm wrapping the exception with my own to solve this, but I can't write unit tests to cover this behaviour as `moto` doesn't replicate the behaviour!

I haven't checked, but I'm guessing this is an error that boto3 will raise more broadly when encountering invalid record names. So the usefulness likely extends beyond my specific usage.

## Related issues

#5059 looks like a similar issue, but it's a different Route53 method, conditions, and exception type.

**Comment by bblommers** [comment]
Hi @philipstarkey, thanks for raising this - I've opened a PR that adds some validation here.

With international domain names the list of approved characters is quite large, so I've only implemented the following rules:

> If your domain name contains any of the following characters, you must specify the characters by using escape codes in the format \three-digit octal code:
>
>    Characters 000 to 040 octal (0 to 32 decimal, 0x00 to 0x20 hexadecimal)
>
>    Characters 177 to 377 octal (127 to 255 decimal, 0x7F to 0xFF hexadecimal)
> 

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html

So Moto doesn't cover everything, but it validates your particular use-case, and we know for certain that our validation will not be too strict.
