### ISSUE TITLE
ServiceURL not matching when using apigatewaymanagementapi 

### ISSUE THREAD

**Issue by bfbenf** [getmoto/moto#8008]
Python Version: 3.12.2
Moto Version: 5.0.13
OS: Mac OSX 14.5

Hi All!

I'm hoping I am just missing something instead of this being a bug. I am trying to use the `apigatewaymanagementapi` client with moto and I keep getting a error of `botocore.exceptions.ClientError: An error occurred (404) when calling the PostToConnection operation: Not yet implemented` 

I have done some digging into this and I think it is because I am using an `endpoint_url` in the client as per the documentation. _To use it, you must explicitly set the SDK’s endpoint to point to the endpoint of your deployed API. The endpoint will be of the form [https:/](https://boto3.amazonaws.com/)/{api-id}.execute-api.{region}.amazonaws.com/{stage}, or will be the endpoint corresponding to your API’s custom domain and base path, if applicable._ (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewaymanagementapi.html)

The error is coming from BotocoreStubber because the the URL is not matching any of the service URLs. This is what it tried to run for `apigatewaymanagementapi` 

```
service: apigatewaymanagementapi 
regex: re.compile('https?://execute-api\\.(.+)\\.amazonaws\\.com') 
url: https://gldhhqzr.execute-api.us-east-1.amazonaws.com/@connections/123
```

I have looked at tests on the PR where apigatewaymanagementapi was introduced and can see they are not using the endpoint_url but when I don't it has no way to understanding the stage name for the api and does not work in real execution. 

I've looked through the docs and cannot see anything specially about how to run this any differently than any other moto calls.

The code being tested looks like this 

```python
client = boto3.client(
        "apigatewaymanagementapi",
        endpoint_url=f"https://{os.environ['API_ID']}.execute-api.{os.environ['REGION']}.amazonaws.com/{os.environ['STAGE']}",
    )
...
client.post_to_connection(
                    ConnectionId=connection["connectionId"]["S"],
                    Data=f"{json.dumps(deserialize_dynamodb_json(message))}",
                ) 
```

**Comment by bblommers** [comment]
Hi @bfbenf! Looks like we weren't matching against the correct URL's, Moto always expected the endpoint URL to be `https://execute-api.us-east-1.amazonaws.com`. I've raised a PR to fix this.

**Comment by bfbenf** [comment]
Thanks for swift fix @bblommers
