### ISSUE TITLE
Fn::Base64 in cloud formation templates is not handled

### ISSUE THREAD

**Issue by Skyscimitar** [getmoto/moto#8018]
Hello!

We use the `Base64` function to encode user data in our cloud formation templates. However it seems that when cleaning the template JSON, Moto does not handle the Base64 function, which results in the `{"Fn::Base64": "user_data_script..."}` dict being passed to the EC2 Instance instead of the b64 encoded string.

**Comment by bblommers** [comment]
Hi @Skyscimitar! I've opened a PR to support this function.
