### ISSUE TITLE
If MfaConfiguration is "ON", then software_token_mfa_enabled should be set in verify_software_token

### ISSUE THREAD

**Issue by jpmckinney** [getmoto/moto#8029]
Presently, software_token_mfa_enabled is only set to True in admin_set_user_mfa_preference.

(When MfaConfiguration is "ON", I don't know it it should be set even earlier than verify_software_token, but it should be set at least once token_verified is set to True).

**Comment by bblommers** [comment]
Hi @jpmckinney, do you have a scenario/reproducible test case that shows where Moto's behaviour differs from AWS?

**Comment by jpmckinney** [comment]
I haven’t tested with the new code (thank you!), but this relates to doing a login in a new session (after MFA was setup in a previous session). When I tried that with the old code, I wasn’t getting an MFA challenge after password authentication.

**Comment by bblommers** [comment]
Happy to help @jpmckinney!

moto >= 5.0.14.dev37 now also requests an MFA token for a second login, plus some other improvements. I think all MFA workflows are now covered, but do let us know if there's still something missing.

**Comment by jpmckinney** [comment]
Awesome, it works! Thank you!
