### ISSUE TITLE
create_state_machine/update_state_machine does not populate stateMachineVersionArn when publish=True

### ISSUE THREAD

**Issue by ekolve** [getmoto/moto#8081]
When calling [create_state_machine](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions/client/create_state_machine.html) and [update_state_machine](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions/client/update_state_machine.html) and passing `publish=True` to either of those commands, the property `stateMachineVersionArn` should be populated in the response with something resembling: `arn:aws:states:us-west-2:123456789012:stateMachine:my-state-machine:33`, but the field is missing from the response.

https://github.com/getmoto/moto/blob/fb51925d2be3a14d96abc12349be3ad332d18dc1/moto/stepfunctions/responses.py#L34
```python
        response = {
            "creationDate": state_machine.creation_date,
            "stateMachineArn": state_machine.arn,
        }
```

Could the model be updated to include this if `publish=True`?

**Comment by bblommers** [comment]
Can do @ekolve! I've raised a PR with the necessary changes.

**Comment by ekolve** [comment]
Thank you!
