### ISSUE TITLE
Static resource ID's

### ISSUE THREAD

**Issue by ludsrill** [getmoto/moto#8089]
Currently, Moto generates random IDs each time I create a resource, for example, something like:

```json
"GroupId": "sg-79f9a3e099b52c2da"
```

However, I’d like to know if there’s a way to make these IDs deterministic (always the same) in tests, so I can make comparisons and ensure consistency across test cases.

I'm thinking of making a patch for this, but is there another way to achieve it?

**Comment by bblommers** [comment]
Hi @ludsrill, you can seed Moto to make identifiers deterministic.

See the docs here: https://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html#deterministic-identifiers

**Comment by ludsrill** [comment]
that's it, thx!
