### ISSUE TITLE
S3 head_bucket method should return error code "NoSuchBucket" when bucket doesn't exists

### ISSUE THREAD

**Issue by MacHu-GWU** [getmoto/moto#8105]
See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/head_bucket.html

And I tested already, it should raises ``e = botocore.exceptions.ClientError()`` and the ``e.response["Error"]["Code"]`` should be ``"NoSuchBucket"``

**Comment by bblommers** [comment]
Hi @MacHu-GWU, Moto already validates this scenario, see the test case here:
https://github.com/getmoto/moto/blob/255d2b851dd11e3aecf8425ba402678072fa2ba4/tests/test_s3/test_s3.py#L244

If I execute that test against AWS (with a unique bucket name), I get the exact same error: 
```
{
  'Error': {'Code': '404', 'Message': 'Not Found'},
  'ResponseMetadata': {'RequestId': '1PZ7EKK7M8T1YDEY', 'HostId': '...', 'HTTPStatusCode': 404, 'HTTPHeaders': {'x-amz-request-id': '...', 'x-amz-id-2': '...', 'content-type': 'application/xml', 'date': 'Mon, 09 Sep 2024 18:38:57 GMT', 'server': 'AmazonS3'}, 'RetryAttempts': 0}}
```
What does your scenario look like, and how did you test it that you ended up with a NoSuchBucket-error?

**Comment by MacHu-GWU** [comment]
The AWS suggested way to capture error for boto3 is like this:
```python
import botocore.exceptions
import boto3

s3 = boto3.client('s3')

try:
    s3.head_bucket(...)
except botocore.exceptions.ClientError as e:

    if e.response["Error"]["Code"] == "ExpectedErrorCode":
        print("bucket not exists, create one")
        s3.create_bucket(...)
    else: # unhandled error
        raise e
```

You can find all valid ExpectedErrorCode at the bottom of boto3 document (see example here https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/head_bucket.html)

For this API, if the bucket doesn't exists, it should give me "NoSuchBucket"

**Comment by MacHu-GWU** [comment]
I am so sorry, I don't know where I got `NoSuchBucket` in my test, I think the existing implementation is right. Please close this issue.
