### ISSUE TITLE
Mocking Cloudfront key pair for signing?

### ISSUE THREAD

**Issue by chrisspen** [getmoto/moto#8121]
I think this might be more of a feature request, but is there any way to mock a Cloudfront key pair, so we can simulate signing URLs for restricted Cloudfront paths? I can't find anything in the documentation.

I've written a unittest that uses moto to successfully mock S3, Dynamo, Cloudfront, and Cognito, but I'm stuck on trying to generate signed cookies to a Cloudfront path.

**Comment by bblommers** [comment]
Hi @chrisspen, that is not possible at the moment. As a workaround, it is always possible to patch botocore to mock these methods: https://docs.getmoto.org/en/latest/docs/services/patching_other_services.html

I'll mark it as an enhancement to add support for these in Moto though. Which methods specifically would you like to see mocked? Based on your description, it sounds like at least:
 - create_public_key()
 - create_key_group()

Any others?
