### ISSUE TITLE
Error in server/standalone mode

### ISSUE THREAD

**Issue by tumkurrunner** [getmoto/moto#8133]
Lambda invoke error for Java 17 runtime.
Steps:
Error: entrypoint requires the handler name to be the first argument
export MOTO_DOCKER_LAMBDA_IMAGE="amazon/aws-lambda-java"
then started moto-server -H 0.0.0.0
Created a lambda function using aws lambda create-function.. and then invoked using aws lambda invoke which results in error **" entrypoint requires the handler name to be the first argument"**

**Comment by bblommers** [comment]
Hi @tumkurrunner, can you share a fully reproducible example?

Does your code run successfully against AWS?

**Comment by tumkurrunner** [comment]
Sorted now it was problem with my python version 3.6
