### ISSUE TITLE
Poor performance of BotocoreStubber

### ISSUE THREAD

**Issue by igorsimko** [getmoto/moto#8185]
https://github.com/getmoto/moto/blob/master/moto/backend_index.py#L11
When using `moto` and `mock_aws` in my pytest fixture, I noticed very poor performance at [moto/core/botocore_stubber.py#L56](https://github.com/getmoto/moto/blob/master/moto/core/botocore_stubber.py#L56) when matching S3 Object Url with many dots.

`BotocoreStubber` is matching S3 Object Key/url in `process_request` with backend url patterns. One of the pattern is 
https://github.com/getmoto/moto/blob/master/moto/backend_index.py#L11
```
    (
        "apigatewaymanagementapi",
        re.compile("https?://(.+\\.)*execute-api\\.(.+)\\.amazonaws\\.com"),
    ),
```
which seems to have very bad performance when matching urls with many dots. I quickly tried to patch that regex to be more explicit:
```
^https?://([a-zA-Z0-9-]+\\.)*execute-api\\.[a-z]{2}-[a-z]+-\\d+\\.amazonaws\\.com
```
and I can see very significant improvemence: < 1sec matching url instead of 30+ sec 

Example of such url would be:
```
https://my-bucket.s3.eu-central-1.amazonaws.com/a.1.1.1.1.1.1/b.2.2.2.2.2.2.2/c.3.3.3.3.3.3/d.4.4.4.4.4.4.4.4.4
```

**Comment by bblommers** [comment]
Hi @igorsimko, thanks for raising this! That is terrible performance indeed - matching that URL took more than 5 minutes on my laptop.

I've raised a PR where I changed the matching to `[^.]+`, i.e. everything but dots, so we get the performance bump but also keep it flexible.

**Comment by igorsimko** [comment]
Thank you @bblommers for looking into it that quickly!
