### ISSUE TITLE
Enhancement: Add Step Functions to support resourcegroupstagging

### ISSUE THREAD

**Issue by zkarpinski** [getmoto/moto#8212]
Per the [AWS docs](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html) Step Function support the Resource Groups Tagging API.

It looks like there is a custom implementation for tags for step functions. @bblommers is there a special case with Step Functions or is this a simple use-case to add this support?

**Comment by bblommers** [comment]
Hi @zkarpinski, that should be relatively straightforward.

The Resource Groups Tagging implementation in Moto simply checks the backend for each service, and uses the tags already stored there. So it would be a matter if adding an additional logic-block for SFN here:

https://github.com/getmoto/moto/blob/c6aea5223488141e64d5ee9efa7d5c9200084e54/moto/resourcegroupstaggingapi/models.py#L205

**Comment by zkarpinski** [comment]
@bblommers Easy enough thank you for the guidance. Submitted a pr!
