### ISSUE TITLE
ecs update_service forceNewDeployment should update service.deployments[0]["createdAt"]

### ISSUE THREAD

**Issue by suonto** [getmoto/moto#8219]
**how to reproduce the issue**: mock_aws and call
```
ecs_client.update_service(
   cluster=service.cluster_name,
   service=service.service_name,
   forceNewDeployment=True,
)
```
**what you expected to happen**
On next `describe_services` call, response `deployments[0]["createdAt"]` should be set to the time when service was updated

**what actually happens** 

- `deployments[0]["createdAt"]` remains the same when forcing redeployment
- the `update_service` response actually has updated timestamp. It's just not reflected on future describe calls.

**Comment by bblommers** [comment]
Hi @suonto, thank you for letting us know! This should be fixed in the next version (5.0.18)
