### ISSUE TITLE
DDB Streams: Event name is always insert

### ISSUE THREAD

**Issue by dacevedo12** [getmoto/moto#8253]
https://github.com/getmoto/moto/blob/036c4a1d9270a4307805922b0c0195e60f5b7676/moto/awslambda/models.py#L2285

should be `item.to_json()["event_name"]` as set by https://github.com/getmoto/moto/blob/036c4a1d9270a4307805922b0c0195e60f5b7676/moto/dynamodb/models/table.py#L202-L207 shouldn't it?

**Comment by bblommers** [comment]
Hi @dacevedo12, welcome to Moto! You're right, it looks like we should pass the `event_name` to the `send_dynamodb_items`-method.

Do you want to open a PR for this?

**Comment by dacevedo12** [comment]
@bblommers done https://github.com/getmoto/moto/pull/8265
