### ISSUE TITLE
Missing networkConfiguration in create_service and describe_service of ECS Client

### ISSUE THREAD

**Issue by cschroeer** [getmoto/moto#8258]
## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.

```
def setup_ecs(client, ec2):
    """test helper"""
    EXAMPLE_AMI_ID = "ami-12c6146b"
    vpc = ec2.create_vpc(CidrBlock="10.0.0.0/16")
    subnet = ec2.create_subnet(VpcId=vpc.id, CidrBlock="10.0.0.0/18")
    sg = ec2.create_security_group(
        VpcId=vpc.id, GroupName="test-ecs", Description="moto ecs"
    )
    test_cluster_name = os.getenv("AWS_ECS_CLUSTER_NAME")
    client.create_cluster(clusterName=test_cluster_name)
    test_instance = ec2.create_instances(
        ImageId=EXAMPLE_AMI_ID, MinCount=1, MaxCount=1
    )[0]
    instance_id_document = json.dumps(
        ec2_utils.generate_instance_identity_document(test_instance)
    )
    client.register_container_instance(
        cluster=test_cluster_name, instanceIdentityDocument=instance_id_document
    )
    client.register_task_definition(
        family="test-task",
        containerDefinitions=[
            {
                "name": "test-container",
                "image": "amazonlinux",
                "cpu": 10,
                "memory": 500,
                "essential": True,
                "entryPoint": ["/bin/sh", "-c"],
                "command": ["echo hello"],
            }
        ],
        requiresCompatibilities=["FARGATE"],
        networkMode="awsvpc",
        cpu="256",
        memory="512",
    )

    return subnet, sg


def test():
    with mock_aws():
        ECS_REGION = os.getenv("AWS_ECS_REGION")
        client = boto3.client("ecs", region_name=ECS_REGION)
        ec2_client = boto3.client("ec2", region_name=ECS_REGION)
        ec2 = boto3.resource("ec2", region_name=ECS_REGION)

        setup_resources = setup_ecs(client, ec2)
        response = client.create_service(
            cluster=os.getenv("AWS_ECS_CLUSTER_NAME"),
            serviceName=os.getenv("AWS_ECS_SERVICE_NAME"),
            taskDefinition="test-task",
            desiredCount=1,
            launchType="FARGATE",
            placementConstraints=[],
            placementStrategy=[],
            deploymentConfiguration={
                "maximumPercent": 100,
                "minimumHealthyPercent": 0,
            },
            networkConfiguration={
                "awsvpcConfiguration": {
                    "subnets": [setup_resources[0].id],
                    "securityGroups": [setup_resources[1].id],
                }
            },
            healthCheckGracePeriodSeconds=120,
            schedulingStrategy="REPLICA",
        )
```

   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?

I expect, that there are networkConfiguration in the responses. 

   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?

There are no networkConfiguration in the responses. 

   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.

moto = "==5.0.13"

   If you do not provide all of these things, it will take us much longer to
   fix your problem.

**Comment by rafcio19** [comment]
@bblommers I can look into this.
