### ISSUE TITLE
ECR only describe_images returns all the tags for given image

### ISSUE THREAD

**Issue by jcieniek-trek10** [getmoto/moto#8269]
If image has multiple tags, only the describe_images operation returns them. Other ones, like list_images return only the latest tag.

**Comment by bblommers** [comment]
Hi @jcieniek-trek10, I'm not able to reproduce this I'm afraid. Can you post a reproducible test case to show what you mean?

Also, what version of Moto are you on?

**Comment by jcieniek-trek10** [comment]
Hi! My moto version is 5.0.20, please find test script attached...
[moto_issue_test.zip](https://github.com/user-attachments/files/17662458/moto_issue_test.zip)

**Comment by bblommers** [comment]
Ah, I see - thank you for putting that together @jcieniek-trek10. I've submitted a PR with a fix!

**Comment by jcieniek-trek10** [comment]
Thank you for your fix @bblommers !
