### ISSUE TITLE
Opensearch: describe_domain_config does not return EngineVersion.Status

### ISSUE THREAD

**Issue by ktech-rob** [getmoto/moto#8271]
When calling describe_domain_config the `Status` key and values are omitted:

Expected:
```json
{
    "DomainConfig": {
        "EngineVersion": {
            "Options": "string",
            "Status": {
                "CreationDate": datetime(2015, 1, 1),
                "UpdateDate": datetime(2015, 1, 1),
                "UpdateVersion": 123,
                "State": "RequiresIndexDocuments"|"Processing"|"Active",
                "PendingDeletion": True|False
            }
        }
}
```
Source: [boto3: describe_domain_config](https://boto3.amazonaws.com/v1/documentation/api/1.26.82/reference/services/opensearch/client/describe_domain_config.html)

Actual:
```json
{
    "DomainConfig": {
        "EngineVersion": {
            "Options": "OpenSearch_2.15"
        }
}
```

### Moto Version

5.0.18

**Comment by bblommers** [comment]
Hi @ktech-rob, welcome to Moto, and thank you for raising this! Marking it as an enhancement to add these fields.

**Comment by ktech-rob** [comment]
@rafcio19 amazing, thank you so much!
