### ISSUE TITLE
State Manager not working on batch job without Docker

### ISSUE THREAD

**Issue by CesarCMa** [getmoto/moto#8287]
## Context

I'm trying to test a simple function that wraps boto3 and cancels a batch job given its `job_id`.

In order to achieve so, I've tried to use the `state_manager` from moto to be able to cancel the job. I'm running the test with docker disabled, as my package is already running on a docker container.

## Issue
The initial implementation of the test using my custom function to cancel the job didn't seem to work properly. The status of the job was always set to `SUCCESS` even increasing the seconds provided to the `state_manager` to +10.

After some debugging, I decided to replicate the test implemented on the `test_cancel_pending_job` from [test_batch_integration module.](https://github.com/getmoto/moto/blob/master/tests/test_moto_api/state_manager/test_batch_integration.py), but without using docker:

```Python
import datetime
import json
import time
import boto3

from uuid import uuid4
from moto import mock_aws
from moto.moto_api import state_manager

from anton import actions, REGION

@mock_aws(config={"batch": {"use_docker": False}})
def test_batch_terminate_job(aws_credentials):

    iam_client = boto3.client('iam', region_name = REGION)
    batch_client = boto3.client('batch', region_name = REGION)


    role_name = f"{str(uuid4())[0:6]}"
    assume_role_policy = json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {"Service": "batch.amazonaws.com"},
                    "Action": "sts:AssumeRole",
                }
            ],
        }
    )
    resp = iam_client.create_role(
        RoleName=role_name, AssumeRolePolicyDocument=assume_role_policy
    )
    iam_arn = resp["Role"]["Arn"]
    iam_client.create_instance_profile(InstanceProfileName=role_name)
    iam_client.add_role_to_instance_profile(
        InstanceProfileName=role_name, RoleName=role_name
    )

    state_manager.set_transition(
        "batch::job", transition={"progression": "time", "seconds": 10}
    )

    commands = ["echo", "hello"]
    job_def_arn, queue_arn = prepare_job(batch_client, commands, iam_arn, "test")

    resp = batch_client.submit_job(
        jobName="test_job_name",
        jobQueue=queue_arn,
        jobDefinition=job_def_arn,
    )
    job_id = resp["jobId"]
    _wait_for_job_statuses(batch_client, job_id, ["FAILED"], seconds_to_wait=20)

    resp = batch_client.describe_jobs(jobs=[job_id])
    assert resp["jobs"][0]["jobName"] == "test_job_name"
    assert resp["jobs"][0]["statusReason"] == "test_cancel"



def prepare_job(batch_client, commands, iam_arn, job_def_name):
    compute_name = str(uuid4())[0:6]
    resp = batch_client.create_compute_environment(
        computeEnvironmentName=compute_name,
        type="UNMANAGED",
        state="ENABLED",
        serviceRole=iam_arn,
    )
    arn = resp["computeEnvironmentArn"]

    resp = batch_client.create_job_queue(
        jobQueueName=str(uuid4())[0:6],
        state="ENABLED",
        priority=123,
        computeEnvironmentOrder=[{"order": 123, "computeEnvironment": arn}],
    )
    queue_arn = resp["jobQueueArn"]
    resp = batch_client.register_job_definition(
        jobDefinitionName=job_def_name,
        type="container",
        containerProperties={
            "image": "busybox:latest",
            "vcpus": 1,
            "memory": 128,
            "command": commands,
        },
    )
    job_def_arn = resp["jobDefinitionArn"]
    return job_def_arn, queue_arn

def _wait_for_job_statuses(client, job_id, statuses, seconds_to_wait=30):
    wait_time = datetime.datetime.now() + datetime.timedelta(seconds=seconds_to_wait)
    last_job_status = None
    while datetime.datetime.now() < wait_time:
        resp = client.describe_jobs(jobs=[job_id])
        last_job_status = resp["jobs"][0]["status"]
        if last_job_status in statuses:
            break
        time.sleep(0.1)
    else:
        raise RuntimeError(
            f"Time out waiting for job status {statuses}!\n Last status: {last_job_status}"
        )
```

Now this test fails with `RuntimeError: Time out waiting for job status ['FAILED']!`, and if I debug and check the status of the job just after submitting it, I get a `SUCCEEDED` every time, even increasing the `seconds` on the `state_manager` to +10.

Is it possible that `state_manager` **does not work when docker is deactivated?** I haven't found any info about it on the documentation.

Thanks in advance!

## Dependencies

* Python 3.11.2
* Boto 1.34.3
* Moto 5.0.18

All of them installed using Poetry 1.4.2

**Comment by bblommers** [comment]
Hi @CesarCMa! Batch-without-docker is meant to be as fast as possible and immediately marks jobs as successful, so there is no concept of state management really.

If you want to mark a job as `failed`, you could set the following env variable:
```
MOTO_SIMPLE_BATCH_FAIL_AFTER=0
```
That way the job will be marked as a failure immediately (after 0 seconds). 

Note that you can set the variable to any positive integer if you want to simulate a delay in how long the `submit_job` takes to to mark it as a failure, but it always syncronous - so there is no option to 'catch' a job running this way.

**Comment by CesarCMa** [comment]
Alright, thanks for answering!
