### ISSUE TITLE
Feature: Determine if managed master password is enable on RDS if describe_db_clusters is used

### ISSUE THREAD

**Issue by lukaalba** [getmoto/moto#8294]
I am currently working on a script which upgrades RDS instances with Blue-Green Deployments. Right now this requires to disable the Managed Master Password before creating the Blue-Green Deployment, so the script includes setting the Masterpassword statically and after completing the Upgrade, switching back to Managed Master Password.

Right now there is no way to tell if these switches work as expected, since `describe_db_clusters` does not return any information whether the master secret is managed or not. In the original boto3 response, `describe_db_clusters` contain the dict `MasterUserSecret` with further information about the Secret.

I happily contribute this feature if desired.

**Comment by bblommers** [comment]
Hi @lukaalba, a PR would be very welcome!

There is some generic info on how to contribute to Moto here:
https://docs.getmoto.org/en/latest/docs/contributing/index.html

The exact response of the `describe_db_clusters`-method is determined here, so the template used there would need some changes:
https://github.com/getmoto/moto/blob/bf49e22f41be7444dc20e05dfa5dd13f25672eba/moto/rds/responses.py#L252

(I haven't looked into it, but there are potentially also changes necessary to the `create_db_clusters`/`update_db_clusters`-methods to ensure that we store/manage that value in the first place.)

Please let me know if you have any questions!

**Comment by lukaalba** [comment]
Hi @bblommers,

sorry for the late response, I had other work related stuff to do in the last couple of weeks. I've added my PR to this issue.
