### ISSUE TITLE
[secuity]Don't use pkcs#1v15

### ISSUE THREAD

**Issue by cryptochecktool** [getmoto/moto#8317]
The current encryption scheme, PKCS#1 v1.5 , is no longer considered secure due to known vulnerabilities. It is recommended to switch to PSS (Probabilistic Signature Scheme) or OAEP (Optimal Asymmetric Encryption Padding) for enhanced security.

code is:https://github.com/getmoto/moto/blob/c9536b117e39fef41b9ccb5e07463eecda15ba2a/moto/sns/models.py#L357
## Rationale

- **Security Concerns**: PKCS#1 v1.5 is susceptible to attacks like Bleichenbacher's attack, which can lead to key compromise.
- **Standardization**: Newer standards and libraries are moving away from PKCS#1 v1.5 in preference of PSS or OAEP.

## Proposed Solution

- **PSS**: Offers better security for RSA signatures with resistance to chosen-message attacks.
- **OAEP**: Provides improved security for RSA encryption with resistance to chosen-ciphertext attacks.

**Comment by bblommers** [comment]
AWS uses this padding scheme, so we do as well.
