### ISSUE TITLE
Lambda update_function_code not incrementing Version when Publish=True

### ISSUE THREAD

**Issue by ekolve** [getmoto/moto#8337]
When running the following beneath moto
```python
import boto3
client = boto3.client('lambda', region_name='us-east-2')
res = client.update_function_code(FunctionName='test-function', ZipFile=<somearchive>, Publish=True)
print(res["Version"])
```
After the first invocation this prints out `1`, but this also prints out  `1` for both results if the following is run:
```python
import boto3
client = boto3.client('lambda', region_name='us-east-2')
res = client.update_function_code(FunctionName='test-function', ZipFile=<somearchive>, Publish=True)
print(res["Version"])
res = client.update_function_code(FunctionName='test-function', ZipFile=<somearchive>, Publish=True)
print(res["Version"])
```
I would expect the second invocation to print out `2` since a new version is getting published.

**Comment by ekolve** [comment]
I tracked down the issue to this:
https://github.com/getmoto/moto/blob/edc7947883a82f8a995d98e9a3a21240ea90a53b/moto/awslambda/models.py#L1691

```python
            if latest_published.code_sha_256 == function.code_sha_256:
                # Nothing has changed, don't publish
                return latest_published
```
I don't believe AWS applies the same logic on their side when code is published.  They seem to publish a new version even if the code hasn't changed.

**Comment by bblommers** [comment]
According to the documentation, AWS does not publish a new version when calling `publish_version` with the same code. 
From https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html:

> Lambda publishes a new function version only if the code has never been published, or if the code has changed from the last published version. If there is no change, the function version remains at the last published version.

Does the `update_function_code` behave differently? If so, that would be.. confusing.

**Comment by ekolve** [comment]
Here is what I am observing with AWS:
```python
import boto3
client = boto3.client('lambda', region_name='us-west-2')
res = client.update_function_code(FunctionName='test-handler', ZipFile=<archive>, Publish=True)
print(res["Version"]) # prints 1
res = client.update_function_code(FunctionName='test-handler', ZipFile=<archive>, Publish=True) # archive is identical to the first call
print(res["Version"]) # prints 2
res = client.publish_version(FunctionName='test-handler')
print(res["Version"]) # prints 2
```
So the docs for `publish_version` are correct, the docs for `update_function_code` https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda/client/update_function_code.html
state the following:
```
Publish (boolean) – Set to true to publish a new version of the function after updating the code. 
This has the same effect as calling PublishVersion separately.
```

Given all this, I'm not sure what the right course of action is with respect to mocking.  Their docs are ambiguous and I can modify my test to slightly modify my archive to trigger the version to get updated with moto, but it would be nice if AWS would state explicitly what should happen for this case.

**Comment by bblommers** [comment]
Hi @ekolve, I've done some more testing, and the actual behaviour seems to be that Lambda publishes a new function version only if the update_function_code or update_function_configuration functions have been called.

Whether or not actual source code has changed is irrelevant.

The attached PR fixes this, and adds some tests that have been verified against AWS.
