### ISSUE TITLE
The passthrough urls are regex, whereas the examples in the documentation use wildcards.

### ISSUE THREAD

**Issue by AlirezaRoshanzamir** [getmoto/moto#8339]
Contrary to the example provided in the documentation, the parameter "core/passthrough/urls" values are regular expressions, not wildcards.

Documentation latest version:
![image](https://github.com/user-attachments/assets/0526cbac-55d5-49c2-ab93-451008e3ab47)

URL pattern evaluation code in master:

https://github.com/getmoto/moto/blob/8d673068b3821d33407c2a2eecb735802d944d16/moto/core/config.py#L73-L77

I've also tested the config, and it worked successfully with the regex patterns.

**Comment by bblommers** [comment]
Hi @AlirezaRoshanzamir, fair point - it isn't completely obvious that this is a regex. I've updated the docs, hoepfully this is clearer now.
