### ISSUE TITLE
Limit shouldn't be applied before Filter when listing users

### ISSUE THREAD

**Issue by WeatherGod** [getmoto/moto#8363]
Using the current version of moto, if you run cognito-idp's list_users() with both Limit and Filter keywords, the limit is applied before the filter. So, if you are searching for a user with a particular sub that isn't the first item in the user pool, and you set Limit to 1, then it will always fail to find it because in `moto/cognito-idp/responses.py`, it calls the backend for the unfiltered list of users limited by the Limit keyword, and then filters that.

**Comment by iknowright** [comment]
Hi I would like to take this work

**Comment by WeatherGod** [comment]
Thank you, @iknowright!
