### ISSUE TITLE
DynamoDB KeyExpression are not evaluated the right way

### ISSUE THREAD

**Issue by Kruspe** [getmoto/moto#8414]
When querying a table with a composite key like `PK` and `SK` depending on the brackets set inside the KeyConditions some queries fail.

## Steps to reproduce:

1. Parsing the following key condition does not work at all
```sh
aws dynamodb query --table-name <TABLE_NAME> --endpoint-url <MOTO_ENDPOINT> --key-condition-expression "(#0 = :0) AND (BEGINS_WITH(#1, :1))" --expression-attribute-values '{":0": {"S": "TEST"}, ":1": {"S": "ABC"}}' --expression-attribute-names '{"#0": "PK", "#1": "SK"}'
```
This produces the following error with moto although it is a valid query:
`An error occurred (ValidationException) when calling the Query operation: Query condition missed key schema element: SK`

2. Given a table with a few entries like:

| PK  | SK |
| ------------- | ------------- |
| TEST  | id#aa  |
| TEST  | id#ab  |
| TEST  | id#ad  |

```sh
aws dynamodb query --table-name <TABLE_NAME> --endpoint-url <MOTO_ENDPOINT> --key-condition-expression "(#0 = :0) AND (#1 BETWEEN :1 AND :2)" --expression-attribute-values '{":0": {"S": "TEST"}, ":1": {"S": "AB"}, ":2": {"S": "AB"}}' --expression-attribute-names '{"#0": "PK", "#1": "SK"}'
```
While this query should only return 1 item (the second item) it returns all three items from the table above.

**Comment by bblommers** [comment]
Hi @Kruspe, welcome to Moto! It looks like this is both because of the parenthesis in front of the sort key - I've opened a PR with a fix.
