### ISSUE TITLE
Have function decorators support coroutines

### ISSUE THREAD

**Issue by thehesiod** [getmoto/moto#905]
looks like `decorate_callable` needs to be updated to support coroutines

**Comment by spulec** [comment]
PR welcome if anyone gets time. This isn't something I personally need.

**Comment by bblommers** [comment]
Hi @thehesiod, is this still something you're interested in?

**Comment by bblommers** [comment]
I'm going to close this - I'm assuming it's no longer necessary. Let me know otherwise.
